Green House software: GreenHouse Class Reference
GreenHouse Class Reference
#include <GreenHouse.h>
Public Member Functions
GreenHouse ()
Construct a new Green House object.
~GreenHouse ()
Destroy the Green House object.
void startSystem ()
Start the system.
void mainSystem ()
Main system, after the system is started, you call this method to manage the system with your options that contains your privilege.
Private Member Functions
void save (int id)
Save the system.
void sleep ()
Sleep the system.
void manageLogin ()
Manage the login.
void manageAdmin ()
Manage the admin.
void manageEmployee ()
Manage the employee.
void manageGuest ()
Manage the guest.
void manageUpdateUser ()
Manage the update user.
void manageCreateUser ()
Manage the create user.
void manageDeleteUser ()
Manage the delete user.
bool searchUser (std::string name, std::string password, std::string nif)
Manage search user.
Private Attributes
AlarmSensors * alarm_
This attribute is the AlarmSensors object (set of pointers to sensors).
MonitoringSystem * ms_
This attribute is the MonitoringSystem object.
UsersServer * us_
This attribute is the UsersServer object (set of pointers to users).
ManageCameras * mc_
This attribute is the ManageCameras object (set of pointers to cameras).
Detailed Description
Definition at line 17 of file GreenHouse.h.
Constructor & Destructor Documentation
GreenHouse()
GreenHouse::GreenHouse ()
Construct a new Green House object.
Definition at line 17 of file GreenHouse.cpp.
     : alarm_(new AlarmSensors()),
       ms_(new MonitoringSystem(new ScreenHardware(true),
                                new KeyboardHardware(true),
                                new SwitchHardware(true))),
       us_(new UsersServer()),
       mc_(new ManageCameras()) {
   // Constructor ahora inicializa todos los atributos privados correctamente.
 }
~GreenHouse()
GreenHouse::~GreenHouse ()
Destroy the Green House object.
Definition at line 29 of file GreenHouse.cpp.
{
   // Destructor ahora elimina todos los atributos privados correctamente.
   delete alarm_;
   delete ms_;
   delete us_;
   delete mc_;
 }
References alarm_, mc_, ms_, and us_.
Member Function Documentation
mainSystem()
void GreenHouse::mainSystem ()
Main system, after the system is started, you call this method to manage the system with your options that contains your privilege.
Definition at line 317 of file GreenHouse.cpp.
{
   // SI la seleccion en startSystem() es 1, entonces se ejecuta el loginScreen()
   // Hacemos mejor un switch para que sea más fácil de leer
   switch (ms_->getSelection()) {
   case 1:
     ms_->loginScreen();
     manageLogin();
     break;
   case 2:
     ms_->exitScreen();
     break;
   default:
     ms_->displayErrorScreen();
     break;
   }
   /* if (ms_->getSelection() == 1)
   {
       us_->loadUsersFromFile();
       ms_->loginScreen();
   } else if (ms_->getSelection() == 2)
   {
       ms_->exitScreen();
   } else {
       ms_->displayErrorScreen();
   }
   */
 }
References MonitoringSystem::displayErrorScreen(), MonitoringSystem::exitScreen(), MonitoringSystem::getSelection(), MonitoringSystem::loginScreen(), manageLogin(), and ms_.
Referenced by main().
manageAdmin()
void GreenHouse::manageAdmin () private
Manage the admin.
Definition at line 91 of file GreenHouse.cpp.
{
   bool exit = false;
   // Mostramos la ventana de admin
   do {
     // Poner unos sefgundos de espera para que se vea el mensaje
     sleep();
     ms_->mainWindowAdmin();
     switch (ms_->getSelection()) {
     case 1:
       manageCreateUser();
       // us_->saveUsersToFile();
       break;
     case 2:
       manageDeleteUser();
       // us_->saveUsersToFile();
       break;
     case 3:
       manageUpdateUser();
       // us_->saveUsersToFile();
       break;
     case 4:
       ms_->displayUsersScreen();
       us_->printUsersServer();
       break;
     case 5:
       ms_->createAlarmScreen();
       alarm_->addSensor(ms_->getIdAlarm(), ms_->getTypeAlarm());
       break;
     case 6:
       ms_->deleteAlarmScreen();
       alarm_->deleteSensor(ms_->getIdSelectedAlarm());
       break;
     case 7:
       ms_->displaySensorsScreen();
       alarm_->displayAllSensorsData();
       break;
     case 8:
       ms_->displayAlarmsScreen();
       alarm_->displayAlarmStatus();
       break;
     case 9:
       ms_->turnOnOffSystemScreen();
       alarm_->turnOnOffSystem(ms_->getSelection());
       break;
     case 10:
       // Enseñar camaras
       ms_->displayCameraScreen();
       mc_->collectAndDisplayData();
       break;
     case 11:
       // Crear camera
       ms_->createCameraScreen();
       mc_->createCamera(ms_->getIdCamera(), ms_->getTypeCamera());
       break;
     case 12:
       // Borrar camera
       ms_->deleteCameraScreen();
       mc_->removeCamera(ms_->getIdSelectedCamera());
       break;
     case 13:
       // Apagar o encender camaras
       ms_->turnOnOffCameraScreen();
       mc_->turnOnOffCameras(ms_->getSelection());
       break;
     case 14:
       // Guardar camaras
       ms_->saveCameraScreen();
       mc_->saveCameras();
       break;
     case 15:
       ms_->saveUsersScreen();
       us_->saveUsersToFile();
       break;
     case 16:
       ms_->saveAlarmScreen();
       alarm_->saveSensorsData();
       break;
     case 17:
       ms_->cleanScreen();
       save(1);
       sleep();
       ms_->exitScreen();
       exit = true;
       break;
     default:
       ms_->displayErrorScreen();
       break;
     }
   } while (!exit);
 }
References AlarmSensors::addSensor(), alarm_, MonitoringSystem::cleanScreen(), ManageCameras::collectAndDisplayData(), MonitoringSystem::createAlarmScreen(), ManageCameras::createCamera(), MonitoringSystem::createCameraScreen(), MonitoringSystem::deleteAlarmScreen(), MonitoringSystem::deleteCameraScreen(), AlarmSensors::deleteSensor(), MonitoringSystem::displayAlarmsScreen(), AlarmSensors::displayAlarmStatus(), AlarmSensors::displayAllSensorsData(), MonitoringSystem::displayCameraScreen(), MonitoringSystem::displayErrorScreen(), MonitoringSystem::displaySensorsScreen(), MonitoringSystem::displayUsersScreen(), MonitoringSystem::exitScreen(), MonitoringSystem::getIdAlarm(), MonitoringSystem::getIdCamera(), MonitoringSystem::getIdSelectedAlarm(), MonitoringSystem::getIdSelectedCamera(), MonitoringSystem::getSelection(), MonitoringSystem::getTypeAlarm(), MonitoringSystem::getTypeCamera(), MonitoringSystem::mainWindowAdmin(), manageCreateUser(), manageDeleteUser(), manageUpdateUser(), mc_, ms_, UsersServer::printUsersServer(), ManageCameras::removeCamera(), save(), MonitoringSystem::saveAlarmScreen(), ManageCameras::saveCameras(), MonitoringSystem::saveCameraScreen(), AlarmSensors::saveSensorsData(), MonitoringSystem::saveUsersScreen(), UsersServer::saveUsersToFile(), sleep(), ManageCameras::turnOnOffCameras(), MonitoringSystem::turnOnOffCameraScreen(), AlarmSensors::turnOnOffSystem(), MonitoringSystem::turnOnOffSystemScreen(), and us_.
Referenced by manageLogin().
manageCreateUser()
void GreenHouse::manageCreateUser () private
Manage the create user.
Definition at line 57 of file GreenHouse.cpp.
{
   ms_->createUserScreen();
   us_->createUser(ms_->getNameSelectedUser(), ms_->getNIFSelectedUser(),
                   ms_->getPasswordSelectedUser(),
                   ms_->getPrivilegesSelectedUser(),
                   ms_->getEmailSelectedUser());
 }
References UsersServer::createUser(), MonitoringSystem::createUserScreen(), MonitoringSystem::getEmailSelectedUser(), MonitoringSystem::getNameSelectedUser(), MonitoringSystem::getNIFSelectedUser(), MonitoringSystem::getPasswordSelectedUser(), MonitoringSystem::getPrivilegesSelectedUser(), ms_, and us_.
Referenced by manageAdmin().
manageDeleteUser()
void GreenHouse::manageDeleteUser () private
Manage the delete user.
Definition at line 47 of file GreenHouse.cpp.
{
   ms_->deleteUserScreen();
   if (searchUser(ms_->getNameSelectedUser(), ms_->getPasswordSelectedUser(),
                  ms_->getNIFSelectedUser())) {
     us_->deleteUser(ms_->getNIFSelectedUser());
   } else {
     printf("Usuario no encontrado\n");
   }
 }
References UsersServer::deleteUser(), MonitoringSystem::deleteUserScreen(), MonitoringSystem::getNameSelectedUser(), MonitoringSystem::getNIFSelectedUser(), MonitoringSystem::getPasswordSelectedUser(), ms_, searchUser(), and us_.
Referenced by manageAdmin().
manageEmployee()
void GreenHouse::manageEmployee () private
Manage the employee.
Definition at line 182 of file GreenHouse.cpp.
{
   bool exit = false;
   // Mostramos la ventana de employee
   do {
     sleep();
     ms_->mainWindowEmployee();
     switch (ms_->getSelection()) {
     case 1:
       ms_->createAlarmScreen();
       alarm_->addSensor(ms_->getIdAlarm(), ms_->getTypeAlarm());
       break;
     case 2:
       ms_->deleteAlarmScreen();
       alarm_->deleteSensor(ms_->getIdSelectedAlarm());
       break;
     case 3:
       ms_->displaySensorsScreen();
       alarm_->displayAllSensorsData();
       break;
     case 4:
       ms_->displayAlarmsScreen();
       alarm_->displayAlarmStatus();
       break;
     case 5:
       ms_->turnOnOffSystemScreen();
       alarm_->turnOnOffSystem(ms_->getSelection());
       break;
     case 6:
       // Enseñar camaras
       ms_->displayCameraScreen();
       mc_->collectAndDisplayData();
       break;
     case 7:
       // Crear camera
       ms_->createCameraScreen();
       mc_->createCamera(ms_->getIdCamera(), ms_->getTypeCamera());
       break;
     case 8:
       // Borrar camera
       ms_->deleteCameraScreen();
       mc_->removeCamera(ms_->getIdSelectedCamera());
       break;
     case 9:
       // Apagar o encender camaras
       ms_->turnOnOffCameraScreen();
       mc_->turnOnOffCameras(ms_->getSelection());
       break;
     case 10:
       // Guardar camaras
       ms_->saveCameraScreen();
       mc_->saveCameras();
       break;
     case 11:
       ms_->saveAlarmScreen();
       alarm_->saveSensorsData();
       break;
     case 12:
       ms_->cleanScreen();
       save(2);
       sleep();
       ms_->exitScreen();
       exit = true;
       break;
     default:
       ms_->displayErrorScreen();
       break;
     }
   } while (!exit);
 }
References AlarmSensors::addSensor(), alarm_, MonitoringSystem::cleanScreen(), ManageCameras::collectAndDisplayData(), MonitoringSystem::createAlarmScreen(), ManageCameras::createCamera(), MonitoringSystem::createCameraScreen(), MonitoringSystem::deleteAlarmScreen(), MonitoringSystem::deleteCameraScreen(), AlarmSensors::deleteSensor(), MonitoringSystem::displayAlarmsScreen(), AlarmSensors::displayAlarmStatus(), AlarmSensors::displayAllSensorsData(), MonitoringSystem::displayCameraScreen(), MonitoringSystem::displayErrorScreen(), MonitoringSystem::displaySensorsScreen(), MonitoringSystem::exitScreen(), MonitoringSystem::getIdAlarm(), MonitoringSystem::getIdCamera(), MonitoringSystem::getIdSelectedAlarm(), MonitoringSystem::getIdSelectedCamera(), MonitoringSystem::getSelection(), MonitoringSystem::getTypeAlarm(), MonitoringSystem::getTypeCamera(), MonitoringSystem::mainWindowEmployee(), mc_, ms_, ManageCameras::removeCamera(), save(), MonitoringSystem::saveAlarmScreen(), ManageCameras::saveCameras(), MonitoringSystem::saveCameraScreen(), AlarmSensors::saveSensorsData(), sleep(), ManageCameras::turnOnOffCameras(), MonitoringSystem::turnOnOffCameraScreen(), AlarmSensors::turnOnOffSystem(), and MonitoringSystem::turnOnOffSystemScreen().
Referenced by manageLogin().
manageGuest()
void GreenHouse::manageGuest () private
Manage the guest.
Definition at line 252 of file GreenHouse.cpp.
{
   bool exit = false;
   // Mostramos la ventana de guest
   do {
     sleep();
     ms_->mainWindowGuest();
     switch (ms_->getSelection()) {
     case 1:
       ms_->displaySensorsScreen();
       alarm_->displayAllSensorsData();
       break;
     case 2:
       ms_->displayAlarmsScreen();
       alarm_->displayAlarmStatus();
       break;
     case 3:
       // Enseñar camaras
       ms_->displayCameraScreen();
       mc_->collectAndDisplayData();
       break;
     case 4:
       ms_->cleanScreen();
       ms_->exitScreen();
       exit = true;
       break;
     default:
       ms_->displayErrorScreen();
       break;
     }
   } while (!exit);
 }
References alarm_, MonitoringSystem::cleanScreen(), ManageCameras::collectAndDisplayData(), MonitoringSystem::displayAlarmsScreen(), AlarmSensors::displayAlarmStatus(), AlarmSensors::displayAllSensorsData(), MonitoringSystem::displayCameraScreen(), MonitoringSystem::displayErrorScreen(), MonitoringSystem::displaySensorsScreen(), MonitoringSystem::exitScreen(), MonitoringSystem::getSelection(), MonitoringSystem::mainWindowGuest(), mc_, ms_, and sleep().
Referenced by manageLogin().
manageLogin()
void GreenHouse::manageLogin () private
Manage the login.
Definition at line 284 of file GreenHouse.cpp.
{
   // Cargamos los usuarios del archivo
   us_->loadUsersFromFile();
   // Cargamos los sensores del archivo
   alarm_->loadSensorsData();
   // Cargamos las camaras del archivo
   mc_->loadCameras();
   sleep();
   ms_->cleanScreen();
   // Comprobamos si el usuario y la contraseña son correctos
   if (us_->findUserLogin(ms_->getName(), ms_->getPassword(), ms_->getNIF())) {
     printf("Usuario correcto\n");
     // ahora tengo qeu ver que tipo de usuario es
     // si es admin, employee o guest
     // si es admin
     if (us_->getPrivileges(ms_->getNIF()) == "ADMIN") {
       manageAdmin();
     } else if (us_->getPrivileges(ms_->getNIF()) == "EMPLOYEE") {
       manageEmployee();
     } else {
       manageGuest();
     }
   } else {
     printf("Usuario incorrecto\n");
     sleep();
     ms_->exitScreen();
   }
 }
References alarm_, MonitoringSystem::cleanScreen(), MonitoringSystem::exitScreen(), UsersServer::findUserLogin(), MonitoringSystem::getName(), MonitoringSystem::getNIF(), MonitoringSystem::getPassword(), UsersServer::getPrivileges(), ManageCameras::loadCameras(), AlarmSensors::loadSensorsData(), UsersServer::loadUsersFromFile(), manageAdmin(), manageEmployee(), manageGuest(), mc_, ms_, sleep(), and us_.
Referenced by mainSystem().
manageUpdateUser()
void GreenHouse::manageUpdateUser () private
Manage the update user.
Definition at line 65 of file GreenHouse.cpp.
{
   ms_->updateUserScreen();
   if (searchUser(ms_->getNameSelectedUser(), ms_->getPasswordSelectedUser(),
                  ms_->getNIFSelectedUser())) {
     us_->updateUser(ms_->getEmailSelectedUser(), ms_->getNIFSelectedUser(),
                     ms_->getPasswordSelectedUser(),
                     ms_->getPrivilegesSelectedUser(),
                     ms_->getEmailSelectedUser());
   } else {
     printf("Usuario no encontrado\n");
   }
 }
References MonitoringSystem::getEmailSelectedUser(), MonitoringSystem::getNameSelectedUser(), MonitoringSystem::getNIFSelectedUser(), MonitoringSystem::getPasswordSelectedUser(), MonitoringSystem::getPrivilegesSelectedUser(), ms_, searchUser(), UsersServer::updateUser(), MonitoringSystem::updateUserScreen(), and us_.
Referenced by manageAdmin().
save()
void GreenHouse::save (int id) private
Save the system.
Definition at line 80 of file GreenHouse.cpp.
{
   if (id == 1) {
     us_->saveUsersToFile();
     alarm_->saveSensorsData();
     mc_->saveCameras();
   } else if (id == 2) {
     alarm_->saveSensorsData();
     mc_->saveCameras();
   }
 }
References alarm_, mc_, ManageCameras::saveCameras(), AlarmSensors::saveSensorsData(), UsersServer::saveUsersToFile(), and us_.
Referenced by manageAdmin(), and manageEmployee().
searchUser()
bool GreenHouse::searchUser (std::string name, std::string password, std::string nif) private
Manage search user.
Definition at line 42 of file GreenHouse.cpp.
{
   return us_->findUserLogin(name, password, nif);
 }
References UsersServer::findUserLogin(), and us_.
Referenced by manageDeleteUser(), and manageUpdateUser().
sleep()
void GreenHouse::sleep () private
Sleep the system.
Definition at line 78 of file GreenHouse.cpp.
 { system("sleep 2"); }
Referenced by manageAdmin(), manageEmployee(), manageGuest(), and manageLogin().
startSystem()
void GreenHouse::startSystem ()
Start the system.
Definition at line 37 of file GreenHouse.cpp.
{
   // Mensaje de bienvenida del invernadero
   ms_->initialScreen();
 }
References MonitoringSystem::initialScreen(), and ms_.
Referenced by main().
Member Data Documentation
alarm_
AlarmSensors* GreenHouse::alarm_ private
This attribute is the AlarmSensors object (set of pointers to sensors).
Definition at line 99 of file GreenHouse.h.
Referenced by manageAdmin(), manageEmployee(), manageGuest(), manageLogin(), save(), and ~GreenHouse().
mc_
ManageCameras* GreenHouse::mc_ private
This attribute is the ManageCameras object (set of pointers to cameras).
Definition at line 118 of file GreenHouse.h.
Referenced by manageAdmin(), manageEmployee(), manageGuest(), manageLogin(), save(), and ~GreenHouse().
ms_
MonitoringSystem* GreenHouse::ms_ private
This attribute is the MonitoringSystem object.
Definition at line 105 of file GreenHouse.h.
Referenced by mainSystem(), manageAdmin(), manageCreateUser(), manageDeleteUser(), manageEmployee(), manageGuest(), manageLogin(), manageUpdateUser(), startSystem(), and ~GreenHouse().
us_
UsersServer* GreenHouse::us_ private
This attribute is the UsersServer object (set of pointers to users).
Definition at line 111 of file GreenHouse.h.
Referenced by manageAdmin(), manageCreateUser(), manageDeleteUser(), manageLogin(), manageUpdateUser(), save(), searchUser(), and ~GreenHouse().
The documentation for this class was generated from the following files:
src/GreenHouse.h
src/GreenHouse.cpp