Green House software: HydrometerSensor Class Reference
HydrometerSensor Class Reference
#include <HydrometerSensor.h>
Public Member Functions
HydrometerSensor (int id, bool active)
Construct a new Hydrometer Sensor object.
~HydrometerSensor () override
Destroy the Hydrometer Sensor object.
void collectData () override
Collect data of the Hydrometer Sensor.
bool checkAllgood () const override
Check if the Hydrometer Sensor is working properly.
void printData () const override
Print the data of the Hydrometer Sensor.
std::string stringStatus () const
Collect and print the data of the Hydrometer Sensor.
void collectAndPrint ()
Collect and print the data of the Hydrometer Sensor.
Public Member Functions inherited from Sensor
Sensor ()
Construct a new Sensor object.
Sensor (int id, Types type, bool active)
Construct a new Sensor object.
virtual ~Sensor ()
Destroy the Sensor object.
bool isActive () const
Return if is active or not the sensor.
void turnOff ()
Turn off the sensor.
void turnOn ()
Turn on the sensor.
float getData () const
Get the Data object.
void setData (float data)
Set the Data object.
int getId () const
Get the Id object.
void setId (int newid)
Set the Id object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool operator< (const Sensor &Sensor) const
Operator < overload.
bool operator> (const Sensor &Sensor) const
Operator > overload.
bool operator== (const Sensor &Sensor) const
Operator == overload.
Friends
std::ostream & operator<< (std::ostream &os, const HydrometerSensor &sensor)
Get the Data object.
Additional Inherited Members
Public Types inherited from Sensor
enum Types {
NONE , TEMPERATURE , AIR_QUALITY , HYDROMETER ,
PRESSURE , LIGHT_SENSOR , PH_SENSOR
}
This is the enum Types. It contains the types of the sensors.
Detailed Description
Definition at line 15 of file HydrometerSensor.h.
Constructor & Destructor Documentation
HydrometerSensor()
HydrometerSensor::HydrometerSensor (int id, bool active) explicit
Construct a new Hydrometer Sensor object.
Parameters
id
active
Returns
HydrometerSensor object
Definition at line 9 of file HydrometerSensor.cpp.
     : Sensor(id, Sensor::Types::HYDROMETER, active) {}
~HydrometerSensor()
HydrometerSensor::~HydrometerSensor () override
Destroy the Hydrometer Sensor object.
Definition at line 12 of file HydrometerSensor.cpp.
 {}
Member Function Documentation
checkAllgood()
bool HydrometerSensor::checkAllgood () const override virtual
Check if the Hydrometer Sensor is working properly.
Returns
true if the Hydrometer Sensor is working properly
false if the Hydrometer Sensor is not working properly
Reimplemented from Sensor.
Definition at line 25 of file HydrometerSensor.cpp.
{
   float data = Sensor::getData();
   // Reading between 55-85 is considered good
   if (data >= 52 && data <= 88) {
     return true;
   } else {
     return false;
   }
 }
References Sensor::getData().
Referenced by stringStatus().
collectAndPrint()
void HydrometerSensor::collectAndPrint () virtual
Collect and print the data of the Hydrometer Sensor.
Reimplemented from Sensor.
Definition at line 65 of file HydrometerSensor.cpp.
{
   collectData();
   printData();
 }
References collectData(), and printData().
Referenced by main().
collectData()
void HydrometerSensor::collectData () override virtual
Collect data of the Hydrometer Sensor.
This method collects the data of the Hydrometer Sensor and stores it in the data attribute.
Reimplemented from Sensor.
Definition at line 14 of file HydrometerSensor.cpp.
{
   // Generate random hydrometer reading between 50-90
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_int_distribution<> dis(50, 90);
   int reading = dis(gen);
   // Set data
   Sensor::setData(reading);
 }
References Sensor::setData().
Referenced by collectAndPrint(), and main().
printData()
void HydrometerSensor::printData () const override virtual
Print the data of the Hydrometer Sensor.
Reimplemented from Sensor.
Definition at line 52 of file HydrometerSensor.cpp.
{
   if (Sensor::isActive()) {
     std::cout << "Hydrometer Sensor with "
               << "ID: " << Sensor::getId() << " - Data: " << Sensor::getData()
               << " % "
               << "- Status: " << stringStatus() << endl;
   } else {
     cout << "Hydrometer Sensor ID: " << Sensor::getId() << " - INACTIVE"
          << endl;
   }
 }
References Sensor::getData(), Sensor::getId(), Sensor::isActive(), and stringStatus().
Referenced by collectAndPrint(), and main().
stringStatus()
std::string HydrometerSensor::stringStatus () const
Collect and print the data of the Hydrometer Sensor.
Returns
std::string of the status of the Hydrometer Sensor
Definition at line 40 of file HydrometerSensor.cpp.
{
   if (Sensor::isActive()) {
     if (this->checkAllgood()) {
       return "ACTIVE - GOOD STATUS";
     } else {
       return "ACTIVE - BAD STATUS";
     }
   } else {
     return "INACTIVE";
   }
 }
References checkAllgood(), and Sensor::isActive().
Referenced by main(), and printData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const HydrometerSensor & sensor) friend
Get the Data object.
Returns
double
Definition at line 35 of file HydrometerSensor.cpp.
{
   sensor.printData();
   return os;
 }
The documentation for this class was generated from the following files:
src/HydrometerSensor.h
src/HydrometerSensor.cpp