Green House software: PressureSensor Class Reference
PressureSensor Class Reference
#include <PressureSensor.h>
Public Member Functions
PressureSensor (int id, bool active)
Construct a new Pressure Sensor object.
~PressureSensor () override
Destroy the Pressure Sensor object.
void collectData () override
Collect data of the Pressure Sensor.
bool checkAllgood () const override
Check if the Pressure Sensor is working properly.
void printData () const override
Print the data of the Pressure Sensor.
std::string stringStatus () const
This method returns the status in a string.
void collectAndPrint ()
Collect and print the data of the Pressure Sensor.
Public Member Functions inherited from Sensor
Sensor ()
Construct a new Sensor object.
Sensor (int id, Types type, bool active)
Construct a new Sensor object.
virtual ~Sensor ()
Destroy the Sensor object.
bool isActive () const
Return if is active or not the sensor.
void turnOff ()
Turn off the sensor.
void turnOn ()
Turn on the sensor.
float getData () const
Get the Data object.
void setData (float data)
Set the Data object.
int getId () const
Get the Id object.
void setId (int newid)
Set the Id object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool operator< (const Sensor &Sensor) const
Operator < overload.
bool operator> (const Sensor &Sensor) const
Operator > overload.
bool operator== (const Sensor &Sensor) const
Operator == overload.
Friends
std::ostream & operator<< (std::ostream &os, const PressureSensor &sensor)
Operator << overload.
Additional Inherited Members
Public Types inherited from Sensor
enum Types {
NONE , TEMPERATURE , AIR_QUALITY , HYDROMETER ,
PRESSURE , LIGHT_SENSOR , PH_SENSOR
}
This is the enum Types. It contains the types of the sensors.
Detailed Description
Definition at line 15 of file PressureSensor.h.
Constructor & Destructor Documentation
PressureSensor()
PressureSensor::PressureSensor (int id, bool active) explicit
Construct a new Pressure Sensor object.
Parameters
id
active
Returns
PressureSensor object
Definition at line 9 of file PressureSensor.cpp.
     : Sensor(id, Sensor::Types::PRESSURE, active) {}
~PressureSensor()
PressureSensor::~PressureSensor () override
Destroy the Pressure Sensor object.
Definition at line 12 of file PressureSensor.cpp.
 {}
Member Function Documentation
checkAllgood()
bool PressureSensor::checkAllgood () const override virtual
Check if the Pressure Sensor is working properly.
Returns
true if the Pressure Sensor is working properly
false if the Pressure Sensor is not working properly
Reimplemented from Sensor.
Definition at line 23 of file PressureSensor.cpp.
{
   float data = Sensor::getData();
   if (data >= 0.91f && data <= 1.09f) {
     return true;
   } else {
     return false;
   }
 }
References Sensor::getData().
Referenced by stringStatus().
collectAndPrint()
void PressureSensor::collectAndPrint () virtual
Collect and print the data of the Pressure Sensor.
Reimplemented from Sensor.
Definition at line 60 of file PressureSensor.cpp.
{
   collectData();
   printData();
 }
References collectData(), and printData().
Referenced by main().
collectData()
void PressureSensor::collectData () override virtual
Collect data of the Pressure Sensor.
This method collects the data of the Pressure Sensor and stores it in the data attribute.
Reimplemented from Sensor.
Definition at line 14 of file PressureSensor.cpp.
{
   // Numero random entre 0.90 y 1.10 bares
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_real_distribution<> dis(0.9, 1.1);
   float pressure = dis(gen);
   Sensor::setData(pressure);
 }
References Sensor::setData().
Referenced by collectAndPrint(), and main().
printData()
void PressureSensor::printData () const override virtual
Print the data of the Pressure Sensor.
Reimplemented from Sensor.
Definition at line 37 of file PressureSensor.cpp.
{
   if (Sensor::isActive()) {
     std::cout << "Pressure Sensor with "
               << "ID: " << Sensor::getId() << " - Data: " << Sensor::getData()
               << " bar - Status: " << stringStatus() << endl;
   } else {
     std::cout << "Pressure Sensor ID: " << Sensor::getId()
               << " - Status: " << stringStatus() << endl;
   }
 }
References Sensor::getData(), Sensor::getId(), Sensor::isActive(), and stringStatus().
Referenced by collectAndPrint(), and main().
stringStatus()
std::string PressureSensor::stringStatus () const
This method returns the status in a string.
Returns
std::string of the status of the Pressure Sensor
Definition at line 48 of file PressureSensor.cpp.
{
   if (Sensor::isActive()) {
     if (this->checkAllgood()) {
       return "ACTIVE - GOOD STATUS";
     } else {
       return "ACTIVE - BAD STATUS";
     }
   } else {
     return "INACTIVE";
   }
 }
References checkAllgood(), and Sensor::isActive().
Referenced by main(), and printData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const PressureSensor & sensor) friend
Operator << overload.
Definition at line 32 of file PressureSensor.cpp.
{
   sensor.printData();
   return os;
 }
The documentation for this class was generated from the following files:
src/PressureSensor.h
src/PressureSensor.cpp