Green House software: KeyboardHardware Class Reference
KeyboardHardware Class Reference
#include <KeyboardHardware.h>
Public Member Functions
KeyboardHardware (bool active)
Construct a new Keyboard Hardware object.
~KeyboardHardware () override
Destroy the Keyboard Hardware object.
int askInput () override
Ask for an input to the user.
std::string stringInput ()
Ask for a string input to the user.
void displayOutput () const override
Display the output of the Keyboard Hardware.
Public Member Functions inherited from Hardware
Hardware ()
Construct a new Hardware object.
Hardware (bool active, Types_Hardware type)
Construct a new Hardware object.
virtual ~Hardware ()
Destroy the Hardware object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool isActive () const
If the hardware is active.
void turnOn ()
Turn on the hardware.
void turnOff ()
Turn off the hardware.
std::string stringStatus () const
This method returns if the hardware is active or not in a string.
Private Attributes
int data_
The int data of the Keyboard Hardware.
std::string stringData_
The string data of the Keyboard Hardware.
Additional Inherited Members
Public Types inherited from Hardware
enum Types_Hardware { NONE , SCREEN , KEYBOARD , SWITCH }
Enum of the types of hardware.
Detailed Description
Definition at line 14 of file KeyboardHardware.h.
Constructor & Destructor Documentation
KeyboardHardware()
KeyboardHardware::KeyboardHardware (bool active) explicit
Construct a new Keyboard Hardware object.
Parameters
active
Returns
KeyboardHardware object
Definition at line 9 of file KeyboardHardware.cpp.
     : Hardware(active, Hardware::Types_Hardware::KEYBOARD) {
   data_ = 0;
   stringData_ = "";
 }
References data_, and stringData_.
~KeyboardHardware()
KeyboardHardware::~KeyboardHardware () override
Destroy the Keyboard Hardware object.
Definition at line 15 of file KeyboardHardware.cpp.
 {}
Member Function Documentation
askInput()
int KeyboardHardware::askInput () override virtual
Ask for an input to the user.
Returns
int
Reimplemented from Hardware.
Definition at line 17 of file KeyboardHardware.cpp.
{
   bool exit = false;
   int input;
   while (not exit) {
     std::cout << "- Keyboard waiting for input (integer): ";
     std::cin >> input;
     // Verificar si la entrada es un número
     if (std::cin.fail()) {
       std::cin.clear(); // Restablecer el estado de cin
       std::cin.ignore(std::numeric_limits<std::streamsize>::max(),
                       '\n'); // Limpiar el buffer de entrada
       std::cout << "Invalid input. Please enter an integer that corresponse to "
                    "one of the options"
                 << std::endl;
     } else {
       exit = true;
       data_ = input; // Guardar el valor ingresado en data_
     }
   }
   return data_;
 }
References data_.
Referenced by MonitoringSystem::askIdAlarm(), MonitoringSystem::askIdCamera(), MonitoringSystem::askInputInt(), and main().
displayOutput()
void KeyboardHardware::displayOutput () const override virtual
Display the output of the Keyboard Hardware.
Reimplemented from Hardware.
Definition at line 50 of file KeyboardHardware.cpp.
{
   std::cout << "-Last intput(integer) of the keyboard: " << data_ << std::endl;
   std::cout << "-Last intput(string) of the keyboard: " << stringData_
             << std::endl;
 }
References data_, and stringData_.
Referenced by main().
stringInput()
std::string KeyboardHardware::stringInput ()
Ask for a string input to the user.
Returns
std::string
Definition at line 42 of file KeyboardHardware.cpp.
{
   std::cout << "- Keyboard waiting for input (string): ";
   std::string input;
   std::cin >> input;
   stringData_ = input;
   return stringData_;
 }
References stringData_.
Referenced by MonitoringSystem::askEmail(), MonitoringSystem::askName(), MonitoringSystem::askNIF(), MonitoringSystem::askPassword(), MonitoringSystem::askPrivileges(), MonitoringSystem::askTypeAlarm(), MonitoringSystem::askTypeCamera(), MonitoringSystem::displayErrorScreen(), and main().
Member Data Documentation
data_
int KeyboardHardware::data_ private
The int data of the Keyboard Hardware.
Definition at line 52 of file KeyboardHardware.h.
Referenced by askInput(), displayOutput(), and KeyboardHardware().
stringData_
std::string KeyboardHardware::stringData_ private
The string data of the Keyboard Hardware.
Definition at line 57 of file KeyboardHardware.h.
Referenced by displayOutput(), KeyboardHardware(), and stringInput().
The documentation for this class was generated from the following files:
src/KeyboardHardware.h
src/KeyboardHardware.cpp