Green House software: AlarmSensors Class Reference
AlarmSensors Class Reference
#include <AlarmSensors.h>
Public Member Functions
AlarmSensors ()
Construct a new Alarm Sensors object.
~AlarmSensors ()
Destroy the Alarm Sensors object.
void addSensor (int id, std::string type)
Add a Sensor object.
void deleteSensor (int id)
Delete a Sensor object.
void displayAlarmStatus ()
Display the Alarm Status.
void displayAllSensorsData ()
Display all Sensors Data.
void turnOnOffSystem (int input)
This method turns on or off the system.
void saveSensorsData ()
This method saves the sensors data to a file, one .txt and other one .dat.
void loadSensorsData ()
This method loads the sensors data from a file .dat, but you can change to loads the sensor from a .txt.
void saveSensorsDataTxt ()
This method saves the sensors data to a file .txt.
void loadSensorsDataTxt ()
This method loads the sensors data from a file .txt.
void saveSensorsDataBin ()
This method saves the sensors data to a file .dat.
void loadSensorsDataBin ()
This method loads the sensors data from a file .dat.
Private Member Functions
int checkSensors ()
Check the Sensors.
bool sensorsIniticialized ()
Check if the Sensors are Initialized.
bool sensorExists (int id)
Check if a Sensor exists.
bool checkAllgood ()
Check if the Sensors have good measurements.
void turnOnSystem ()
Turn on the System.
void turnOffSystem ()
Turn off the System.
Private Attributes
std::set< Sensor * > sensors_
This is the set of Sensor pointers.
std::string fileNameTxt = "sensors.txt"
This is the name of the file .txt.
std::string fileNameBin = "sensors.dat"
This is the name of the file .dat.
bool status_ = true
The status of the alarm.
Detailed Description
Definition at line 25 of file AlarmSensors.h.
Constructor & Destructor Documentation
AlarmSensors()
AlarmSensors::AlarmSensors () explicit
Construct a new Alarm Sensors object.
Definition at line 19 of file AlarmSensors.cpp.
{
   // El set de sensores se inicializa con un sensor de cada tipo
   sensors_.insert(new TemperatureSensor(1, true));
   sensors_.insert(new AirQualitySensor(2, true));
   sensors_.insert(new HydrometerSensor(3, true));
   sensors_.insert(new PressureSensor(4, true));
   sensors_.insert(new LightSensor(5, true));
   sensors_.insert(new PhSensor(6, true));
 }
~AlarmSensors()
AlarmSensors::~AlarmSensors ()
Destroy the Alarm Sensors object.
Definition at line 29 of file AlarmSensors.cpp.
{
   // Destructor que elimina todos los sensores
   for (auto sensor : sensors_) {
     delete sensor;
   }
 }
Member Function Documentation
addSensor()
void AlarmSensors::addSensor (int id, std::string type)
Add a Sensor object.
Parameters
id
type
Definition at line 46 of file AlarmSensors.cpp.
{
   // Si el sensor ya existe no se puede añadir
   if (sensorExists(id)) {
     cout << "Sensor already exists" << endl;
     return;
   }
   // Pasar a mayusculas el tipo de sensor
   for (auto &c : type) {
     c = toupper(c);
   }
   // Añadir un sensor al set de sensores
   if (type == "TEMPERATURE") {
     sensors_.insert(new TemperatureSensor(id, true));
   } else if (type == "AIR_QUALITY") {
     sensors_.insert(new AirQualitySensor(id, true));
   } else if (type == "HYDROMETER") {
     sensors_.insert(new HydrometerSensor(id, true));
   } else if (type == "PRESSURE") {
     sensors_.insert(new PressureSensor(id, true));
   } else if (type == "LIGHT") {
     sensors_.insert(new LightSensor(id, true));
   } else if (type == "PH") {
     sensors_.insert(new PhSensor(id, true));
   } else {
     cout << "Sensor type not valid" << endl;
   }
 }
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
checkAllgood()
bool AlarmSensors::checkAllgood () private
Check if the Sensors have good measurements.
Returns
true if the Sensors have good measurements
false if the Sensors do not have good measurements
Definition at line 102 of file AlarmSensors.cpp.
{
   // Si los sensores tienen buenas mediciones
   for (auto sensor : sensors_) {
     if (!sensor->checkAllgood()) {
       return false;
     }
   }
   return true;
 }
checkSensors()
int AlarmSensors::checkSensors () private
Check the Sensors.
Returns
int
Definition at line 112 of file AlarmSensors.cpp.
{
   if (!sensorsIniticialized()) {
     return -1;
   } else {
     if (checkAllgood()) {
       return 1;
     } else {
       return 0;
     }
   }
 }
deleteSensor()
void AlarmSensors::deleteSensor (int id)
Delete a Sensor object.
Parameters
id
Definition at line 74 of file AlarmSensors.cpp.
{
   bool found = false;
   // Eliminar un sensor del set de sensores
   for (auto sensor : sensors_) {
     if (sensor->getId() == id) {
       std::cout << "Sensor with id: " << id << " deleted" << std::endl;
       sensors_.erase(sensor);
       delete sensor;
       found = true;
       break;
     }
   }
   if (!found) {
     std::cout << "Sensor with id: " << id << " not found" << std::endl;
   }
 }
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
displayAlarmStatus()
void AlarmSensors::displayAlarmStatus ()
Display the Alarm Status.
Definition at line 124 of file AlarmSensors.cpp.
{
   if (status_) {
     if (checkSensors() == 1) {
       cout << "---------------------------------------------------" << endl;
       cout << "|                                                 |" << endl;
       cout << "|         All sensors are in good status          |" << endl;
       cout << "|                                                 |" << endl;
       cout << "---------------------------------------------------" << endl;
     } else if (checkSensors() == 0) {
       // Dibujar el logo de alarma, el triangulo con la exclamacion en el medio
       cout << "---------------------------------------------------" << endl;
       cout << "|                                                 |" << endl;
       cout << "|  ¡¡One or more sensors are not in good status¡¡ |" << endl;
       cout << "|                                                 |" << endl;
       cout << "---------------------------------------------------" << endl;
     } else if (checkSensors() == -1) {
       cout << "---------------------------------------------------" << endl;
       cout << "|                                                 |" << endl;
       cout << "|  ¡¡One or more sensors are not initialized¡¡    |" << endl;
       cout << "|    do a collect of data to initialize them      |" << endl;
       cout << "|                                                 |" << endl;
       cout << "---------------------------------------------------" << endl;
     } else {
       cout << "---------------------------------------------------" << endl;
       cout << "|                                                 |" << endl;
       cout << "|            ¡¡Error in the system¡¡              |" << endl;
       cout << "|                                                 |" << endl;
       cout << "---------------------------------------------------" << endl;
     }
   } else {
     cout << "---------------------------------------------------" << endl;
     cout << "|                                                 |" << endl;
     cout << "|                 The system its off              |" << endl;
     cout << "|                                                 |" << endl;
     cout << "---------------------------------------------------" << endl;
   }
 }
Referenced by main(), GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::manageGuest().
displayAllSensorsData()
void AlarmSensors::displayAllSensorsData ()
Display all Sensors Data.
Definition at line 162 of file AlarmSensors.cpp.
{
   // Imprimir los datos de todos los sensores
   for (auto sensor : sensors_) {
     sensor->collectAndPrint();
   }
 }
Referenced by main(), GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::manageGuest().
loadSensorsData()
void AlarmSensors::loadSensorsData ()
This method loads the sensors data from a file .dat, but you can change to loads the sensor from a .txt.
Definition at line 290 of file AlarmSensors.cpp.
{
   // Cargar los datos de los sensores de un archivo binario
   loadSensorsDataBin();
   // Cargar los datos de los sensores de un archivo de texto
   // loadSensorsDataTxt();
 }
Referenced by GreenHouse::manageLogin().
loadSensorsDataBin()
void AlarmSensors::loadSensorsDataBin ()
This method loads the sensors data from a file .dat.
Definition at line 262 of file AlarmSensors.cpp.
{
   // Cargar los datos de los sensores de un archivo binario usando trunc
   ifstream file(fileNameBin, ios::binary);
   int id;
   string type;
   int data;
   while (file.read(reinterpret_cast<char *>(&id), sizeof(int))) {
     // Strings cannot be read directly as binary data due to their dynamic size
     // First, read the length of the string
     size_t typeLength;
     if (file.read(reinterpret_cast<char *>(&typeLength), sizeof(size_t))) {
       // Resize the string to the read length
       type.resize(typeLength);
       // Now, read the string data
       file.read(&type[0], typeLength);
     }
     file.read(reinterpret_cast<char *>(&data), sizeof(int));
     addSensor(id, type);
     for (auto sensor : sensors_) {
       if (sensor->getId() == id) {
         sensor->setData(data);
       }
     }
     std::cout << "Sensor with id: " << id << " loaded (binary)" << std::endl;
   }
   file.close();
 }
loadSensorsDataTxt()
void AlarmSensors::loadSensorsDataTxt ()
This method loads the sensors data from a file .txt.
Definition at line 243 of file AlarmSensors.cpp.
{
   // Cargar los datos de los sensores de un archivo de texto
   ifstream file;
   file.open(fileNameTxt);
   int id;
   string type;
   int data;
   while (file >> id >> type >> data) {
     addSensor(id, type);
     for (auto sensor : sensors_) {
       if (sensor->getId() == id) {
         sensor->setData(data);
       }
     }
     std::cout << "Sensor with id: " << id << " loaded (txt)" << std::endl;
   }
   file.close();
 }
saveSensorsData()
void AlarmSensors::saveSensorsData ()
This method saves the sensors data to a file, one .txt and other one .dat.
Definition at line 236 of file AlarmSensors.cpp.
{
   // Guardar los datos de los sensores en un archivo binario
   saveSensorsDataBin();
   // GUardar los datos de los sensores en un archivo de texto
   saveSensorsDataTxt();
 }
Referenced by GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::save().
saveSensorsDataBin()
void AlarmSensors::saveSensorsDataBin ()
This method saves the sensors data to a file .dat.
Definition at line 217 of file AlarmSensors.cpp.
{
   ofstream file(fileNameBin, ios::binary | ios::trunc);
   for (auto sensor : sensors_) {
     int id = sensor->getId();
     file.write(reinterpret_cast<char *>(&id), sizeof(int));
     size_t typeLength = sensor->getType().length();
     file.write(reinterpret_cast<char *>(&typeLength), sizeof(size_t));
     file.write(sensor->getType().c_str(), typeLength);
     int data = sensor->getData();
     file.write(reinterpret_cast<char *>(&data), sizeof(int));
     std::cout << "Sensor with id: " << sensor->getId() << " saved (binary)"
               << std::endl;
   }
   file.close();
 }
saveSensorsDataTxt()
void AlarmSensors::saveSensorsDataTxt ()
This method saves the sensors data to a file .txt.
Definition at line 204 of file AlarmSensors.cpp.
{
   // Guardar los datos de los sensores en un archivo de texto
   ofstream file;
   file.open(fileNameTxt);
   for (auto sensor : sensors_) {
     file << sensor->getId() << " " << sensor->getType() << " "
          << sensor->getData() << endl;
     std::cout << "Sensor with id: " << sensor->getId() << " saved (txt)"
               << std::endl;
   }
   file.close();
 }
sensorExists()
bool AlarmSensors::sensorExists (int id) private
Check if a Sensor exists.
Parameters
id
Returns
true if the Sensor exists
false if the Sensor does not exist
Definition at line 36 of file AlarmSensors.cpp.
{
   // Ver si existe un sensor
   for (auto sensor : sensors_) {
     if (sensor->getId() == id) {
       return true;
     }
   }
   return false;
 }
sensorsIniticialized()
bool AlarmSensors::sensorsIniticialized () private
Check if the Sensors are Initialized.
Returns
true if the Sensors are Initialized
false if the Sensors are not Initialized
Definition at line 91 of file AlarmSensors.cpp.
{
   // Los sensores estan iniciados si todos los sensores no tienen el valor por
   // defecto de -1
   for (auto sensor : sensors_) {
     if (sensor->getData() == -1) {
       return false;
     }
   }
   return true;
 }
turnOffSystem()
void AlarmSensors::turnOffSystem () private
Turn off the System.
Definition at line 176 of file AlarmSensors.cpp.
{
   // Apagar todos los sensores del set
   for (auto sensor : sensors_) {
     sensor->turnOff();
   }
 }
turnOnOffSystem()
void AlarmSensors::turnOnOffSystem (int input)
This method turns on or off the system.
Parameters
input
Definition at line 183 of file AlarmSensors.cpp.
{
   // Si el input es igual a true entonces encender todos los sensores
   if (input == 1) {
     turnOnSystem();
     cout << "---------------------------------------------------" << endl;
     cout << "|                                                 |" << endl;
     cout << "|                 System turned on                |" << endl;
     cout << "|                                                 |" << endl;
     cout << "---------------------------------------------------" << endl;
     status_ = true;
   } else if (input == 2) {
     turnOffSystem();
     cout << "---------------------------------------------------" << endl;
     cout << "|                                                 |" << endl;
     cout << "|                 System turned off               |" << endl;
     cout << "|                                                 |" << endl;
     cout << "---------------------------------------------------" << endl;
     status_ = false;
   }
 }
Referenced by main(), GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
turnOnSystem()
void AlarmSensors::turnOnSystem () private
Turn on the System.
Definition at line 169 of file AlarmSensors.cpp.
{
   // Encender todos los sensores del set
   for (auto sensor : sensors_) {
     sensor->turnOn();
   }
 }
Member Data Documentation
fileNameBin
std::string AlarmSensors::fileNameBin = "sensors.dat" private
This is the name of the file .dat.
Definition at line 131 of file AlarmSensors.h.
fileNameTxt
std::string AlarmSensors::fileNameTxt = "sensors.txt" private
This is the name of the file .txt.
Definition at line 126 of file AlarmSensors.h.
sensors_
std::set<Sensor *> AlarmSensors::sensors_ private
This is the set of Sensor pointers.
Definition at line 119 of file AlarmSensors.h.
status_
bool AlarmSensors::status_ = true private
The status of the alarm.
Definition at line 183 of file AlarmSensors.h.
The documentation for this class was generated from the following files:
src/AlarmSensors.h
src/AlarmSensors.cpp