Green House software: Camera Class Reference
Camera Class Reference
#include <Camera.h>
Public Member Functions
Camera (int id, std::string type, bool active)
Construct a new Camera object.
virtual ~Camera ()
Destroy the Camera object.
void setId (int newid)
Set the id of the camera.
int getId () const
Get the id of the camera.
void setType (std::string newtype)
Set the type of the camera.
std::string getType () const
Get the type of the camera.
virtual void printCamera ()
Print the camera information.
virtual void collectData ()
Collect data from the camera.
void turnOn ()
Turn on the camera.
void turnOff ()
Turn off the camera.
const bool isActive ()
Check if the camera is active.
Private Attributes
int id_
This attribute represents the id of the camera.
std::string type_
This attribute represents the type of the camera.
bool active_
This attribute represents if the camera is active.
Detailed Description
Definition at line 16 of file Camera.h.
Constructor & Destructor Documentation
Camera()
Camera::Camera (int id, std::string type, bool active) explicit
Construct a new Camera object.
Parameters
id
type
active
Returns
Camera object
Definition at line 5 of file Camera.cpp.
{
   id_ = id;
   type_ = type;
   active_ = active;
 }
~Camera()
Camera::~Camera () virtual
Destroy the Camera object.
Definition at line 11 of file Camera.cpp.
 {}
Member Function Documentation
collectData()
void Camera::collectData () virtual
Collect data from the camera.
Reimplemented in TemperatureCamera, and RGBCamera.
Definition at line 21 of file Camera.cpp.
{
   cout << "Collecting data from camera " << id_ << endl;
 }
getId()
int Camera::getId () const
Get the id of the camera.
Returns
int
Definition at line 15 of file Camera.cpp.
 { return id_; }
Referenced by RGBCamera::printCamera(), TemperatureCamera::printCamera(), RGBCamera::RGBCamera(), ManageCameras::saveCameras(), and TemperatureCamera::TemperatureCamera().
getType()
std::string Camera::getType () const
Get the type of the camera.
Returns
std::string
Definition at line 19 of file Camera.cpp.
 { return type_; }
isActive()
const bool Camera::isActive ()
Check if the camera is active.
Returns
const bool
Definition at line 34 of file Camera.cpp.
 { return active_; }
Referenced by RGBCamera::printCamera(), and TemperatureCamera::printCamera().
printCamera()
void Camera::printCamera () virtual
Print the camera information.
Reimplemented in TemperatureCamera, and RGBCamera.
Definition at line 25 of file Camera.cpp.
{
   cout << "Camera id: " << id_ << " type: " << type_ << " active: " << active_
        << endl;
 }
setId()
void Camera::setId (int newid)
Set the id of the camera.
Parameters
newid
Definition at line 13 of file Camera.cpp.
 { id_ = newid; }
setType()
void Camera::setType (std::string newtype)
Set the type of the camera.
Parameters
newtype
Definition at line 17 of file Camera.cpp.
 { type_ = newtype; }
turnOff()
void Camera::turnOff ()
Turn off the camera.
Definition at line 32 of file Camera.cpp.
 { active_ = false; }
Referenced by main().
turnOn()
void Camera::turnOn ()
Turn on the camera.
Definition at line 30 of file Camera.cpp.
 { active_ = true; }
Member Data Documentation
active_
bool Camera::active_ private
This attribute represents if the camera is active.
Definition at line 98 of file Camera.h.
id_
int Camera::id_ private
This attribute represents the id of the camera.
Definition at line 88 of file Camera.h.
type_
std::string Camera::type_ private
This attribute represents the type of the camera.
Definition at line 93 of file Camera.h.
The documentation for this class was generated from the following files:
src/Camera.h
src/Camera.cpp