Green House software: Hardware Class Reference
Hardware Class Reference
#include <Hardware.h>
Public Types
enum Types_Hardware { NONE , SCREEN , KEYBOARD , SWITCH }
Enum of the types of hardware.
Public Member Functions
Hardware ()
Construct a new Hardware object.
Hardware (bool active, Types_Hardware type)
Construct a new Hardware object.
virtual ~Hardware ()
Destroy the Hardware object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool isActive () const
If the hardware is active.
void turnOn ()
Turn on the hardware.
void turnOff ()
Turn off the hardware.
std::string stringStatus () const
This method returns if the hardware is active or not in a string.
virtual int askInput ()
This method asks the user for an input.
virtual void displayOutput () const
This method displays the output of the hardware.
Private Member Functions
std::string typeToString (Types_Hardware type) const
This method converts the type of hardware to a string.
Types_Hardware stringToType (std::string type) const
This method converts the string to a type of hardware.
Private Attributes
bool active_
This atrribute is the status of the hardware.
Types_Hardware type_
This attribute is the type of the hardware.
Detailed Description
Definition at line 15 of file Hardware.h.
Member Enumeration Documentation
Types_Hardware
enum Hardware::Types_Hardware
Enum of the types of hardware.
Enumerator
NONE
SCREEN
KEYBOARD
SWITCH
Definition at line 21 of file Hardware.h.
 { NONE, SCREEN, KEYBOARD, SWITCH };
Constructor & Destructor Documentation
Hardware() [1/2]
Hardware::Hardware ()
Construct a new Hardware object.
Definition at line 7 of file Hardware.cpp.
 : active_(false), type_(Types_Hardware::NONE) {}
Hardware() [2/2]
Hardware::Hardware (bool active, Types_Hardware type) explicit
Construct a new Hardware object.
Parameters
active
type
Definition at line 8 of file Hardware.cpp.
     : active_(active), type_(type) {}
~Hardware()
Hardware::~Hardware () virtual
Destroy the Hardware object.
Definition at line 10 of file Hardware.cpp.
 {}
Member Function Documentation
askInput()
int Hardware::askInput () virtual
This method asks the user for an input.
Returns
int
Reimplemented in SwitchHardware, ScreenHardware, and KeyboardHardware.
Definition at line 34 of file Hardware.cpp.
{
   return 0;
   // esta funcion sera definida en clases hijas
   // pero la idea es qeu muestre un mensaje estilo Pantalla: (Aqui viene el
   // input del usuario)
 }
displayOutput()
void Hardware::displayOutput () const virtual
This method displays the output of the hardware.
Reimplemented in SwitchHardware, ScreenHardware, and KeyboardHardware.
Definition at line 41 of file Hardware.cpp.
{
   // Esta funcion sera definida en las clases hijas
   // Por ahora mostramos un mensaje generico
   cout << "Hardware cannot display output for this type" << endl;
 }
getType()
std::string Hardware::getType () const
Get the Type object.
Returns
std::string
Definition at line 12 of file Hardware.cpp.
 { return typeToString(type_); }
References type_, and typeToString().
Referenced by main(), and stringStatus().
isActive()
bool Hardware::isActive () const
If the hardware is active.
Returns
true if the hardware is active
false if the hardware is not active
Definition at line 16 of file Hardware.cpp.
 { return active_; }
References active_.
Referenced by main(), and stringStatus().
setType()
void Hardware::setType (std::string newtype)
Set the Type object.
Parameters
newtype
Definition at line 14 of file Hardware.cpp.
 { type_ = stringToType(newtype); }
References stringToType(), and type_.
Referenced by main().
stringStatus()
std::string Hardware::stringStatus () const
This method returns if the hardware is active or not in a string.
Returns
std::string
Definition at line 22 of file Hardware.cpp.
{
   std::string status;
   if (isActive()) {
     status = "ON";
   } else {
     status = "OFF";
   }
   status += " - ";
   status += getType();
   return status;
 }
References getType(), and isActive().
Referenced by SwitchHardware::displayOutput(), and main().
stringToType()
Hardware::Types_Hardware Hardware::stringToType (std::string type) const private
This method converts the string to a type of hardware.
Parameters
type
Returns
Types_Hardware
Definition at line 60 of file Hardware.cpp.
{
   if (type == "SCREEN") {
     return Hardware::Types_Hardware::SCREEN;
   } else if (type == "KEYBOARD") {
     return Hardware::Types_Hardware::KEYBOARD;
   } else if (type == "SWITCH") {
     return Hardware::Types_Hardware::SWITCH;
   } else {
     return Hardware::Types_Hardware::NONE;
   }
 }
Referenced by setType().
turnOff()
void Hardware::turnOff ()
Turn off the hardware.
Definition at line 20 of file Hardware.cpp.
 { active_ = false; }
References active_.
Referenced by main(), and SwitchHardware::translateInput().
turnOn()
void Hardware::turnOn ()
Turn on the hardware.
Definition at line 18 of file Hardware.cpp.
 { active_ = true; }
References active_.
Referenced by main(), and SwitchHardware::translateInput().
typeToString()
std::string Hardware::typeToString (Types_Hardware type) const private
This method converts the type of hardware to a string.
Parameters
type
Returns
std::string
Definition at line 47 of file Hardware.cpp.
{
   switch (type) {
   case Types_Hardware::SCREEN:
     return "SCREEN";
   case Types_Hardware::KEYBOARD:
     return "KEYBOARD";
   case Types_Hardware::SWITCH:
     return "SWITCH";
   default:
     return "None";
   }
 }
Referenced by getType().
Member Data Documentation
active_
bool Hardware::active_ private
This atrribute is the status of the hardware.
Definition at line 95 of file Hardware.h.
Referenced by isActive(), turnOff(), and turnOn().
type_
Types_Hardware Hardware::type_ private
This attribute is the type of the hardware.
Definition at line 100 of file Hardware.h.
Referenced by getType(), and setType().
The documentation for this class was generated from the following files:
src/Hardware.h
src/Hardware.cpp