Green House software: LightSensor Class Reference
LightSensor Class Reference
#include <LightSensor.h>
Public Member Functions
LightSensor (int id, bool active)
Construct a new Light Sensor object.
~LightSensor () override
Destroy the Light Sensor object.
void collectData () override
Collect data of the Light Sensor.
bool checkAllgood () const override
Check if the Light Sensor is working properly.
void printData () const override
Print the data of the Light Sensor.
std::string stringStatus () const
Collect and print the data of the Light Sensor.
void collectAndPrint ()
Collect and print the data of the Light Sensor.
Public Member Functions inherited from Sensor
Sensor ()
Construct a new Sensor object.
Sensor (int id, Types type, bool active)
Construct a new Sensor object.
virtual ~Sensor ()
Destroy the Sensor object.
bool isActive () const
Return if is active or not the sensor.
void turnOff ()
Turn off the sensor.
void turnOn ()
Turn on the sensor.
float getData () const
Get the Data object.
void setData (float data)
Set the Data object.
int getId () const
Get the Id object.
void setId (int newid)
Set the Id object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool operator< (const Sensor &Sensor) const
Operator < overload.
bool operator> (const Sensor &Sensor) const
Operator > overload.
bool operator== (const Sensor &Sensor) const
Operator == overload.
Friends
std::ostream & operator<< (std::ostream &os, const LightSensor &sensor)
Get the Light object.
Additional Inherited Members
Public Types inherited from Sensor
enum Types {
NONE , TEMPERATURE , AIR_QUALITY , HYDROMETER ,
PRESSURE , LIGHT_SENSOR , PH_SENSOR
}
This is the enum Types. It contains the types of the sensors.
Detailed Description
Definition at line 15 of file LightSensor.h.
Constructor & Destructor Documentation
LightSensor()
LightSensor::LightSensor (int id, bool active) explicit
Construct a new Light Sensor object.
Parameters
id
active
Returns
LightSensor object
Definition at line 8 of file LightSensor.cpp.
     : Sensor(id, Sensor::Types::LIGHT_SENSOR, active) {}
~LightSensor()
LightSensor::~LightSensor () override
Destroy the Light Sensor object.
Definition at line 11 of file LightSensor.cpp.
 {}
Member Function Documentation
checkAllgood()
bool LightSensor::checkAllgood () const override virtual
Check if the Light Sensor is working properly.
Returns
true if the Light Sensor is working properly
false if the Light Sensor is not working properly
Reimplemented from Sensor.
Definition at line 23 of file LightSensor.cpp.
{
   float data = Sensor::getData();
   if (data >= 300 && data <= 3900) {
     return true;
   } else {
     return false;
   }
 }
References Sensor::getData().
Referenced by stringStatus().
collectAndPrint()
void LightSensor::collectAndPrint () virtual
Collect and print the data of the Light Sensor.
Reimplemented from Sensor.
Definition at line 61 of file LightSensor.cpp.
{
   collectData();
   printData();
 }
References collectData(), and printData().
Referenced by main().
collectData()
void LightSensor::collectData () override virtual
Collect data of the Light Sensor.
This method collects the data of the Light Sensor and stores it in the data attribute.
Reimplemented from Sensor.
Definition at line 13 of file LightSensor.cpp.
{
   // Medido en lux entre 200-4000 lux
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_int_distribution<> dis(200, 4000);
   int reading = dis(gen);
   Sensor::setData(reading);
 }
References Sensor::setData().
Referenced by collectAndPrint(), and main().
printData()
void LightSensor::printData () const override virtual
Print the data of the Light Sensor.
Reimplemented from Sensor.
Definition at line 38 of file LightSensor.cpp.
{
   if (Sensor::isActive()) {
     std::cout << "Light Sensor with "
               << "ID: " << Sensor::getId() << " - Data: " << Sensor::getData()
               << " lux - Status: " << stringStatus() << endl;
   } else {
     std::cout << "Light Sensor ID: " << Sensor::getId()
               << " - Status: " << stringStatus() << endl;
   }
 }
References Sensor::getData(), Sensor::getId(), Sensor::isActive(), and stringStatus().
Referenced by collectAndPrint(), and main().
stringStatus()
std::string LightSensor::stringStatus () const
Collect and print the data of the Light Sensor.
Definition at line 49 of file LightSensor.cpp.
{
   if (Sensor::isActive()) {
     if (this->checkAllgood()) {
       return "ACTIVE - GOOD STATUS";
     } else {
       return "ACTIVE - BAD STATUS";
     }
   } else {
     return "INACTIVE";
   }
 }
References checkAllgood(), and Sensor::isActive().
Referenced by main(), and printData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const LightSensor & sensor) friend
Get the Light object.
Returns
int
Definition at line 33 of file LightSensor.cpp.
{
   sensor.printData();
   return os;
 }
The documentation for this class was generated from the following files:
src/LightSensor.h
src/LightSensor.cpp