Green House software: UsersDatabase Class Reference
UsersDatabase Class Reference
#include <UsersDatabase.h>
Public Member Functions
UsersDatabase ()
Construct a new Users Database object Creates a new UsersDatabase object that contains the pointers to users.
~UsersDatabase ()
Destroy the Users Database object.
void addUser (const User *user)
Add a user to the set of users.
std::set< const User *, UserPtrComparator > getUsers () const
Get the Users object.
void setUsers (const std::set< const User *, UserPtrComparator > &users)
Set the Users object.
User * findUser (const User &user) const
Find a user in the set of users.
User * findUserByName (const std::string name) const
Find a user in the set of users with the name.
User * findUserByNif (const std::string nif) const
Fiend a user in the set of users with the NIF.
User * findUserByPassword (const std::string password) const
Find a user in the set of users with the password.
User * findUserByEmail (const std::string email) const
Find a user in the set of users with the email.
void deleteUser (const User &user)
Delete a user from the set of users.
void deleteUserByName (const std::string name)
Delete a user from the set of users with the name.
void deleteUserByNif (const std::string nif)
Delete a user from the set of users with the NIF.
void deleteUserByEmail (const std::string email)
Delete a user from the set of users with the email.
bool isValidPrivileges (const std::string privileges) const
This method checks if the privileges are valid.
void printUsers () const
Print all the users.
Private Member Functions
void printDeletedUser (const User *user) const
This method prints the user that has been deleted.
std::set< const User *, UserNameComparator > getUsersSortedByName () const
Private Attributes
std::set< const User *, UserPtrComparator > users_
This is the set of pointers to users.
Detailed Description
Definition at line 40 of file UsersDatabase.h.
Constructor & Destructor Documentation
UsersDatabase()
UsersDatabase::UsersDatabase ()
Construct a new Users Database object Creates a new UsersDatabase object that contains the pointers to users.
Returns
UsersDatabase object
Definition at line 13 of file UsersDatabase.cpp.
 {}
~UsersDatabase()
UsersDatabase::~UsersDatabase ()
Destroy the Users Database object.
Definition at line 15 of file UsersDatabase.cpp.
{
   // Liberar la memoria de los usuarios
   for (auto user : users_) {
     delete user;
   }
 }
References users_.
Member Function Documentation
addUser()
void UsersDatabase::addUser (const User * user)
Add a user to the set of users.
Parameters
user
Definition at line 28 of file UsersDatabase.cpp.
{
   // Intento añadir un usuario al set de usuarios si no existe, si existe no lo
   // añado y llamo a su destructor, tambien tiene que tener unos privilegios
   // validos
   if (findUserByNif(user->getNif()) == nullptr &&
       (isValidPrivileges(user->getPrivileges()))) {
     users_.insert(user);
   } else {
     if (!isValidPrivileges(user->getPrivileges())) {
       std::cout << "Privileges are not valid (ADMIN/EMPLOYEE/GUEST)"
                 << std::endl;
     } else {
       std::cout << "User already exists" << std::endl;
     }
     delete user;
   }
 }
References findUserByNif(), User::getNif(), User::getPrivileges(), isValidPrivileges(), and users_.
Referenced by main().
deleteUser()
void UsersDatabase::deleteUser (const User & user)
Delete a user from the set of users.
Parameters
user
Definition at line 148 of file UsersDatabase.cpp.
{
   for (std::set<const User *>::iterator it = users_.begin(); it != users_.end();
        it++) {
     // Si encuentro el usuario lo borro y también el puntero con el destructor
     // de la clase User
     if (*(*it) == user) {
       printDeletedUser(*it);
       delete *it; // Llama al destructor de User y libera la memoria
       users_.erase(it);
       return;
     }
   }
   std::cout << "User not found" << std::endl;
   std::cout << std::endl;
 }
References printDeletedUser(), and users_.
Referenced by main().
deleteUserByEmail()
void UsersDatabase::deleteUserByEmail (const std::string email)
Delete a user from the set of users with the email.
Parameters
email
Definition at line 195 of file UsersDatabase.cpp.
{
   for (std::set<const User *>::iterator it = users_.begin(); it != users_.end();
        it++) {
     if ((*it)->getEmail() == email) {
       printDeletedUser(*it);
       delete *it; // Llama al destructor de User y libera la memoria
       users_.erase(it);
       return;
     }
   }
   std::cout << "User not found" << std::endl;
   std::cout << std::endl;
 }
References printDeletedUser(), and users_.
Referenced by main().
deleteUserByName()
void UsersDatabase::deleteUserByName (const std::string name)
Delete a user from the set of users with the name.
Parameters
name
Definition at line 165 of file UsersDatabase.cpp.
{
   for (std::set<const User *>::iterator it = users_.begin(); it != users_.end();
        it++) {
     // Si esta el usuario lo borro y tambien borro el puntero
     if ((*it)->getName() == name) {
       printDeletedUser(*it);
       delete *it; // Llama al destructor de User y libera la memoria
       users_.erase(it);
       return;
     }
   }
   std::cout << "User not found" << std::endl;
   std::cout << std::endl;
 }
References printDeletedUser(), and users_.
Referenced by main().
deleteUserByNif()
void UsersDatabase::deleteUserByNif (const std::string nif)
Delete a user from the set of users with the NIF.
Parameters
nif
Definition at line 180 of file UsersDatabase.cpp.
{
   for (std::set<const User *>::iterator it = users_.begin(); it != users_.end();
        it++) {
     if ((*it)->getNif() == nif) {
       printDeletedUser(*it);
       delete *it; // Llama al destructor de User y libera la memoria
       users_.erase(it);
       return;
     }
   }
   std::cout << "User not found" << std::endl;
   std::cout << std::endl;
 }
References printDeletedUser(), and users_.
Referenced by main().
findUser()
User * UsersDatabase::findUser (const User & user) const
Find a user in the set of users.
Parameters
user
Returns
User*
Definition at line 78 of file UsersDatabase.cpp.
{
   // Si el usuario existe devuelvo el usuario, si no existe devuelvo un usuario
   // con todos los atributos vacios
   for (std::set<const User *, UserPtrComparator>::const_iterator it =
            users_.begin();
        it != users_.end(); it++) {
     if (*(*it) == user) {
       return const_cast<User *>(*it);
     }
   }
   return nullptr;
 }
References users_.
Referenced by main().
findUserByEmail()
User * UsersDatabase::findUserByEmail (const std::string email) const
Find a user in the set of users with the email.
Parameters
email
Returns
User*
Definition at line 134 of file UsersDatabase.cpp.
{
   // Si el usuario existe devuelvo el usuario, si no existe devuelvo un usuario
   // con todos los atributos vacios
   for (std::set<const User *, UserPtrComparator>::const_iterator it =
            users_.begin();
        it != users_.end(); it++) {
     if ((*it)->getEmail() == email) {
       return const_cast<User *>(*it);
     }
   }
   return nullptr;
 }
References users_.
Referenced by main().
findUserByName()
User * UsersDatabase::findUserByName (const std::string name) const
Find a user in the set of users with the name.
Parameters
name
Returns
User*
Definition at line 92 of file UsersDatabase.cpp.
{
   // Si el usuario existe devuelvo el usuario, si no existe devuelvo un usuario
   // con todos los atributos vacios
   for (std::set<const User *, UserPtrComparator>::const_iterator it =
            users_.begin();
        it != users_.end(); it++) {
     if ((*it)->getName() == name) {
       return const_cast<User *>(*it);
     }
   }
   return nullptr;
 }
References users_.
Referenced by main().
findUserByNif()
User * UsersDatabase::findUserByNif (const std::string nif) const
Fiend a user in the set of users with the NIF.
Parameters
nif
Returns
User*
Definition at line 106 of file UsersDatabase.cpp.
{
   // Si el usuario existe devuelvo el usuario, si no existe devuelvo un usuario
   // con todos los atributos vacios
   for (std::set<const User *, UserPtrComparator>::const_iterator it =
            users_.begin();
        it != users_.end(); it++) {
     if ((*it)->getNif() == nif) {
       return const_cast<User *>(*it);
     }
   }
   return nullptr;
 }
References users_.
Referenced by addUser(), and main().
findUserByPassword()
User * UsersDatabase::findUserByPassword (const std::string password) const
Find a user in the set of users with the password.
Parameters
password
Returns
User*
Definition at line 120 of file UsersDatabase.cpp.
{
   // Si el usuario existe devuelvo el usuario, si no existe devuelvo un usuario
   // con todos los atributos vacios
   for (std::set<const User *, UserPtrComparator>::const_iterator it =
            users_.begin();
        it != users_.end(); it++) {
     if ((*it)->getPassword() == password) {
       return const_cast<User *>(*it);
     }
   }
   return nullptr;
 }
References users_.
getUsers()
std::set< const User *, UserPtrComparator > UsersDatabase::getUsers () const
Get the Users object.
Returns
std::set<const User *, UserPtrComparator>
Definition at line 47 of file UsersDatabase.cpp.
{
   return users_;
 }
References users_.
Referenced by main().
getUsersSortedByName()
std::set< const User *, UserNameComparator > UsersDatabase::getUsersSortedByName () const private
Definition at line 233 of file UsersDatabase.cpp.
{
   std::set<const User *, UserNameComparator> sortedUsers(users_.begin(), users_.end());
   return sortedUsers;
 }
References users_.
isValidPrivileges()
bool UsersDatabase::isValidPrivileges (const std::string privileges) const
This method checks if the privileges are valid.
Parameters
privileges
Returns
true
false
Definition at line 22 of file UsersDatabase.cpp.
{
   // Compruebo si los privilegios son validos
   return privileges == "ADMIN" || privileges == "EMPLOYEE" ||
          privileges == "GUEST";
 }
Referenced by addUser().
printDeletedUser()
void UsersDatabase::printDeletedUser (const User * user) const private
This method prints the user that has been deleted.
This method prints the user that has been deleted, is private method becouse to print a delete user first you have to delete one. So when you delete a user, this method print the user that has been deleted.
Parameters
user
Definition at line 227 of file UsersDatabase.cpp.
{
   std::cout << "User deleted: " << (*user).getName() << "-" << (*user).getNif()
             << std::endl;
   std::cout << std::endl;
 }
Referenced by deleteUser(), deleteUserByEmail(), deleteUserByName(), and deleteUserByNif().
printUsers()
void UsersDatabase::printUsers () const
Print all the users.
Definition at line 210 of file UsersDatabase.cpp.
{
   std::cout << "*** LIST OF USERS ***" << std::endl;
   // Imprimir todos los usuarios
   /*
   for (auto it = users_.rbegin(); it != users_.rend(); ++it) {
     (*it)->printUser();
     std::cout << std::endl;
   }
   */
   for (const auto &user : users_) {
     (*user).printUser();
     std::cout << std::endl;
   }
   std::cout << "*** END OF LIST ***" << std::endl;
 }
References users_.
Referenced by main().
setUsers()
void UsersDatabase::setUsers (const std::set< const User *, UserPtrComparator > & users)
Set the Users object.
Parameters
users
Definition at line 51 of file UsersDatabase.cpp.
{
   // El set users debe de convertir los punteros de usuarios a Objetos de
   // usuarios y luego añadirlos al set de usuarios Bucle para convertirlos en
   // objetos usuario
   for (auto user : users) {
     try {
       if (user->getPrivileges() == "ADMIN") {
         users_.insert(new UserAdmin(*static_cast<const UserAdmin *>(user)));
       } else if (user->getPrivileges() == "EMPLOYEE") {
         users_.insert(
             new UserEmployee(*static_cast<const UserEmployee *>(user)));
       } else if (user->getPrivileges() == "GUEST") {
         users_.insert(new UserGuest(*static_cast<const UserGuest *>(user)));
       } else {
         std::cerr << "Unknown user privilege: " << user->getPrivileges()
                   << '\n';
       }
     } catch (std::bad_alloc &ba) {
       std::cerr << "bad_alloc caught: " << ba.what() << '\n';
       // Borrar el usuario que no se ha podido añadir
       delete user;
       throw;
     }
   }
 }
References users_.
Referenced by main().
Member Data Documentation
users_
std::set<const User *, UserPtrComparator> UsersDatabase::users_ private
This is the set of pointers to users.
This is the atributte that contains the pointers to users.
Definition at line 175 of file UsersDatabase.h.
Referenced by addUser(), deleteUser(), deleteUserByEmail(), deleteUserByName(), deleteUserByNif(), findUser(), findUserByEmail(), findUserByName(), findUserByNif(), findUserByPassword(), getUsers(), getUsersSortedByName(), printUsers(), setUsers(), and ~UsersDatabase().
The documentation for this class was generated from the following files:
src/UsersDatabase.h
src/UsersDatabase.cpp