Green House software: RGBCamera Class Reference
RGBCamera Class Reference
#include <RGBCamera.h>
Public Member Functions
RGBCamera (int id)
Construct a new RGB Camera object.
~RGBCamera ()
Destroy the RGB Camera object.
void setRGB (int red, int green, int blue)
This method sets the RGB values of the camera.
void setRed (int red)
This method sets the red value of the camera.
void setGreen (int green)
This method sets the green value of the camera.
void setBlue (int blue)
This method sets the blue value of the camera.
int getRed ()
This method returns the red value of the camera.
int getGreen ()
This method returns the green value of the camera.
int getBlue ()
This method returns the blue value of the camera.
void collectData () override
This method collects the data of the camera.
void printCamera () override
This method prints the camera information.
int randomComponent ()
This method returns a random number between 0 and 255.
Public Member Functions inherited from Camera
Camera (int id, std::string type, bool active)
Construct a new Camera object.
virtual ~Camera ()
Destroy the Camera object.
void setId (int newid)
Set the id of the camera.
int getId () const
Get the id of the camera.
void setType (std::string newtype)
Set the type of the camera.
std::string getType () const
Get the type of the camera.
void turnOn ()
Turn on the camera.
void turnOff ()
Turn off the camera.
const bool isActive ()
Check if the camera is active.
Private Attributes
int red_
This attribute represents the red value of the camera.
int green_
This attribute represents the green value of the camera.
int blue_
This attribute represents the blue value of the camera.
Detailed Description
Definition at line 19 of file RGBCamera.h.
Constructor & Destructor Documentation
RGBCamera()
RGBCamera::RGBCamera (int id) explicit
Construct a new RGB Camera object.
Parameters
id
Returns
RGBCamera object
Definition at line 6 of file RGBCamera.cpp.
                            : Camera(id, "RGB", true) {
   red_ = -1;
   green_ = -1;
   blue_ = -1;
   std::cout << "RGB Camera id (" << getId() << ") created" << std::endl;
 }
References blue_, Camera::getId(), green_, and red_.
~RGBCamera()
RGBCamera::~RGBCamera ()
Destroy the RGB Camera object.
Definition at line 13 of file RGBCamera.cpp.
 {}
Member Function Documentation
collectData()
void RGBCamera::collectData () override virtual
This method collects the data of the camera.
Reimplemented from Camera.
Definition at line 41 of file RGBCamera.cpp.
{
   setRGB(randomComponent(), randomComponent(), randomComponent());
 }
References randomComponent(), and setRGB().
Referenced by main().
getBlue()
int RGBCamera::getBlue ()
This method returns the blue value of the camera.
Returns
int
Definition at line 31 of file RGBCamera.cpp.
 { return blue_; }
References blue_.
Referenced by ManageCameras::saveCameras().
getGreen()
int RGBCamera::getGreen ()
This method returns the green value of the camera.
Returns
int
Definition at line 29 of file RGBCamera.cpp.
 { return green_; }
References green_.
Referenced by ManageCameras::saveCameras().
getRed()
int RGBCamera::getRed ()
This method returns the red value of the camera.
Returns
int
Definition at line 27 of file RGBCamera.cpp.
 { return red_; }
References red_.
Referenced by ManageCameras::saveCameras().
printCamera()
void RGBCamera::printCamera () override virtual
This method prints the camera information.
Reimplemented from Camera.
Definition at line 45 of file RGBCamera.cpp.
{
   if (isActive() and red_ != -1 and green_ != -1 and blue_ != -1)
     std::cout << "RGB Camera id (" << getId() << ")"
               << ": "
               << " red: " << red_ << " green: " << green_ << " blue: " << blue_
               << std::endl;
   else if (isActive() and red_ == -1 and green_ == -1 and blue_ == -1)
     std::cout << "RGB Camera " << getId()
               << " is active but has not collected data yet" << std::endl;
   else
     std::cout << "RGB Camera " << getId() << " is not active" << std::endl;
 }
References blue_, Camera::getId(), green_, Camera::isActive(), and red_.
Referenced by main().
randomComponent()
int RGBCamera::randomComponent ()
This method returns a random number between 0 and 255.
Returns
int
Definition at line 33 of file RGBCamera.cpp.
{
   // Random number entre 0 y 255
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_int_distribution<> dis(0, 255);
   return dis(gen);
 }
Referenced by collectData().
setBlue()
void RGBCamera::setBlue (int blue)
This method sets the blue value of the camera.
Parameters
blue
Definition at line 25 of file RGBCamera.cpp.
 { blue_ = blue; }
References blue_.
Referenced by setRGB().
setGreen()
void RGBCamera::setGreen (int green)
This method sets the green value of the camera.
Parameters
green
Definition at line 23 of file RGBCamera.cpp.
 { green_ = green; }
References green_.
Referenced by setRGB().
setRed()
void RGBCamera::setRed (int red)
This method sets the red value of the camera.
Parameters
red
Definition at line 21 of file RGBCamera.cpp.
 { red_ = red; }
References red_.
Referenced by setRGB().
setRGB()
void RGBCamera::setRGB (int red, int green, int blue)
This method sets the RGB values of the camera.
Parameters
red
green
blue
Definition at line 15 of file RGBCamera.cpp.
{
   setRed(red);
   setGreen(green);
   setBlue(blue);
 }
References setBlue(), setGreen(), and setRed().
Referenced by collectData(), and ManageCameras::loadCameras().
Member Data Documentation
blue_
int RGBCamera::blue_ private
This attribute represents the blue value of the camera.
Definition at line 111 of file RGBCamera.h.
Referenced by getBlue(), printCamera(), RGBCamera(), and setBlue().
green_
int RGBCamera::green_ private
This attribute represents the green value of the camera.
Definition at line 106 of file RGBCamera.h.
Referenced by getGreen(), printCamera(), RGBCamera(), and setGreen().
red_
int RGBCamera::red_ private
This attribute represents the red value of the camera.
Definition at line 101 of file RGBCamera.h.
Referenced by getRed(), printCamera(), RGBCamera(), and setRed().
The documentation for this class was generated from the following files:
src/RGBCamera.h
src/RGBCamera.cpp