Green House software: ManageCameras Class Reference
ManageCameras Class Reference
#include <ManageCameras.h>
Public Member Functions
ManageCameras ()
Construct a new Manage Cameras object.
~ManageCameras ()
Destroy the Manage Cameras object.
void createCamera (int id, std::string type)
Create a Camera object.
void clearCameras ()
Clear all the cameras.
void addCamera (Camera *camera)
Add a Camera object.
void removeCamera (int id)
Remove a Camera object.
Camera * findCamera (int id)
Find a Camera object.
void displayAllCameras ()
Display all the cameras.
void collectAndDisplayData ()
Collect and display the data of all the cameras.
void collectData ()
Collect the data of all the cameras.
void turnOnCameras ()
Turn on all the cameras.
void turnOffCameras ()
Turn off all the cameras.
void turnOnOffCameras (int status)
Turn on or off the cameras.
void saveCameras ()
Save the cameras to a file.
void loadCameras ()
Load the cameras from a file.
Private Attributes
std::set< Camera * > cameras_
This attribute is a set of Camera pointers.
std::string filename_ = "cameras.txt"
This attribute is the name of the file where the cameras are saved.
Detailed Description
Definition at line 21 of file ManageCameras.h.
Constructor & Destructor Documentation
ManageCameras()
ManageCameras::ManageCameras ()
Construct a new Manage Cameras object.
Definition at line 11 of file ManageCameras.cpp.
{
   // Crear las camaras por defecto
   cameras_.insert(new RGBCamera(1));
   cameras_.insert(new TemperatureCamera(2));
 }
~ManageCameras()
ManageCameras::~ManageCameras ()
Destroy the Manage Cameras object.
Definition at line 17 of file ManageCameras.cpp.
 { clearCameras(); }
Member Function Documentation
addCamera()
void ManageCameras::addCamera (Camera * camera)
Add a Camera object.
Parameters
camera
Definition at line 46 of file ManageCameras.cpp.
 { cameras_.insert(camera); }
clearCameras()
void ManageCameras::clearCameras ()
Clear all the cameras.
Definition at line 19 of file ManageCameras.cpp.
{
   for (auto camera : cameras_) {
     delete camera;
   }
   cameras_.clear();
 }
collectAndDisplayData()
void ManageCameras::collectAndDisplayData ()
Collect and display the data of all the cameras.
Definition at line 83 of file ManageCameras.cpp.
{
   collectData();
   displayAllCameras();
 }
Referenced by GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::manageGuest().
collectData()
void ManageCameras::collectData ()
Collect the data of all the cameras.
Definition at line 77 of file ManageCameras.cpp.
{
   for (Camera *camera : cameras_) {
     camera->collectData();
   }
 }
Referenced by main().
createCamera()
void ManageCameras::createCamera (int id, std::string type)
Create a Camera object.
Parameters
id
type
Definition at line 26 of file ManageCameras.cpp.
{
   // Pasar a mayusculas el tipo
   for (char &c : type) {
     c = toupper(c);
   }
   // Crear la camara y añadir el puntero a cameras_
   // SI ya esta ese id, no se crea la camara y se informa
   if (findCamera(id) == nullptr) {
     if (type == "RGB") {
       cameras_.insert(new RGBCamera(id));
     } else if (type == "TEMPERATURE") {
       cameras_.insert(new TemperatureCamera(id));
     } else {
       cout << "Invalid camera type" << endl;
     }
   } else {
     cout << "Camera with id " << id << " already exists" << endl;
   }
 }
Referenced by main(), GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
displayAllCameras()
void ManageCameras::displayAllCameras ()
Display all the cameras.
Definition at line 71 of file ManageCameras.cpp.
{
   for (Camera *camera : cameras_) {
     camera->printCamera();
   }
 }
Referenced by main().
findCamera()
Camera * ManageCameras::findCamera (int id)
Find a Camera object.
Parameters
id
Returns
Camera*
Definition at line 61 of file ManageCameras.cpp.
{
   // Encontrar la camara con el id dado y retornar el puntero
   for (Camera *camera : cameras_) {
     if (camera->getId() == id) {
       return camera;
     }
   }
   return nullptr;
 }
loadCameras()
void ManageCameras::loadCameras ()
Load the cameras from a file.
Definition at line 142 of file ManageCameras.cpp.
{
   // Crear un archivo de entrada
   std::ifstream file(filename_);
   if (file.is_open()) {
     // Hay que recorrer cada linea del archivo
     // Primero se leera el id, luego el tipo y luego los datos rgb o temperatura
     // dependiendo del tipo
     // Primero borrar las camaras actuales
     clearCameras();
     while (!file.eof()) {
       int id;
       std::string type;
       file >> id >> type;
       if (type == "RGB") {
         int red, green, blue;
         file >> red >> green >> blue;
         if (findCamera(id) != nullptr) {
           cout << "Camera with id " << id << " already exists" << endl;
           continue; // Si ya existe la camara, no se crea y se pasa a la
                     // siguiente
         }
         RGBCamera *rgbCamera = new RGBCamera(id);
         rgbCamera->setRGB(red, green, blue);
         cameras_.insert(rgbCamera);
       } else if (type == "TEMPERATURE") {
         float temperature;
         file >> temperature;
         if (findCamera(id) != nullptr) {
           cout << "Camera with id " << id << " already exists" << endl;
           continue; // Si ya existe la camara, no se crea y se pasa a la
                     // siguiente
         }
         TemperatureCamera *temperatureCamera = new TemperatureCamera(id);
         temperatureCamera->setTemperature(temperature);
         cameras_.insert(temperatureCamera);
       }
     }
     file.close();
     std::cout << "Cameras loaded" << std::endl;
   } else {
     std::cout << "Unable to open file" << std::endl;
   }
 }
References RGBCamera::setRGB(), and TemperatureCamera::setTemperature().
Referenced by main(), and GreenHouse::manageLogin().
removeCamera()
void ManageCameras::removeCamera (int id)
Remove a Camera object.
Parameters
id
Definition at line 48 of file ManageCameras.cpp.
{
   // Usar findcamera para encontrar la camara con el id dado
   Camera *camera = findCamera(id);
   // Si la camara existe, borrarla
   if (camera != nullptr) {
     cout << "Removing camera with id " << id << endl;
     cameras_.erase(camera);
     delete camera;
   } else {
     cout << "Camera with id " << id << " does not exist" << endl;
   }
 }
Referenced by main(), GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
saveCameras()
void ManageCameras::saveCameras ()
Save the cameras to a file.
Definition at line 112 of file ManageCameras.cpp.
{
   // Crear un archivo de salida
   std::ofstream file(filename_);
   if (file.is_open()) {
     for (Camera *camera : cameras_) {
       // Guardar el id, tipo y sus datos rgb o temperatura dependiendo del tipo
       // Guardando en este orden las cosa TIPO ID Datos
       if (camera->getType() == "RGB") {
         std::cout << "Saving RGB camera (" << camera->getId() << ")"
                   << std::endl;
         RGBCamera *rgbCamera = static_cast<RGBCamera *>(camera);
         file << camera->getId() << " " << camera->getType() << " "
              << rgbCamera->getRed() << " " << rgbCamera->getGreen() << " "
              << rgbCamera->getBlue() << std::endl;
       } else if (camera->getType() == "TEMPERATURE") {
         std::cout << "Saving Temperature camera (" << camera->getId() << ")"
                   << std::endl;
         TemperatureCamera *temperatureCamera =
             static_cast<TemperatureCamera *>(camera);
         file << camera->getId() << " " << camera->getType() << " "
              << temperatureCamera->getTemperature() << std::endl;
       }
     }
     file.close();
     std::cout << "Cameras saved" << std::endl;
   } else {
     std::cout << "Unable to open file" << std::endl;
   }
 }
References RGBCamera::getBlue(), RGBCamera::getGreen(), Camera::getId(), RGBCamera::getRed(), and TemperatureCamera::getTemperature().
Referenced by main(), GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::save().
turnOffCameras()
void ManageCameras::turnOffCameras ()
Turn off all the cameras.
Definition at line 95 of file ManageCameras.cpp.
{
   cout << "Turning off the cameras...\n" << endl;
   for (Camera *camera : cameras_) {
     camera->turnOff();
   }
 }
Referenced by main().
turnOnCameras()
void ManageCameras::turnOnCameras ()
Turn on all the cameras.
Definition at line 88 of file ManageCameras.cpp.
{
   cout << "Turning on the cameras...\n" << endl;
   for (Camera *camera : cameras_) {
     camera->turnOn();
   }
 }
turnOnOffCameras()
void ManageCameras::turnOnOffCameras (int status)
Turn on or off the cameras.
Parameters
status
Definition at line 102 of file ManageCameras.cpp.
{
   if (status == 1) {
     turnOnCameras();
   } else if (status == 2) {
     turnOffCameras();
   } else {
     cout << "Invalid status" << endl;
   }
 }
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
Member Data Documentation
cameras_
std::set<Camera *> ManageCameras::cameras_ private
This attribute is a set of Camera pointers.
Definition at line 116 of file ManageCameras.h.
filename_
std::string ManageCameras::filename_ = "cameras.txt" private
This attribute is the name of the file where the cameras are saved.
Definition at line 121 of file ManageCameras.h.
The documentation for this class was generated from the following files:
src/ManageCameras.h
src/ManageCameras.cpp