Green House software: TemperatureCamera Class Reference
TemperatureCamera Class Reference
#include <TemperatureCamera.h>
Public Member Functions
TemperatureCamera (int id)
Construct a new Temperature Camera object.
~TemperatureCamera ()
Destroy the Temperature Camera object.
void setTemperature (float temperature)
This method sets the temperature of the camera.
float getTemperature ()
This method gets the temperature of the camera.
void collectData () override
This method collects the data of the camera.
void printCamera () override
This method prints the camera information.
Public Member Functions inherited from Camera
Camera (int id, std::string type, bool active)
Construct a new Camera object.
virtual ~Camera ()
Destroy the Camera object.
void setId (int newid)
Set the id of the camera.
int getId () const
Get the id of the camera.
void setType (std::string newtype)
Set the type of the camera.
std::string getType () const
Get the type of the camera.
void turnOn ()
Turn on the camera.
void turnOff ()
Turn off the camera.
const bool isActive ()
Check if the camera is active.
Private Member Functions
float randomTemperature ()
This method generates a random temperature.
Private Attributes
float temperature_
This attribute stores the temperature of the camera.
Detailed Description
Definition at line 19 of file TemperatureCamera.h.
Constructor & Destructor Documentation
TemperatureCamera()
TemperatureCamera::TemperatureCamera (int id) explicit
Construct a new Temperature Camera object.
Parameters
id
Returns
TemperatureCamera object
Definition at line 10 of file TemperatureCamera.cpp.
                                            : Camera(id, "TEMPERATURE", true) {
   temperature_ = -1;
   std::cout << "Temperature Camera id (" << getId() << ") created" << std::endl;
 }
References Camera::getId(), and temperature_.
~TemperatureCamera()
TemperatureCamera::~TemperatureCamera ()
Destroy the Temperature Camera object.
Definition at line 15 of file TemperatureCamera.cpp.
 {}
Member Function Documentation
collectData()
void TemperatureCamera::collectData () override virtual
This method collects the data of the camera.
Reimplemented from Camera.
Definition at line 33 of file TemperatureCamera.cpp.
 { setTemperature(randomTemperature()); }
References randomTemperature(), and setTemperature().
Referenced by main().
getTemperature()
float TemperatureCamera::getTemperature ()
This method gets the temperature of the camera.
Returns
float
Definition at line 21 of file TemperatureCamera.cpp.
 { return temperature_; }
References temperature_.
Referenced by ManageCameras::saveCameras().
printCamera()
void TemperatureCamera::printCamera () override virtual
This method prints the camera information.
Reimplemented from Camera.
Definition at line 35 of file TemperatureCamera.cpp.
{
   if (isActive() and temperature_ != -1) {
     cout << "Temperature camera (" << getId() << ") record this temperature "
          << temperature_ << " ºC" << endl;
   } else if (isActive() and temperature_ == -1) {
     cout << "Temperature camera " << getId()
          << " is active but has not collected data yet" << endl;
   } else {
     cout << "Temperature camera " << getId() << " is not active" << endl;
   }
 }
References Camera::getId(), Camera::isActive(), and temperature_.
Referenced by main().
randomTemperature()
float TemperatureCamera::randomTemperature () private
This method generates a random temperature.
Returns
float
Definition at line 23 of file TemperatureCamera.cpp.
{
   // Random temperature entre 19.0 y 31.0
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_real_distribution<> dis(19.0, 31.0);
   float temperature = dis(gen);
   temperature = std::round(temperature * 100) / 100; // Redondea a dos decimales
   return temperature;
 }
Referenced by collectData().
setTemperature()
void TemperatureCamera::setTemperature (float temperature)
This method sets the temperature of the camera.
Parameters
temperature
Definition at line 17 of file TemperatureCamera.cpp.
{
   temperature_ = temperature;
 }
References temperature_.
Referenced by collectData(), and ManageCameras::loadCameras().
Member Data Documentation
temperature_
float TemperatureCamera::temperature_ private
This attribute stores the temperature of the camera.
Definition at line 69 of file TemperatureCamera.h.
Referenced by getTemperature(), printCamera(), setTemperature(), and TemperatureCamera().
The documentation for this class was generated from the following files:
src/TemperatureCamera.h
src/TemperatureCamera.cpp