Green House software: User Class Reference
User Class Reference
#include <User.h>
Public Member Functions
User ()
Construct a new User object.
User (const std::string name, const std::string nif, std::string password, std::string privileges, std::string email)
Construct a new User object.
std::string getName () const
Get the Name object.
std::string getNif () const
Get the Nif object.
std::string getPassword () const
Get the Password object.
std::string getPrivileges () const
Get the Privileges object.
std::string getEmail () const
Get the Email object.
void setName (const std::string name)
Set the Name object.
void setNif (const std::string nif)
Set the Nif object.
void setPassword (const std::string password)
Set the Password object.
virtual void setPrivileges (const std::string privileges)
Set the Privileges object.
void setEmail (const std::string email)
Set the Email object.
bool operator< (const User &user) const
Operator < overload (this comparison is made by the privileges)
bool operator> (const User &user) const
Operator > overload (this comparison is made by the privileges)
bool operator== (const User &user) const
Operator == overload (this comparison is made by the nif)
void printUser () const
Print the user.
virtual ~User ()
Destroy the User object.
Private Attributes
std::string name
This is the name of the user.
std::string nif
This is the nif of the user.
std::string password
This is the password of the user.
std::string privileges
This is the privileges of the user.
std::string email
This is the email of the user.
Friends
std::ostream & operator<< (std::ostream &os, const User &user)
Operator << overload.
std::istream & operator>> (std::istream &is, User &user)
Operator >> overload.
Detailed Description
Definition at line 14 of file User.h.
Constructor & Destructor Documentation
User() [1/2]
User::User ()
Construct a new User object.
Creates a new User object with the default values (name, nif, password, privileges, email).
Returns
User object
Definition at line 5 of file User.cpp.
            {
   name = "";
   nif = "";
   password = "";
   privileges = "";
   email = "";
 }
References email, name, nif, password, and privileges.
User() [2/2]
User::User (const std::string name, const std::string nif, std::string password, std::string privileges, std::string email) explicit
Construct a new User object.
Creates a new User object with the values passed as parameters.
Parameters
name of the user
nif of the user
password of the user
privileges of the user
email of the user
Returns
User object
Definition at line 13 of file User.cpp.
{
   // LLamar a los metodos set para que se encarguen de hacer las conversiones
   // necesarias
   setName(name);
   setNif(nif);
   setPassword(password);
   setPrivileges(privileges);
   setEmail(email);
 }
References email, name, nif, password, privileges, setEmail(), setName(), setNif(), setPassword(), and setPrivileges().
~User()
User::~User () virtual
Destroy the User object.
Definition at line 25 of file User.cpp.
 {}
Member Function Documentation
getEmail()
std::string User::getEmail () const
Get the Email object.
Returns
std::string
Definition at line 35 of file User.cpp.
 { return email; }
References email.
Referenced by main().
getName()
std::string User::getName () const
Get the Name object.
Returns
std::string
Definition at line 27 of file User.cpp.
 { return name; }
References name.
Referenced by main(), UserNameComparator::operator()(), and UsersServer::readUsersFromFileBi().
getNif()
std::string User::getNif () const
Get the Nif object.
Returns
std::string
Definition at line 29 of file User.cpp.
 { return nif; }
References nif.
Referenced by UsersDatabase::addUser(), main(), UserPtrComparator::operator()(), and UsersServer::readUsersFromFileBi().
getPassword()
std::string User::getPassword () const
Get the Password object.
Returns
std::string
Definition at line 31 of file User.cpp.
 { return password; }
References password.
Referenced by main().
getPrivileges()
std::string User::getPrivileges () const
Get the Privileges object.
Returns
std::string
Definition at line 33 of file User.cpp.
 { return privileges; }
References privileges.
Referenced by UsersDatabase::addUser(), UsersServer::getPrivileges(), main(), and UsersServer::readUsersFromFileBi().
operator<()
bool User::operator< (const User & user) const
Operator < overload (this comparison is made by the privileges)
Parameters
user
Returns
true
false
Definition at line 62 of file User.cpp.
{
   return privileges > other.privileges;
 }
References privileges.
operator==()
bool User::operator== (const User & user) const
Operator == overload (this comparison is made by the nif)
Parameters
user
Returns
true
false
Definition at line 73 of file User.cpp.
 { return nif == other.nif; }
References nif.
operator>()
bool User::operator> (const User & user) const
Operator > overload (this comparison is made by the privileges)
Parameters
user
Returns
true
false
Definition at line 68 of file User.cpp.
{
   return privileges < other.privileges;
 };
References privileges.
printUser()
void User::printUser () const
Print the user.
Definition at line 52 of file User.cpp.
{
   std::cout << "----------User------------" << std::endl;
   std::cout << "Name: " << name << std::endl;
   std::cout << "NIF: " << nif << std::endl;
   std::cout << "Password: " << password << std::endl;
   std::cout << "Privileges: " << privileges << std::endl;
   std::cout << "Email: " << email << std::endl;
   std::cout << "--------------------------" << std::endl;
 }
References email, name, nif, password, and privileges.
Referenced by main().
setEmail()
void User::setEmail (const std::string email)
Set the Email object.
Parameters
email
Definition at line 50 of file User.cpp.
 { this->email = email; }
References email.
Referenced by main(), UsersServer::readUsersFromFileBi(), UsersServer::updateUser(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
setName()
void User::setName (const std::string name)
Set the Name object.
Parameters
name
Definition at line 37 of file User.cpp.
 { this->name = name; }
References name.
Referenced by main(), UsersServer::readUsersFromFileBi(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
setNif()
void User::setNif (const std::string nif)
Set the Nif object.
Parameters
nif
Definition at line 39 of file User.cpp.
 { this->nif = nif; }
References nif.
Referenced by main(), UsersServer::readUsersFromFileBi(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
setPassword()
void User::setPassword (const std::string password)
Set the Password object.
Parameters
password
Definition at line 41 of file User.cpp.
 { this->password = password; }
References password.
Referenced by main(), UsersServer::readUsersFromFileBi(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
setPrivileges()
void User::setPrivileges (const std::string privileges) virtual
Set the Privileges object.
Parameters
privileges
Definition at line 43 of file User.cpp.
{
   for (std::string::size_type i = 0; i < privileges.length(); i++) {
     privileges[i] = toupper(privileges[i]);
   }
   this->privileges = privileges;
 }
References privileges.
Referenced by main(), UsersServer::readUsersFromFileBi(), UsersServer::updateUser(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const User & user) friend
Operator << overload.
Parameters
os
user
Returns
std::ostream&
Definition at line 76 of file User.cpp.
{
   os << user.getName() << " " << user.getNif() << " " << user.getPassword()
      << " " << user.getPrivileges() << " " << user.getEmail() << std::endl;
   return os;
 }
operator>>
std::istream& operator>> (std::istream & is, User & user) friend
Operator >> overload.
Parameters
is
user
Returns
std::istream&
Definition at line 83 of file User.cpp.
{
   std::string privilege;
   is >> user.name >> user.nif >> user.password >> privilege >> user.email;
   user.setPrivileges(privilege);
   return is;
 }
Member Data Documentation
email
std::string User::email private
This is the email of the user.
Definition at line 184 of file User.h.
Referenced by getEmail(), printUser(), setEmail(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
name
std::string User::name private
This is the name of the user.
Definition at line 164 of file User.h.
Referenced by getName(), printUser(), setName(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
nif
std::string User::nif private
This is the nif of the user.
Definition at line 169 of file User.h.
Referenced by getNif(), operator==(), printUser(), setNif(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
password
std::string User::password private
This is the password of the user.
Definition at line 174 of file User.h.
Referenced by getPassword(), printUser(), setPassword(), User(), UserAdmin::UserAdmin(), UserEmployee::UserEmployee(), and UserGuest::UserGuest().
privileges
std::string User::privileges private
This is the privileges of the user.
Definition at line 179 of file User.h.
Referenced by getPrivileges(), operator<(), operator>(), printUser(), setPrivileges(), and User().
The documentation for this class was generated from the following files:
src/User.h
src/User.cpp