Green House software: AirQualitySensor Class Reference
AirQualitySensor Class Reference
#include <AirQualitySensor.h>
Public Member Functions
AirQualitySensor (int id, bool active)
Construct a new Air Quality Sensor object.
~AirQualitySensor () override
Destroy the Air Quality Sensor object.
void collectData () override
Collect data of the Air Quality Sensor.
bool checkAllgood () const override
Check if the Air Quality Sensor is working properly.
void printData () const override
Print the data of the Air Quality Sensor.
void collectAndPrint ()
Collect and print the data of the Air Quality Sensor.
std::string stringStatus () const
This method returns if the Air Quality Sensor is active or not and if its active, it returns if its good or bad the data.
Public Member Functions inherited from Sensor
Sensor ()
Construct a new Sensor object.
Sensor (int id, Types type, bool active)
Construct a new Sensor object.
virtual ~Sensor ()
Destroy the Sensor object.
bool isActive () const
Return if is active or not the sensor.
void turnOff ()
Turn off the sensor.
void turnOn ()
Turn on the sensor.
float getData () const
Get the Data object.
void setData (float data)
Set the Data object.
int getId () const
Get the Id object.
void setId (int newid)
Set the Id object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool operator< (const Sensor &Sensor) const
Operator < overload.
bool operator> (const Sensor &Sensor) const
Operator > overload.
bool operator== (const Sensor &Sensor) const
Operator == overload.
Friends
std::ostream & operator<< (std::ostream &os, const AirQualitySensor &sensor)
This method prints the AirQualitySensor object.
Additional Inherited Members
Public Types inherited from Sensor
enum Types {
NONE , TEMPERATURE , AIR_QUALITY , HYDROMETER ,
PRESSURE , LIGHT_SENSOR , PH_SENSOR
}
This is the enum Types. It contains the types of the sensors.
Detailed Description
Definition at line 15 of file AirQualitySensor.h.
Constructor & Destructor Documentation
AirQualitySensor()
AirQualitySensor::AirQualitySensor (int id, bool active) explicit
Construct a new Air Quality Sensor object.
Parameters
id
active
Returns
AirQualitySensor object
Definition at line 9 of file AirQualitySensor.cpp.
     : Sensor(id, Sensor::Types::AIR_QUALITY, active) {}
~AirQualitySensor()
AirQualitySensor::~AirQualitySensor () override
Destroy the Air Quality Sensor object.
Definition at line 12 of file AirQualitySensor.cpp.
 {}
Member Function Documentation
checkAllgood()
bool AirQualitySensor::checkAllgood () const override virtual
Check if the Air Quality Sensor is working properly.
Returns
true if the Air Quality Sensor is working properly
false if the Air Quality Sensor is not working properly
Reimplemented from Sensor.
Definition at line 24 of file AirQualitySensor.cpp.
{
   // Por debajo de 65 microgramos/m3 se considera buena calidad del aire
   float data = Sensor::getData();
   if (data <= 65) {
     return true;
   } else {
     return false;
   }
 }
References Sensor::getData().
Referenced by stringStatus().
collectAndPrint()
void AirQualitySensor::collectAndPrint () virtual
Collect and print the data of the Air Quality Sensor.
Reimplemented from Sensor.
Definition at line 65 of file AirQualitySensor.cpp.
{
   collectData();
   printData();
 }
References collectData(), and printData().
Referenced by main().
collectData()
void AirQualitySensor::collectData () override virtual
Collect data of the Air Quality Sensor.
This method collects the data of the Air Quality Sensor and stores it in the data attribute.
Reimplemented from Sensor.
Definition at line 14 of file AirQualitySensor.cpp.
{
   // Generamos un numero random entre 0 y 70 para simular la calidad del aire en
   // microgramos/m3
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_int_distribution<> dis(0, 70);
   int airQuality = dis(gen);
   Sensor::setData(airQuality);
 }
References Sensor::setData().
Referenced by collectAndPrint(), and main().
printData()
void AirQualitySensor::printData () const override virtual
Print the data of the Air Quality Sensor.
Reimplemented from Sensor.
Definition at line 52 of file AirQualitySensor.cpp.
{
   // Imprimimos las particulas por microgramo/m3, el id del sensor, y si todo
   // esta bien o no
   if (Sensor::isActive()) {
     std::cout << "Air Quality Sensor with "
               << "ID: " << Sensor::getId() << " - Data: " << Sensor::getData()
               << " microgram/m3 - Status: " << stringStatus() << std::endl;
   } else {
     std::cout << "Air Quality Sensor ID: " << Sensor::getId() << " - INACTIVE"
               << std::endl;
   }
 }
References Sensor::getData(), Sensor::getId(), Sensor::isActive(), and stringStatus().
Referenced by collectAndPrint(), and main().
stringStatus()
std::string AirQualitySensor::stringStatus () const
This method returns if the Air Quality Sensor is active or not and if its active, it returns if its good or bad the data.
Returns
std::string
Definition at line 40 of file AirQualitySensor.cpp.
{
   if (Sensor::isActive()) {
     if (this->checkAllgood()) {
       return "ACTIVE - GOOD STATUS";
     } else {
       return "ACTIVE - BAD STATUS";
     }
   } else {
     return "INACTIVE";
   }
 }
References checkAllgood(), and Sensor::isActive().
Referenced by main(), and printData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const AirQualitySensor & sensor) friend
This method prints the AirQualitySensor object.
Parameters
os
sensor
Returns
std::ostream&
Definition at line 35 of file AirQualitySensor.cpp.
{
   sensor.printData();
   return os;
 }
The documentation for this class was generated from the following files:
src/AirQualitySensor.h
src/AirQualitySensor.cpp