Green House software: Sensor Class Reference
Sensor Class Reference
#include <Sensor.h>
Public Types
enum Types {
NONE , TEMPERATURE , AIR_QUALITY , HYDROMETER ,
PRESSURE , LIGHT_SENSOR , PH_SENSOR
}
This is the enum Types. It contains the types of the sensors.
Public Member Functions
Sensor ()
Construct a new Sensor object.
Sensor (int id, Types type, bool active)
Construct a new Sensor object.
virtual ~Sensor ()
Destroy the Sensor object.
virtual void collectData ()
Collect data of the Sensor.
virtual void collectAndPrint ()
Collect and print the data of the Sensor.
bool isActive () const
Return if is active or not the sensor.
void turnOff ()
Turn off the sensor.
void turnOn ()
Turn on the sensor.
float getData () const
Get the Data object.
void setData (float data)
Set the Data object.
int getId () const
Get the Id object.
void setId (int newid)
Set the Id object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
virtual bool checkAllgood () const
Check if the Sensor is working properly.
bool operator< (const Sensor &Sensor) const
Operator < overload.
bool operator> (const Sensor &Sensor) const
Operator > overload.
bool operator== (const Sensor &Sensor) const
Operator == overload.
virtual void printData () const
Print the data of the Sensor.
Private Member Functions
Types stringToType (const std::string &type) const
Convert the string to the type.
std::string typeToString (Types type) const
Convert the type to the string.
Private Attributes
int id_
The id of the sensor.
Types type_
The type of the sensor.
bool active_
The state of the sensor.
float data_
The data of the sensor.
Friends
std::ostream & operator<< (std::ostream &os, const Sensor &Sensor)
Operator << overload.
std::istream & operator>> (std::istream &is, Sensor &Sensor)
Operator >> overload.
Detailed Description
Definition at line 13 of file Sensor.h.
Member Enumeration Documentation
Types
enum Sensor::Types
This is the enum Types. It contains the types of the sensors.
Enumerator
NONE
TEMPERATURE
AIR_QUALITY
HYDROMETER
PRESSURE
LIGHT_SENSOR
PH_SENSOR
Definition at line 19 of file Sensor.h.
              {
     NONE,
     TEMPERATURE,
     AIR_QUALITY,
     HYDROMETER,
     PRESSURE,
     LIGHT_SENSOR,
     PH_SENSOR,
   };
Constructor & Destructor Documentation
Sensor() [1/2]
Sensor::Sensor ()
Construct a new Sensor object.
Creates a new Sensor object with the default values (id, type, active).
Returns
Sensor object
Definition at line 6 of file Sensor.cpp.
                {
   id_ = -1;
   type_ = Types::NONE;
   active_ = false;
   data_ = -1;
 }
Sensor() [2/2]
Sensor::Sensor (int id, Types type, bool active) explicit
Construct a new Sensor object.
Creates a new Sensor object with the values passed as parameters.
Parameters
id of the sensor
type of the sensor
active of the sensor
Returns
Sensor object
Definition at line 13 of file Sensor.cpp.
{
   id_ = id;
   type_ = type;
   active_ = active;
   data_ = -1;
 }
~Sensor()
Sensor::~Sensor () virtual
Destroy the Sensor object.
Definition at line 20 of file Sensor.cpp.
 {}
Member Function Documentation
checkAllgood()
bool Sensor::checkAllgood () const virtual
Check if the Sensor is working properly.
Returns
true if the Sensor is working properly
false if the Sensor is not working properly
Reimplemented in TemperatureSensor, PressureSensor, PhSensor, LightSensor, HydrometerSensor, and AirQualitySensor.
Definition at line 128 of file Sensor.cpp.
 { return true; }
Referenced by main().
collectAndPrint()
void Sensor::collectAndPrint () virtual
Collect and print the data of the Sensor.
Reimplemented in TemperatureSensor, PressureSensor, PhSensor, LightSensor, HydrometerSensor, and AirQualitySensor.
Definition at line 31 of file Sensor.cpp.
{
   collectData();
   printData();
 }
collectData()
void Sensor::collectData () virtual
Collect data of the Sensor.
Reimplemented in TemperatureSensor, PressureSensor, PhSensor, LightSensor, HydrometerSensor, and AirQualitySensor.
Definition at line 22 of file Sensor.cpp.
{
   cout << "Collecting data from sensor id" << id_ << " wich is: " << getType()
        << endl;
   setData(-10000);
   // This function will be implemented in the derived classes
   // en la clase derivada se implementara la funcion, generaremos de manera
   // aleatoria el valor y despues lo asignaremos al atributo data_ con setData()
 }
Referenced by main().
getData()
float Sensor::getData () const
Get the Data object.
Returns
float
Definition at line 42 of file Sensor.cpp.
 { return data_; }
Referenced by AirQualitySensor::checkAllgood(), HydrometerSensor::checkAllgood(), LightSensor::checkAllgood(), PhSensor::checkAllgood(), PressureSensor::checkAllgood(), TemperatureSensor::checkAllgood(), main(), AirQualitySensor::printData(), HydrometerSensor::printData(), LightSensor::printData(), PhSensor::printData(), PressureSensor::printData(), TemperatureSensor::printData(), and PhSensor::qualifyPh().
getId()
int Sensor::getId () const
Get the Id object.
Returns
int
Definition at line 46 of file Sensor.cpp.
 { return id_; }
Referenced by main(), AirQualitySensor::printData(), HydrometerSensor::printData(), LightSensor::printData(), PhSensor::printData(), PressureSensor::printData(), and TemperatureSensor::printData().
getType()
std::string Sensor::getType () const
Get the Type object.
Returns
std::string
Definition at line 50 of file Sensor.cpp.
{
   std::string type = typeToString(type_);
   return type;
 }
Referenced by main().
isActive()
bool Sensor::isActive () const
Return if is active or not the sensor.
Returns
true
false
Definition at line 36 of file Sensor.cpp.
 { return active_; }
Referenced by main(), AirQualitySensor::printData(), HydrometerSensor::printData(), LightSensor::printData(), PhSensor::printData(), PressureSensor::printData(), TemperatureSensor::printData(), AirQualitySensor::stringStatus(), HydrometerSensor::stringStatus(), LightSensor::stringStatus(), PhSensor::stringStatus(), PressureSensor::stringStatus(), and TemperatureSensor::stringStatus().
operator<()
bool Sensor::operator< (const Sensor & Sensor) const
Operator < overload.
Parameters
Sensor
Returns
true
false
Definition at line 94 of file Sensor.cpp.
 { return id_ < Sensor.id_; }
References id_.
operator==()
bool Sensor::operator== (const Sensor & Sensor) const
Operator == overload.
Parameters
Sensor
Returns
true
false
Definition at line 98 of file Sensor.cpp.
{
   return id_ == Sensor.id_;
 }
References id_.
operator>()
bool Sensor::operator> (const Sensor & Sensor) const
Operator > overload.
Parameters
Sensor
Returns
true
false
Definition at line 96 of file Sensor.cpp.
 { return id_ > Sensor.id_; }
References id_.
printData()
void Sensor::printData () const virtual
Print the data of the Sensor.
Reimplemented in TemperatureSensor, PressureSensor, PhSensor, LightSensor, HydrometerSensor, and AirQualitySensor.
Definition at line 122 of file Sensor.cpp.
{
   cout << "This prints the data of sensor " << getType() << " with id" << id_
        << " please use the correct function to print the data" << endl;
   // This function will be implemented in the derived classes
 }
Referenced by main().
setData()
void Sensor::setData (float data)
Set the Data object.
Parameters
data
Definition at line 44 of file Sensor.cpp.
 { data_ = data; }
Referenced by AirQualitySensor::collectData(), HydrometerSensor::collectData(), LightSensor::collectData(), PhSensor::collectData(), PressureSensor::collectData(), TemperatureSensor::collectData(), and main().
setId()
void Sensor::setId (int newid)
Set the Id object.
Parameters
newid
Definition at line 48 of file Sensor.cpp.
 { id_ = newid; }
Referenced by main().
setType()
void Sensor::setType (std::string newtype)
Set the Type object.
Parameters
newtype
Definition at line 55 of file Sensor.cpp.
 { type_ = stringToType(newtype); }
Referenced by main().
stringToType()
Sensor::Types Sensor::stringToType (const std::string & type) const private
Convert the string to the type.
Parameters
type
Returns
Types
Definition at line 57 of file Sensor.cpp.
{
   if (type == "TEMPERATURE") {
     return Types::TEMPERATURE;
   } else if (type == "AIR_QUALITY") {
     return Types::AIR_QUALITY;
   } else if (type == "HYDROMETER") {
     return Types::HYDROMETER;
   } else if (type == "PRESSURE") {
     return Types::PRESSURE;
   } else if (type == "LIGHT_SENSOR") {
     return Types::LIGHT_SENSOR;
   } else if (type == "PH_SENSOR") {
     return Types::PH_SENSOR;
   } else {
     return Types::NONE;
   }
 }
turnOff()
void Sensor::turnOff ()
Turn off the sensor.
Definition at line 38 of file Sensor.cpp.
 { active_ = false; }
Referenced by main().
turnOn()
void Sensor::turnOn ()
Turn on the sensor.
Definition at line 40 of file Sensor.cpp.
 { active_ = true; }
Referenced by main().
typeToString()
std::string Sensor::typeToString (Types type) const private
Convert the type to the string.
Parameters
type
Returns
std::string
Definition at line 75 of file Sensor.cpp.
{
   switch (type) {
   case Types::TEMPERATURE:
     return "TEMPERATURE";
   case Types::AIR_QUALITY:
     return "AIR_QUALITY";
   case Types::HYDROMETER:
     return "HYDROMETER";
   case Types::PRESSURE:
     return "PRESSURE";
   case Types::LIGHT_SENSOR:
     return "LIGHT_SENSOR";
   case Types::PH_SENSOR:
     return "PH_SENSOR";
   default:
     return "NONE";
   }
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Sensor & Sensor) friend
Operator << overload.
Parameters
os
Sensor
Returns
std::ostream&
Definition at line 102 of file Sensor.cpp.
{
   os << "ID: " << Sensor.getId() << " Type: " << Sensor.getType()
      << " Active: " << Sensor.isActive() << " Data: " << Sensor.getData()
      << std::endl;
   return os;
 }
operator>>
std::istream& operator>> (std::istream & is, Sensor & Sensor) friend
Operator >> overload.
Parameters
is
Sensor
Returns
std::istream&
Definition at line 109 of file Sensor.cpp.
{
   cout << "Enter sensor ID: ";
   is >> sensor.id_;
   cout << "Enter the type: ";
   std::string type;
   is >> type;
   sensor.setType(type);
   cout << "Enter sensor active: ";
   is >> sensor.active_;
   return is;
 }
Member Data Documentation
active_
bool Sensor::active_ private
The state of the sensor.
Definition at line 194 of file Sensor.h.
data_
float Sensor::data_ private
The data of the sensor.
Definition at line 199 of file Sensor.h.
id_
int Sensor::id_ private
The id of the sensor.
Definition at line 184 of file Sensor.h.
Referenced by operator<(), operator==(), and operator>().
type_
Types Sensor::type_ private
The type of the sensor.
Definition at line 189 of file Sensor.h.
The documentation for this class was generated from the following files:
src/Sensor.h
src/Sensor.cpp