Green House software: PhSensor Class Reference
PhSensor Class Reference
#include <PhSensor.h>
Public Member Functions
PhSensor (int id, bool active)
Construct a new Ph Sensor object.
~PhSensor () override
Destroy the Ph Sensor object.
void collectData () override
Collect data of the Ph Sensor.
bool checkAllgood () const override
Check if the Ph Sensor is working properly.
std::string qualifyPh () const
This qualifies the Ph Sensor into Acidic, Neutral or Alkaline.
void printData () const override
This method prints the data of the Ph Sensor.
std::string stringStatus () const
This method returns the status in a string.
void collectAndPrint ()
Collect and print the data of the Ph Sensor.
Public Member Functions inherited from Sensor
Sensor ()
Construct a new Sensor object.
Sensor (int id, Types type, bool active)
Construct a new Sensor object.
virtual ~Sensor ()
Destroy the Sensor object.
bool isActive () const
Return if is active or not the sensor.
void turnOff ()
Turn off the sensor.
void turnOn ()
Turn on the sensor.
float getData () const
Get the Data object.
void setData (float data)
Set the Data object.
int getId () const
Get the Id object.
void setId (int newid)
Set the Id object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool operator< (const Sensor &Sensor) const
Operator < overload.
bool operator> (const Sensor &Sensor) const
Operator > overload.
bool operator== (const Sensor &Sensor) const
Operator == overload.
Friends
std::ostream & operator<< (std::ostream &os, const PhSensor &sensor)
Operator << overload.
Additional Inherited Members
Public Types inherited from Sensor
enum Types {
NONE , TEMPERATURE , AIR_QUALITY , HYDROMETER ,
PRESSURE , LIGHT_SENSOR , PH_SENSOR
}
This is the enum Types. It contains the types of the sensors.
Detailed Description
Definition at line 15 of file PhSensor.h.
Constructor & Destructor Documentation
PhSensor()
PhSensor::PhSensor (int id, bool active) explicit
Construct a new Ph Sensor object.
Parameters
id
active
Returns
PhSensor object
Definition at line 9 of file PhSensor.cpp.
     : Sensor(id, Sensor::Types::PH_SENSOR, active) {}
~PhSensor()
PhSensor::~PhSensor () override
Destroy the Ph Sensor object.
Definition at line 11 of file PhSensor.cpp.
 {}
Member Function Documentation
checkAllgood()
bool PhSensor::checkAllgood () const override virtual
Check if the Ph Sensor is working properly.
Returns
true if the Ph Sensor is working properly
false if the Ph Sensor is not working properly
Reimplemented from Sensor.
Definition at line 22 of file PhSensor.cpp.
{
   float data = Sensor::getData();
   if (data >= 6.2 && data <= 7.8) {
     return true;
   } else {
     return false;
   }
 }
References Sensor::getData().
Referenced by qualifyPh(), and stringStatus().
collectAndPrint()
void PhSensor::collectAndPrint () virtual
Collect and print the data of the Ph Sensor.
Reimplemented from Sensor.
Definition at line 72 of file PhSensor.cpp.
{
   collectData();
   printData();
 }
References collectData(), and printData().
Referenced by main().
collectData()
void PhSensor::collectData () override virtual
Collect data of the Ph Sensor.
This method collects the data of the Ph Sensor and stores it in the data attribute.
Reimplemented from Sensor.
Definition at line 13 of file PhSensor.cpp.
{
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_real_distribution<> dis(6, 8);
   float reading = dis(gen);
   Sensor::setData(reading);
 }
References Sensor::setData().
Referenced by collectAndPrint(), and main().
printData()
void PhSensor::printData () const override virtual
This method prints the data of the Ph Sensor.
Reimplemented from Sensor.
Definition at line 43 of file PhSensor.cpp.
{
   if (Sensor::isActive()) {
     std::cout << "Ph Sensor with "
               << "ID: " << Sensor::getId() << " - Data: " << Sensor::getData()
               << " - Status: " << stringStatus()
               << " - Qualification: " << qualifyPh() << endl;
   } else {
     std::cout << "Ph Sensor ID: " << Sensor::getId()
               << " - Status: " << stringStatus() << endl;
   }
 }
References Sensor::getData(), Sensor::getId(), Sensor::isActive(), qualifyPh(), and stringStatus().
Referenced by collectAndPrint(), and main().
qualifyPh()
std::string PhSensor::qualifyPh () const
This qualifies the Ph Sensor into Acidic, Neutral or Alkaline.
Returns
std::string of the qualification of the Ph Sensor
Definition at line 32 of file PhSensor.cpp.
{
   float data = Sensor::getData();
   if (this->checkAllgood()) {
     return "Ideal";
   } else if (data < 6.5f) {
     return "Acidic";
   } else {
     return "Alkaline";
   }
 }
References checkAllgood(), and Sensor::getData().
Referenced by printData().
stringStatus()
std::string PhSensor::stringStatus () const
This method returns the status in a string.
Returns
std::string of the status of the Ph Sensor
Definition at line 60 of file PhSensor.cpp.
{
   if (Sensor::isActive()) {
     if (this->checkAllgood()) {
       return "ACTIVE - GOOD STATUS";
     } else {
       return "ACTIVE - BAD STATUS";
     }
   } else {
     return "INACTIVE";
   }
 }
References checkAllgood(), and Sensor::isActive().
Referenced by main(), and printData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const PhSensor & sensor) friend
Operator << overload.
Definition at line 55 of file PhSensor.cpp.
{
   sensor.printData();
   return os;
 }
The documentation for this class was generated from the following files:
src/PhSensor.h
src/PhSensor.cpp