Green House software: SwitchHardware Class Reference
SwitchHardware Class Reference
#include <SwitchHardware.h>
Public Member Functions
SwitchHardware (bool active)
Construct a new Switch Hardware object.
~SwitchHardware () override
Destroy the Switch Hardware object.
int askInput () override
Ask for an input.
void displayOutput () const override
Display the output of the Switch Hardware.
Public Member Functions inherited from Hardware
Hardware ()
Construct a new Hardware object.
Hardware (bool active, Types_Hardware type)
Construct a new Hardware object.
virtual ~Hardware ()
Destroy the Hardware object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool isActive () const
If the hardware is active.
void turnOn ()
Turn on the hardware.
void turnOff ()
Turn off the hardware.
std::string stringStatus () const
This method returns if the hardware is active or not in a string.
Private Member Functions
void translateInput (int input)
The data of the Switch Hardware.
Additional Inherited Members
Public Types inherited from Hardware
enum Types_Hardware { NONE , SCREEN , KEYBOARD , SWITCH }
Enum of the types of hardware.
Detailed Description
Definition at line 14 of file SwitchHardware.h.
Constructor & Destructor Documentation
SwitchHardware()
SwitchHardware::SwitchHardware (bool active) explicit
Construct a new Switch Hardware object.
Parameters
active
Returns
SwitchHardware object
Definition at line 7 of file SwitchHardware.cpp.
     : Hardware(active, Hardware::Types_Hardware::SWITCH) {}
~SwitchHardware()
SwitchHardware::~SwitchHardware () override
Destroy the Switch Hardware object.
Definition at line 10 of file SwitchHardware.cpp.
 {}
Member Function Documentation
askInput()
int SwitchHardware::askInput () override virtual
Ask for an input.
Returns
int
Reimplemented from Hardware.
Definition at line 20 of file SwitchHardware.cpp.
{
   int input;
   std::string input_string;
   // Preguntamos al usuario si ON of OFF y luego el input se lo pasamos a
   // translateInputToBool
   std::cout << "Switch wating a input(ON/OFF)..." << std::endl;
   std::cin >> input_string;
   if (input_string == "ON") {
     input = 1;
   }
   if (input_string == "OFF") {
     input = 0;
   }
   translateInput(input);
   return input;
   // El valor de active_ sera true o false dependiendo de si se activa o se
   // desactiva el switch
 }
References translateInput().
Referenced by main().
displayOutput()
void SwitchHardware::displayOutput () const override virtual
Display the output of the Switch Hardware.
Reimplemented from Hardware.
Definition at line 40 of file SwitchHardware.cpp.
{
   std::cout << stringStatus() << std::endl;
 }
References Hardware::stringStatus().
Referenced by main().
translateInput()
void SwitchHardware::translateInput (int input) private
The data of the Switch Hardware.
Definition at line 12 of file SwitchHardware.cpp.
{
   if (input) {
     turnOn();
   } else {
     turnOff();
   }
 }
References Hardware::turnOff(), and Hardware::turnOn().
Referenced by askInput().
The documentation for this class was generated from the following files:
src/SwitchHardware.h
src/SwitchHardware.cpp