Green House software: MonitoringSystem Class Reference
MonitoringSystem Class Reference
#include <MonitoringSystem.h>
Public Member Functions
MonitoringSystem (ScreenHardware *screen, KeyboardHardware *keyboard, SwitchHardware *sw)
Construct a new Monitoring System object.
~MonitoringSystem ()
Destroy the Monitoring System object.
int getSelection ()
Get the Selection object.
std::string getName ()
Get the Name object.
std::string getNIF ()
Get the NIF object.
std::string getPassword ()
Get the Password object.
std::string getNameSelectedUser ()
Get the Name Selected User object.
std::string getNIFSelectedUser ()
Get the NIF Selected User object.
std::string getPasswordSelectedUser ()
Get the Password Selected User object.
std::string getPrivilegesSelectedUser ()
Get the Privileges Selected User object.
std::string getEmailSelectedUser ()
Get the Email Selected User object.
int getIdAlarm ()
Get the Id Alarm object.
std::string getTypeAlarm ()
Get the Type Alarm object.
int getIdSelectedAlarm ()
Get the Id Selected Alarm object.
std::string getTypeCamera ()
Get the Type Camera object.
int getIdCamera ()
Get the Id Camera object.
int getIdSelectedCamera ()
Get the Id Selected Camera object.
void initialScreen ()
This method initializes the screen and keyboard.
void exitScreen ()
This method exits the screen.
void loginScreen ()
This method shows the login screen.
void mainWindowAdmin ()
This method shows the main menu for the admins.
void mainWindowEmployee ()
This method shows the main menu for the employees.
void mainWindowGuest ()
This method shows the main menu for the guests.
void createUserScreen ()
This method shows the message to create a new user.
void deleteUserScreen ()
This method shows the message to delete a user.
void updateUserScreen ()
This method shows the message to update a user.
void displayUsersScreen ()
This method shows the message to show the users.
void displaySensorsScreen ()
This method shows the message to show the sensors.
void displayAlarmsScreen ()
This method shows the message to show the alarms.
void turnOnOffSystemScreen ()
This method shows the message to turn on or off the system.
void displayErrorScreen ()
This method shows the message if and error occurs.
void createAlarmScreen ()
This method shows the message to create a new alarm.
void deleteAlarmScreen ()
This method shows the message to delete an alarm.
void saveAlarmScreen ()
This method shows the message to save an alarm.
void displayCameraScreen ()
Display the camera screen.
void createCameraScreen ()
Create a Camera Screen object.
void deleteCameraScreen ()
Delete a Camera Screen object.
void turnOnOffCameraScreen ()
Turn on or off a Camera Screen object.
void saveCameraScreen ()
Save a Camera Screen object.
void cleanScreen ()
Clean the screen.
void saveUsersScreen ()
Save the users screen.
Private Member Functions
bool inputCorrect (int input, int max)
This method checks if the input is correct.
int askInputInt (int max)
This method asks the user for an int input.
std::string askName ()
This method asks the user for an input for the name.
std::string askNIF ()
This method asks the user for an input for the NIF.
std::string askPassword ()
This method asks the user for an input for the password.
std::string askPrivileges ()
This method asks the user for an input for the privileges.
std::string askEmail ()
This method asks the user for an input for the email.
void selectUser ()
This is the method to select a user.
void shortSelectUser ()
This is the method to select a short user.
void askMainUser ()
This is the method to ask the main user, the one that its going to loggin.
std::string askTypeAlarm ()
This is the method to ask the type of the alarm.
int askIdAlarm ()
This is the method to ask the id of the alarm.
std::string askTypeCamera ()
This is the method to ask the type of the camera.
int askIdCamera ()
This is the method to ask the id of the camera.
Private Attributes
ScreenHardware * screen
This is the pointer to the ScreenHardware object.
KeyboardHardware * keyboard
This is the pointer to the KeyboardHardware object.
SwitchHardware * sw
This is the pointer to the SwitchHardware object.
int selection_
This is the selection of the user.
std::string name_
This is the name of the user.
std::string nif_
This is the NIF of the user.
std::string password_
This is the password of the user.
std::string nameSelectedUser_
This is the name of the selected user.
std::string nifSelectedUser_
This is the password of the selected user.
std::string passwordSelectedUser_
This is the privileges of the selected user.
std::string privilegesSelectedUser_
This is the privileges of the selected user.
std::string emailSelectedUser_
This is the email of the selected user.
int idAlarm_
This attribute is the id of the alarm.
std::string typeAlarm_
This attribute is the type of the alarm.
int idSelectedAlarm_
This attribute is the id of the selected alarm.
int idCamera_
This attribute is the id of the camera.
std::string typeCamera_
This attribute is the type of the camera.
int idSelectedCamera_
This attribute is the id of the selected camera.
Detailed Description
Definition at line 24 of file MonitoringSystem.h.
Constructor & Destructor Documentation
MonitoringSystem()
MonitoringSystem::MonitoringSystem (ScreenHardware * screen, KeyboardHardware * keyboard, SwitchHardware * sw) explicit
Construct a new Monitoring System object.
Parameters
screen
keyboard
sw
Definition at line 15 of file MonitoringSystem.cpp.
     : screen(screen), keyboard(keyboard), sw(sw) {}
~MonitoringSystem()
MonitoringSystem::~MonitoringSystem ()
Destroy the Monitoring System object.
Definition at line 20 of file MonitoringSystem.cpp.
{
   delete screen;
   delete keyboard;
   delete sw;
 }
References keyboard, screen, and sw.
Member Function Documentation
askEmail()
std::string MonitoringSystem::askEmail () private
This method asks the user for an input for the email.
Returns
std::string
Definition at line 134 of file MonitoringSystem.cpp.
{
   std::cout << "(EMAIL) ";
   return keyboard->stringInput();
 }
References keyboard, and KeyboardHardware::stringInput().
Referenced by selectUser().
askIdAlarm()
int MonitoringSystem::askIdAlarm () private
This is the method to ask the id of the alarm.
Definition at line 243 of file MonitoringSystem.cpp.
{
   std::cout << "(ID ALARM) ";
   return keyboard->askInput();
 }
References KeyboardHardware::askInput(), and keyboard.
Referenced by createAlarmScreen(), and deleteAlarmScreen().
askIdCamera()
int MonitoringSystem::askIdCamera () private
This is the method to ask the id of the camera.
Returns
int
Definition at line 287 of file MonitoringSystem.cpp.
{
   // Pido con el keyboard un input que sera el id de la camara
   std::cout << "(ID CAMERA) ";
   return keyboard->askInput();
 }
References KeyboardHardware::askInput(), and keyboard.
Referenced by createCameraScreen(), and deleteCameraScreen().
askInputInt()
int MonitoringSystem::askInputInt (int max) private
This method asks the user for an int input.
Parameters
max
Returns
int
Definition at line 89 of file MonitoringSystem.cpp.
{
   int input;
   do {
     input = keyboard->askInput();
   } while (!inputCorrect(input, max));
   return input;
 }
References KeyboardHardware::askInput(), inputCorrect(), and keyboard.
Referenced by initialScreen(), mainWindowAdmin(), mainWindowEmployee(), mainWindowGuest(), turnOnOffCameraScreen(), and turnOnOffSystemScreen().
askMainUser()
void MonitoringSystem::askMainUser () private
This is the method to ask the main user, the one that its going to loggin.
Definition at line 42 of file MonitoringSystem.cpp.
{
   name_ = askName();
   password_ = askPassword();
   nif_ = askNIF();
 }
References askName(), askNIF(), askPassword(), name_, nif_, and password_.
Referenced by loginScreen().
askName()
std::string MonitoringSystem::askName () private
This method asks the user for an input for the name.
Returns
std::string
Definition at line 114 of file MonitoringSystem.cpp.
{
   std::cout << "(NAME) ";
   return keyboard->stringInput();
 }
References keyboard, and KeyboardHardware::stringInput().
Referenced by askMainUser(), selectUser(), and shortSelectUser().
askNIF()
std::string MonitoringSystem::askNIF () private
This method asks the user for an input for the NIF.
Returns
std::string
Definition at line 124 of file MonitoringSystem.cpp.
{
   std::cout << "(NIF) ";
   return keyboard->stringInput();
 }
References keyboard, and KeyboardHardware::stringInput().
Referenced by askMainUser(), selectUser(), and shortSelectUser().
askPassword()
std::string MonitoringSystem::askPassword () private
This method asks the user for an input for the password.
Returns
std::string
Definition at line 119 of file MonitoringSystem.cpp.
{
   std::cout << "(PASSWORD) ";
   return keyboard->stringInput();
 }
References keyboard, and KeyboardHardware::stringInput().
Referenced by askMainUser(), selectUser(), and shortSelectUser().
askPrivileges()
std::string MonitoringSystem::askPrivileges () private
This method asks the user for an input for the privileges.
Returns
std::string
Definition at line 129 of file MonitoringSystem.cpp.
{
   std::cout << "(PRIVILEGES) ";
   return keyboard->stringInput();
 }
References keyboard, and KeyboardHardware::stringInput().
Referenced by selectUser().
askTypeAlarm()
std::string MonitoringSystem::askTypeAlarm () private
This is the method to ask the type of the alarm.
Definition at line 238 of file MonitoringSystem.cpp.
{
   std::cout << "(TYPE ALARM) ";
   return keyboard->stringInput();
 }
References keyboard, and KeyboardHardware::stringInput().
Referenced by createAlarmScreen().
askTypeCamera()
std::string MonitoringSystem::askTypeCamera () private
This is the method to ask the type of the camera.
Returns
std::string
Definition at line 281 of file MonitoringSystem.cpp.
{
   // Pido con el keyboard un input que sera el tipo de la camara
   std::cout << "(TYPE CAMERA) ";
   return keyboard->stringInput();
 }
References keyboard, and KeyboardHardware::stringInput().
Referenced by createCameraScreen().
cleanScreen()
void MonitoringSystem::cleanScreen ()
Clean the screen.
Definition at line 322 of file MonitoringSystem.cpp.
{
   // Muestro de screen la cleanScreen
   screen->cleanScreen();
 }
References ScreenHardware::cleanScreen(), and screen.
Referenced by GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), GreenHouse::manageGuest(), and GreenHouse::manageLogin().
createAlarmScreen()
void MonitoringSystem::createAlarmScreen ()
This method shows the message to create a new alarm.
Definition at line 248 of file MonitoringSystem.cpp.
{
   // Muestro de screen la createAlarmWindow
   screen->cleanScreen();
   screen->createAlarmWindow();
   typeAlarm_ = askTypeAlarm();
   idAlarm_ = askIdAlarm();
 }
References askIdAlarm(), askTypeAlarm(), ScreenHardware::cleanScreen(), ScreenHardware::createAlarmWindow(), idAlarm_, screen, and typeAlarm_.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
createCameraScreen()
void MonitoringSystem::createCameraScreen ()
Create a Camera Screen object.
Definition at line 293 of file MonitoringSystem.cpp.
{
   // Muestro de screen la createCameraWindow
   screen->cleanScreen();
   screen->createCameraWindow();
   idCamera_ = askIdCamera();
   typeCamera_ = askTypeCamera();
 }
References askIdCamera(), askTypeCamera(), ScreenHardware::cleanScreen(), ScreenHardware::createCameraWindow(), idCamera_, screen, and typeCamera_.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
createUserScreen()
void MonitoringSystem::createUserScreen ()
This method shows the message to create a new user.
Definition at line 177 of file MonitoringSystem.cpp.
{
   // Muestro de screen la createUserWindow, luego pido con el keyboard un input
   // hasta que este entre los valores correctos
   screen->cleanScreen();
   screen->createUserWindow();
   selectUser();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::createUserWindow(), screen, and selectUser().
Referenced by main(), and GreenHouse::manageCreateUser().
deleteAlarmScreen()
void MonitoringSystem::deleteAlarmScreen ()
This method shows the message to delete an alarm.
Definition at line 256 of file MonitoringSystem.cpp.
{
   // Muestro de screen la deleteAlarmWindow
   screen->cleanScreen();
   screen->deleteAlarmWindow();
   idSelectedAlarm_ = askIdAlarm();
 }
References askIdAlarm(), ScreenHardware::cleanScreen(), ScreenHardware::deleteAlarmWindow(), idSelectedAlarm_, and screen.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
deleteCameraScreen()
void MonitoringSystem::deleteCameraScreen ()
Delete a Camera Screen object.
Definition at line 301 of file MonitoringSystem.cpp.
{
   // Muestro de screen la deleteCameraWindow
   screen->cleanScreen();
   screen->deleteCameraWindow();
   idSelectedCamera_ = askIdCamera();
 }
References askIdCamera(), ScreenHardware::cleanScreen(), ScreenHardware::deleteCameraWindow(), idSelectedCamera_, and screen.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
deleteUserScreen()
void MonitoringSystem::deleteUserScreen ()
This method shows the message to delete a user.
Definition at line 185 of file MonitoringSystem.cpp.
{
   // Muestro de screen la deleteUserWindow, luego pido con el keyboard un input
   // hasta que este entre los valores correctos
   screen->cleanScreen();
   screen->deleteUserWindow();
   shortSelectUser();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::deleteUserWindow(), screen, and shortSelectUser().
Referenced by main(), and GreenHouse::manageDeleteUser().
displayAlarmsScreen()
void MonitoringSystem::displayAlarmsScreen ()
This method shows the message to show the alarms.
Definition at line 215 of file MonitoringSystem.cpp.
{
   // Muestro de screen la displayAlarmsWindow
   screen->cleanScreen();
   screen->displayAlarmsWindow();
   // keyboard->stringInput();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::displayAlarmsWindow(), and screen.
Referenced by main(), GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::manageGuest().
displayCameraScreen()
void MonitoringSystem::displayCameraScreen ()
Display the camera screen.
Definition at line 275 of file MonitoringSystem.cpp.
{
   // Muestro de screen la displayCameraWindow
   screen->cleanScreen();
   screen->displayCameraWindow();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::displayCameraWindow(), and screen.
Referenced by GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::manageGuest().
displayErrorScreen()
void MonitoringSystem::displayErrorScreen ()
This method shows the message if and error occurs.
Definition at line 230 of file MonitoringSystem.cpp.
{
   // Muestro de screen la displayErrorWindow
   screen->cleanScreen();
   screen->displayErrorWindow();
   keyboard->stringInput();
   exitScreen();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::displayErrorWindow(), exitScreen(), keyboard, screen, and KeyboardHardware::stringInput().
Referenced by GreenHouse::mainSystem(), GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::manageGuest().
displaySensorsScreen()
void MonitoringSystem::displaySensorsScreen ()
This method shows the message to show the sensors.
Definition at line 208 of file MonitoringSystem.cpp.
{
   // Muestro de screen la displaySensorsWindow
   screen->cleanScreen();
   screen->displaySensorsWindow();
   // keyboard->stringInput();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::displaySensorsWindow(), and screen.
Referenced by main(), GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::manageGuest().
displayUsersScreen()
void MonitoringSystem::displayUsersScreen ()
This method shows the message to show the users.
Definition at line 201 of file MonitoringSystem.cpp.
{
   // Muestro de screen la displayUsersWindow
   screen->cleanScreen();
   screen->displayUsersWindow();
   // keyboard->stringInput();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::displayUsersWindow(), and screen.
Referenced by main(), and GreenHouse::manageAdmin().
exitScreen()
void MonitoringSystem::exitScreen ()
This method exits the screen.
Definition at line 108 of file MonitoringSystem.cpp.
{
   // Borrar terminal y mostrar el exitWindow
   screen->cleanScreen();
   screen->exitWindow();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::exitWindow(), and screen.
Referenced by displayErrorScreen(), main(), GreenHouse::mainSystem(), GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), GreenHouse::manageGuest(), and GreenHouse::manageLogin().
getEmailSelectedUser()
std::string MonitoringSystem::getEmailSelectedUser ()
Get the Email Selected User object.
Returns
std::string
Definition at line 74 of file MonitoringSystem.cpp.
{
   return emailSelectedUser_;
 }
References emailSelectedUser_.
Referenced by GreenHouse::manageCreateUser(), and GreenHouse::manageUpdateUser().
getIdAlarm()
int MonitoringSystem::getIdAlarm ()
Get the Id Alarm object.
Returns
int
Definition at line 50 of file MonitoringSystem.cpp.
 { return idAlarm_; }
References idAlarm_.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
getIdCamera()
int MonitoringSystem::getIdCamera ()
Get the Id Camera object.
Returns
int
Definition at line 271 of file MonitoringSystem.cpp.
 { return idCamera_; }
References idCamera_.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
getIdSelectedAlarm()
int MonitoringSystem::getIdSelectedAlarm ()
Get the Id Selected Alarm object.
Returns
int
Definition at line 52 of file MonitoringSystem.cpp.
 { return idSelectedAlarm_; }
References idSelectedAlarm_.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
getIdSelectedCamera()
int MonitoringSystem::getIdSelectedCamera ()
Get the Id Selected Camera object.
Returns
int
Definition at line 273 of file MonitoringSystem.cpp.
 { return idSelectedCamera_; }
References idSelectedCamera_.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
getName()
std::string MonitoringSystem::getName ()
Get the Name object.
Returns
std::string
Definition at line 54 of file MonitoringSystem.cpp.
 { return name_; }
References name_.
Referenced by GreenHouse::manageLogin().
getNameSelectedUser()
std::string MonitoringSystem::getNameSelectedUser ()
Get the Name Selected User object.
Returns
std::string
Definition at line 60 of file MonitoringSystem.cpp.
{
   return nameSelectedUser_;
 }
References nameSelectedUser_.
Referenced by GreenHouse::manageCreateUser(), GreenHouse::manageDeleteUser(), and GreenHouse::manageUpdateUser().
getNIF()
std::string MonitoringSystem::getNIF ()
Get the NIF object.
Returns
std::string
Definition at line 56 of file MonitoringSystem.cpp.
 { return nif_; }
References nif_.
Referenced by GreenHouse::manageLogin().
getNIFSelectedUser()
std::string MonitoringSystem::getNIFSelectedUser ()
Get the NIF Selected User object.
Returns
std::string
Definition at line 64 of file MonitoringSystem.cpp.
 { return nifSelectedUser_; }
References nifSelectedUser_.
Referenced by GreenHouse::manageCreateUser(), GreenHouse::manageDeleteUser(), and GreenHouse::manageUpdateUser().
getPassword()
std::string MonitoringSystem::getPassword ()
Get the Password object.
Returns
std::string
Definition at line 58 of file MonitoringSystem.cpp.
 { return password_; }
References password_.
Referenced by GreenHouse::manageLogin().
getPasswordSelectedUser()
std::string MonitoringSystem::getPasswordSelectedUser ()
Get the Password Selected User object.
Returns
std::string
Definition at line 66 of file MonitoringSystem.cpp.
{
   return passwordSelectedUser_;
 }
References passwordSelectedUser_.
Referenced by GreenHouse::manageCreateUser(), GreenHouse::manageDeleteUser(), and GreenHouse::manageUpdateUser().
getPrivilegesSelectedUser()
std::string MonitoringSystem::getPrivilegesSelectedUser ()
Get the Privileges Selected User object.
Returns
std::string
Definition at line 70 of file MonitoringSystem.cpp.
{
   return privilegesSelectedUser_;
 }
References privilegesSelectedUser_.
Referenced by GreenHouse::manageCreateUser(), and GreenHouse::manageUpdateUser().
getSelection()
int MonitoringSystem::getSelection ()
Get the Selection object.
Returns
int
Definition at line 26 of file MonitoringSystem.cpp.
 { return selection_; }
References selection_.
Referenced by main(), GreenHouse::mainSystem(), GreenHouse::manageAdmin(), GreenHouse::manageEmployee(), and GreenHouse::manageGuest().
getTypeAlarm()
std::string MonitoringSystem::getTypeAlarm ()
Get the Type Alarm object.
Returns
std::string
Definition at line 48 of file MonitoringSystem.cpp.
 { return typeAlarm_; }
References typeAlarm_.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
getTypeCamera()
std::string MonitoringSystem::getTypeCamera ()
Get the Type Camera object.
Returns
std::string
Definition at line 269 of file MonitoringSystem.cpp.
 { return typeCamera_; }
References typeCamera_.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
initialScreen()
void MonitoringSystem::initialScreen ()
This method initializes the screen and keyboard.
Definition at line 99 of file MonitoringSystem.cpp.
{
   screen->cleanScreen();
   int options = MAIN_MENU_OPTIONS;
   // Muestro de screen la initialWindow, luego pido con el keyboard un input
   // hasta que este entre los valores correctos
   screen->initialWindow();
   selection_ = askInputInt(options);
 }
References askInputInt(), ScreenHardware::cleanScreen(), ScreenHardware::initialWindow(), MAIN_MENU_OPTIONS, screen, and selection_.
Referenced by main(), and GreenHouse::startSystem().
inputCorrect()
bool MonitoringSystem::inputCorrect (int input, int max) private
This method checks if the input is correct.
Parameters
input
max
Returns
true
false
Definition at line 78 of file MonitoringSystem.cpp.
{
   bool correct = input >= 1 && input <= max;
   if (!correct) {
     cout << "Invalid input. Please enter an integer that corresponds to one of "
             "the options"
          << endl;
   }
   // Input debe de estar entre 1 y max
   return correct;
 }
Referenced by askInputInt().
loginScreen()
void MonitoringSystem::loginScreen ()
This method shows the login screen.
Definition at line 139 of file MonitoringSystem.cpp.
{
   // Muestro de screen la loginWindow, luego pido con el keyboard un input hasta
   // que este entre los valores correctos
   screen->cleanScreen();
   screen->loginWindow();
   askMainUser();
   // std::cout << name_ << " " << password_ << " " << nif_ << endl;
 }
References askMainUser(), ScreenHardware::cleanScreen(), ScreenHardware::loginWindow(), and screen.
Referenced by main(), and GreenHouse::mainSystem().
mainWindowAdmin()
void MonitoringSystem::mainWindowAdmin ()
This method shows the main menu for the admins.
Definition at line 148 of file MonitoringSystem.cpp.
{
   // Muestro de screen la mainWindowAdmin, luego pido con el keyboard un input
   // hasta que este entre los valores correctos
   screen->cleanScreen();
   int options = ADMIN_MENU_OPTIONS;
   screen->mainWindowAdmin();
   selection_ = askInputInt(options);
 }
References ADMIN_MENU_OPTIONS, askInputInt(), ScreenHardware::cleanScreen(), ScreenHardware::mainWindowAdmin(), screen, and selection_.
Referenced by main(), and GreenHouse::manageAdmin().
mainWindowEmployee()
void MonitoringSystem::mainWindowEmployee ()
This method shows the main menu for the employees.
Definition at line 157 of file MonitoringSystem.cpp.
{
   // Muestro de screen la mainWindowEmployee, luego pido con el keyboard un
   // input hasta que este entre los valores correctos
   screen->cleanScreen();
   int options = EMPLOYEE_MENU_OPTIONS;
   screen->mainWindowEmployee();
   selection_ = askInputInt(options);
 }
References askInputInt(), ScreenHardware::cleanScreen(), EMPLOYEE_MENU_OPTIONS, ScreenHardware::mainWindowEmployee(), screen, and selection_.
Referenced by GreenHouse::manageEmployee().
mainWindowGuest()
void MonitoringSystem::mainWindowGuest ()
This method shows the main menu for the guests.
Definition at line 166 of file MonitoringSystem.cpp.
{
   // Muestro de screen la mainWindowGuest, luego pido con el keyboard un input
   // hasta que este entre los valores correctos
   screen->cleanScreen();
   int options = GUEST_MENU_OPTIONS;
   screen->mainWindowGuest();
   selection_ = askInputInt(options);
 }
References askInputInt(), ScreenHardware::cleanScreen(), GUEST_MENU_OPTIONS, ScreenHardware::mainWindowGuest(), screen, and selection_.
Referenced by GreenHouse::manageGuest().
saveAlarmScreen()
void MonitoringSystem::saveAlarmScreen ()
This method shows the message to save an alarm.
Definition at line 263 of file MonitoringSystem.cpp.
{
   // Muestro de screen la saveAlarmWindow
   screen->cleanScreen();
   screen->saveAlarmWindow();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::saveAlarmWindow(), and screen.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
saveCameraScreen()
void MonitoringSystem::saveCameraScreen ()
Save a Camera Screen object.
Definition at line 316 of file MonitoringSystem.cpp.
{
   // Muestro de screen la saveCameraWindow
   screen->cleanScreen();
   screen->saveCameraWindow();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::saveCameraWindow(), and screen.
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
saveUsersScreen()
void MonitoringSystem::saveUsersScreen ()
Save the users screen.
Definition at line 327 of file MonitoringSystem.cpp.
{
   // Muestro de screen la saveUsersWindow
   screen->cleanScreen();
   screen->saveUsersWindow();
 }
References ScreenHardware::cleanScreen(), ScreenHardware::saveUsersWindow(), and screen.
Referenced by GreenHouse::manageAdmin().
selectUser()
void MonitoringSystem::selectUser () private
This is the method to select a user.
In this selection you have to introduce all the parameters of the user.
Definition at line 28 of file MonitoringSystem.cpp.
{
   nameSelectedUser_ = askName();
   passwordSelectedUser_ = askPassword();
   nifSelectedUser_ = askNIF();
   privilegesSelectedUser_ = askPrivileges();
   emailSelectedUser_ = askEmail();
 }
References askEmail(), askName(), askNIF(), askPassword(), askPrivileges(), emailSelectedUser_, nameSelectedUser_, nifSelectedUser_, passwordSelectedUser_, and privilegesSelectedUser_.
Referenced by createUserScreen(), and updateUserScreen().
shortSelectUser()
void MonitoringSystem::shortSelectUser () private
This is the method to select a short user.
In this selection you have to introduce the name, the password and the NIF of the user.
Definition at line 36 of file MonitoringSystem.cpp.
{
   nameSelectedUser_ = askName();
   passwordSelectedUser_ = askPassword();
   nifSelectedUser_ = askNIF();
 }
References askName(), askNIF(), askPassword(), nameSelectedUser_, nifSelectedUser_, and passwordSelectedUser_.
Referenced by deleteUserScreen().
turnOnOffCameraScreen()
void MonitoringSystem::turnOnOffCameraScreen ()
Turn on or off a Camera Screen object.
Definition at line 308 of file MonitoringSystem.cpp.
{
   // Muestro de screen la turnOnOffCameraWindow
   screen->cleanScreen();
   int options = 2;
   screen->turnOnOffCameraWindow();
   selection_ = askInputInt(options);
 }
References askInputInt(), ScreenHardware::cleanScreen(), screen, selection_, and ScreenHardware::turnOnOffCameraWindow().
Referenced by GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
turnOnOffSystemScreen()
void MonitoringSystem::turnOnOffSystemScreen ()
This method shows the message to turn on or off the system.
Definition at line 222 of file MonitoringSystem.cpp.
{
   // Muestro de screen la turnOnOffSystemWindow
   screen->cleanScreen();
   int options = 2;
   screen->turnOnOffSystemWindow();
   selection_ = askInputInt(options);
 }
References askInputInt(), ScreenHardware::cleanScreen(), screen, selection_, and ScreenHardware::turnOnOffSystemWindow().
Referenced by main(), GreenHouse::manageAdmin(), and GreenHouse::manageEmployee().
updateUserScreen()
void MonitoringSystem::updateUserScreen ()
This method shows the message to update a user.
Definition at line 193 of file MonitoringSystem.cpp.
{
   // Muestro de screen la updateUserWindow, luego pido con el keyboard un input
   // hasta que este entre los valores correctos
   screen->cleanScreen();
   screen->updateUserWindow();
   selectUser();
 }
References ScreenHardware::cleanScreen(), screen, selectUser(), and ScreenHardware::updateUserWindow().
Referenced by main(), and GreenHouse::manageUpdateUser().
Member Data Documentation
emailSelectedUser_
std::string MonitoringSystem::emailSelectedUser_ private
This is the email of the selected user.
Definition at line 414 of file MonitoringSystem.h.
Referenced by getEmailSelectedUser(), and selectUser().
idAlarm_
int MonitoringSystem::idAlarm_ private
This attribute is the id of the alarm.
Definition at line 430 of file MonitoringSystem.h.
Referenced by createAlarmScreen(), and getIdAlarm().
idCamera_
int MonitoringSystem::idCamera_ private
This attribute is the id of the camera.
Definition at line 457 of file MonitoringSystem.h.
Referenced by createCameraScreen(), and getIdCamera().
idSelectedAlarm_
int MonitoringSystem::idSelectedAlarm_ private
This attribute is the id of the selected alarm.
Definition at line 438 of file MonitoringSystem.h.
Referenced by deleteAlarmScreen(), and getIdSelectedAlarm().
idSelectedCamera_
int MonitoringSystem::idSelectedCamera_ private
This attribute is the id of the selected camera.
Definition at line 467 of file MonitoringSystem.h.
Referenced by deleteCameraScreen(), and getIdSelectedCamera().
keyboard
KeyboardHardware* MonitoringSystem::keyboard private
This is the pointer to the KeyboardHardware object.
Definition at line 287 of file MonitoringSystem.h.
Referenced by askEmail(), askIdAlarm(), askIdCamera(), askInputInt(), askName(), askNIF(), askPassword(), askPrivileges(), askTypeAlarm(), askTypeCamera(), displayErrorScreen(), and ~MonitoringSystem().
name_
std::string MonitoringSystem::name_ private
This is the name of the user.
Definition at line 352 of file MonitoringSystem.h.
Referenced by askMainUser(), and getName().
nameSelectedUser_
std::string MonitoringSystem::nameSelectedUser_ private
This is the name of the selected user.
This is the NIF of the selected user.
Definition at line 394 of file MonitoringSystem.h.
Referenced by getNameSelectedUser(), selectUser(), and shortSelectUser().
nif_
std::string MonitoringSystem::nif_ private
This is the NIF of the user.
Definition at line 357 of file MonitoringSystem.h.
Referenced by askMainUser(), and getNIF().
nifSelectedUser_
std::string MonitoringSystem::nifSelectedUser_ private
This is the password of the selected user.
Definition at line 399 of file MonitoringSystem.h.
Referenced by getNIFSelectedUser(), selectUser(), and shortSelectUser().
password_
std::string MonitoringSystem::password_ private
This is the password of the user.
Definition at line 362 of file MonitoringSystem.h.
Referenced by askMainUser(), and getPassword().
passwordSelectedUser_
std::string MonitoringSystem::passwordSelectedUser_ private
This is the privileges of the selected user.
Definition at line 404 of file MonitoringSystem.h.
Referenced by getPasswordSelectedUser(), selectUser(), and shortSelectUser().
privilegesSelectedUser_
std::string MonitoringSystem::privilegesSelectedUser_ private
This is the privileges of the selected user.
Definition at line 409 of file MonitoringSystem.h.
Referenced by getPrivilegesSelectedUser(), and selectUser().
screen
ScreenHardware* MonitoringSystem::screen private
This is the pointer to the ScreenHardware object.
Definition at line 282 of file MonitoringSystem.h.
Referenced by cleanScreen(), createAlarmScreen(), createCameraScreen(), createUserScreen(), deleteAlarmScreen(), deleteCameraScreen(), deleteUserScreen(), displayAlarmsScreen(), displayCameraScreen(), displayErrorScreen(), displaySensorsScreen(), displayUsersScreen(), exitScreen(), initialScreen(), loginScreen(), mainWindowAdmin(), mainWindowEmployee(), mainWindowGuest(), saveAlarmScreen(), saveCameraScreen(), saveUsersScreen(), turnOnOffCameraScreen(), turnOnOffSystemScreen(), updateUserScreen(), and ~MonitoringSystem().
selection_
int MonitoringSystem::selection_ private
This is the selection of the user.
Definition at line 347 of file MonitoringSystem.h.
Referenced by getSelection(), initialScreen(), mainWindowAdmin(), mainWindowEmployee(), mainWindowGuest(), turnOnOffCameraScreen(), and turnOnOffSystemScreen().
sw
SwitchHardware* MonitoringSystem::sw private
This is the pointer to the SwitchHardware object.
Definition at line 292 of file MonitoringSystem.h.
Referenced by ~MonitoringSystem().
typeAlarm_
std::string MonitoringSystem::typeAlarm_ private
This attribute is the type of the alarm.
Definition at line 434 of file MonitoringSystem.h.
Referenced by createAlarmScreen(), and getTypeAlarm().
typeCamera_
std::string MonitoringSystem::typeCamera_ private
This attribute is the type of the camera.
Definition at line 462 of file MonitoringSystem.h.
Referenced by createCameraScreen(), and getTypeCamera().
The documentation for this class was generated from the following files:
src/MonitoringSystem.h
src/MonitoringSystem.cpp