Green House software: UserEmployee Class Reference
UserEmployee Class Reference
#include <UserEmployee.h>
Public Member Functions
UserEmployee ()
Construct a new User Employee object.
UserEmployee (const std::string name, const std::string nif, std::string password, std::string email)
Construct a new User Employee object.
virtual ~UserEmployee ()
Destroy the User Employee object.
Public Member Functions inherited from User
User ()
Construct a new User object.
User (const std::string name, const std::string nif, std::string password, std::string privileges, std::string email)
Construct a new User object.
std::string getName () const
Get the Name object.
std::string getNif () const
Get the Nif object.
std::string getPassword () const
Get the Password object.
std::string getPrivileges () const
Get the Privileges object.
std::string getEmail () const
Get the Email object.
void setName (const std::string name)
Set the Name object.
void setNif (const std::string nif)
Set the Nif object.
void setPassword (const std::string password)
Set the Password object.
virtual void setPrivileges (const std::string privileges)
Set the Privileges object.
void setEmail (const std::string email)
Set the Email object.
bool operator< (const User &user) const
Operator < overload (this comparison is made by the privileges)
bool operator> (const User &user) const
Operator > overload (this comparison is made by the privileges)
bool operator== (const User &user) const
Operator == overload (this comparison is made by the nif)
void printUser () const
Print the user.
virtual ~User ()
Destroy the User object.
Detailed Description
Definition at line 15 of file UserEmployee.h.
Constructor & Destructor Documentation
UserEmployee() [1/2]
UserEmployee::UserEmployee ()
Construct a new User Employee object.
Creates a new UserEmployee object with the default values (name, nif, password, email).
Returns
UserEmployee object
Definition at line 3 of file UserEmployee.cpp.
{
   // Utilizar los setters para asignar valores a los atributos
   setName("");
   setNif("");
   setPassword("");
   setEmail("");
   setPrivileges("EMPLOYEE");
 }
References User::setEmail(), User::setName(), User::setNif(), User::setPassword(), and User::setPrivileges().
UserEmployee() [2/2]
UserEmployee::UserEmployee (const std::string name, const std::string nif, std::string password, std::string email) explicit
Construct a new User Employee object.
Creates a new UserEmployee object with the values passed as parameters.
Parameters
name of the user
nif of the user
password of the user
email of the user
Returns
UserEmployee object
Definition at line 12 of file UserEmployee.cpp.
{
   // Utilizar los setters para asignar valores a los atributos
   setName(name);
   setNif(nif);
   setPassword(password);
   setEmail(email);
   setPrivileges("EMPLOYEE");
 }
References User::email, User::name, User::nif, User::password, User::setEmail(), User::setName(), User::setNif(), User::setPassword(), and User::setPrivileges().
~UserEmployee()
UserEmployee::~UserEmployee () virtual
Destroy the User Employee object.
Definition at line 22 of file UserEmployee.cpp.
 {}
The documentation for this class was generated from the following files:
src/UserEmployee.h
src/UserEmployee.cpp