Green House software: TemperatureSensor Class Reference
TemperatureSensor Class Reference
#include <TemperatureSensor.h>
Public Member Functions
TemperatureSensor (int id, bool active)
Construct a new Temperature Sensor object.
~TemperatureSensor () override
Destroy the Temperature Sensor object.
void collectData () override
Collect data of the Temperature Sensor.
bool checkAllgood () const override
Check if the Temperature Sensor is working properly.
void printData () const override
Print the data of the Temperature Sensor.
std::string stringStatus () const
String status of the Temperature Sensor.
void collectAndPrint ()
Collect and print the data of the Temperature Sensor.
Public Member Functions inherited from Sensor
Sensor ()
Construct a new Sensor object.
Sensor (int id, Types type, bool active)
Construct a new Sensor object.
virtual ~Sensor ()
Destroy the Sensor object.
bool isActive () const
Return if is active or not the sensor.
void turnOff ()
Turn off the sensor.
void turnOn ()
Turn on the sensor.
float getData () const
Get the Data object.
void setData (float data)
Set the Data object.
int getId () const
Get the Id object.
void setId (int newid)
Set the Id object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool operator< (const Sensor &Sensor) const
Operator < overload.
bool operator> (const Sensor &Sensor) const
Operator > overload.
bool operator== (const Sensor &Sensor) const
Operator == overload.
Friends
std::ostream & operator<< (std::ostream &os, const TemperatureSensor &sensor)
Overloaded operator<<.
Additional Inherited Members
Public Types inherited from Sensor
enum Types {
NONE , TEMPERATURE , AIR_QUALITY , HYDROMETER ,
PRESSURE , LIGHT_SENSOR , PH_SENSOR
}
This is the enum Types. It contains the types of the sensors.
Detailed Description
Definition at line 15 of file TemperatureSensor.h.
Constructor & Destructor Documentation
TemperatureSensor()
TemperatureSensor::TemperatureSensor (int id, bool active) explicit
Construct a new Temperature Sensor object.
Parameters
id
active
Returns
TemperatureSensor object
Definition at line 10 of file TemperatureSensor.cpp.
     : Sensor(id, Sensor::Types::TEMPERATURE, active) {}
~TemperatureSensor()
TemperatureSensor::~TemperatureSensor () override
Destroy the Temperature Sensor object.
Definition at line 13 of file TemperatureSensor.cpp.
 {}
Member Function Documentation
checkAllgood()
bool TemperatureSensor::checkAllgood () const override virtual
Check if the Temperature Sensor is working properly.
Returns
true if the Temperature Sensor is working properly
false if the Temperature Sensor is not working properly
Reimplemented from Sensor.
Definition at line 25 of file TemperatureSensor.cpp.
{
   float data = Sensor::getData();
   // Entre 20 y 30 estara bien la temperatura, en el resto de los casos no
   // estara bien
   if (data >= 20.0f && data <= 30.0f) {
     return true;
   } else {
     return false;
   }
 }
References Sensor::getData().
Referenced by stringStatus().
collectAndPrint()
void TemperatureSensor::collectAndPrint () virtual
Collect and print the data of the Temperature Sensor.
Reimplemented from Sensor.
Definition at line 66 of file TemperatureSensor.cpp.
{
   collectData();
   printData();
 }
References collectData(), and printData().
Referenced by main().
collectData()
void TemperatureSensor::collectData () override virtual
Collect data of the Temperature Sensor.
This method collects the data of the Temperature Sensor and stores it in the data attribute.
Reimplemented from Sensor.
Definition at line 15 of file TemperatureSensor.cpp.
{
   // Generamos una temperatura aleatoria entre 19 y 31 grados Centigrados
   std::random_device rd;
   std::mt19937 gen(rd());
   std::uniform_real_distribution<> dis(19.0, 31.0);
   float temperature = dis(gen);
   Sensor::setData(temperature);
 }
References Sensor::setData().
Referenced by collectAndPrint(), and main().
printData()
void TemperatureSensor::printData () const override virtual
Print the data of the Temperature Sensor.
Reimplemented from Sensor.
Definition at line 53 of file TemperatureSensor.cpp.
{
   // Imprimimos la temperatura actual del sensor, el id que tiene el sensor, y
   // si todo esta bien o no con (True/False)
   if (Sensor::isActive()) {
     std::cout << "Temperature Sensor with "
               << "ID: " << Sensor::getId() << " - Data: " << Sensor::getData()
               << " Cº - Status: " << stringStatus() << endl;
   } else {
     std::cout << "Temperature Sensor with "
               << "ID: " << Sensor::getId() << " - INACTIVE" << endl;
   }
 }
References Sensor::getData(), Sensor::getId(), Sensor::isActive(), and stringStatus().
Referenced by collectAndPrint(), and main().
stringStatus()
std::string TemperatureSensor::stringStatus () const
String status of the Temperature Sensor.
Definition at line 41 of file TemperatureSensor.cpp.
{
   if (Sensor::isActive()) {
     if (this->checkAllgood()) {
       return "ACTIVE - GOOD STATUS";
     } else {
       return "ACTIVE - BAD STATUS";
     }
   } else {
     return "INACTIVE";
   }
 }
References checkAllgood(), and Sensor::isActive().
Referenced by main(), and printData().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const TemperatureSensor & sensor) friend
Overloaded operator<<.
Definition at line 36 of file TemperatureSensor.cpp.
{
   sensor.printData();
   return os;
 }
The documentation for this class was generated from the following files:
src/TemperatureSensor.h
src/TemperatureSensor.cpp