Green House software: UsersServer Class Reference
UsersServer Class Reference
#include <UsersServer.h>
Public Member Functions
UsersServer ()
Construct a new Users Server object Creates a new UsersServer object that contains the UsersDatabase object.
~UsersServer ()
Destroy the Users Server object.
void createUser (const std::string name, const std::string nif, const std::string password, const std::string privileges, const std::string email)
Create a User object.
void deleteUser (const std::string nif)
Delete a User object.
void printUsersServer () const
Print all Users Print all users in the UsersDatabase object.
void loadUsersFromFile ()
Load Users from File Load users from a file.
void saveUsersToFile ()
Save Users to File Save users to a file.
bool findUserLogin (std::string name, std::string password, std::string nif)
Find User Login.
std::string getPrivileges (std::string nif)
Get Privileges.
void updateUser (const std::string name, const std::string nif, const std::string password, const std::string privileges, const std::string email)
Update User.
Private Member Functions
void readUsersFromFileTxt ()
This method reads the users from a file txt.
void writeUserToFileTxt ()
This method writes the users to a file txt.
void writeUserToFileBi ()
This method writes the users from a file binary.
void readUsersFromFileBi ()
This method reads the users from a file binary.
Private Attributes
UsersDatabase usersDatabase_
This is the UsersDatabase object.
std::string fileNameTxt_ = "users.txt"
This is the name of the file.
std::string fileNameBi_ = "users.dat"
This is the name of the binary file.
Detailed Description
Definition at line 19 of file UsersServer.h.
Constructor & Destructor Documentation
UsersServer()
UsersServer::UsersServer ()
Construct a new Users Server object Creates a new UsersServer object that contains the UsersDatabase object.
Returns
UsersServer object
Definition at line 17 of file UsersServer.cpp.
{
   // Creamos tres usuarios por defecto
   createUser("admin", "12345678X", "admin", "ADMIN", "admin@example.com");
   createUser("employee", "12345678Y", "employee", "EMPLOYEE",
              "employee@example.com");
   createUser("guest", "12345678Z", "guest", "GUEST", "guest@example.com");
 }
~UsersServer()
UsersServer::~UsersServer ()
Destroy the Users Server object.
Definition at line 25 of file UsersServer.cpp.
{
   // Esto destruira el set de punteros de la base de datos
 }
Member Function Documentation
createUser()
void UsersServer::createUser (const std::string name, const std::string nif, const std::string password, const std::string privileges, const std::string email)
Create a User object.
Parameters
name
nif
password
privileges
email
Definition at line 29 of file UsersServer.cpp.
{
   // Debe de crear el usuario y añadir el puntero al set de usuarios
   User *user = new User(name, nif, password, privileges, email);
   usersDatabase_.addUser(user);
 }
Referenced by main(), and GreenHouse::manageCreateUser().
deleteUser()
void UsersServer::deleteUser (const std::string nif)
Delete a User object.
Parameters
nif
Definition at line 38 of file UsersServer.cpp.
{
   usersDatabase_.deleteUserByNif(nif);
 }
Referenced by main(), and GreenHouse::manageDeleteUser().
findUserLogin()
bool UsersServer::findUserLogin (std::string name, std::string password, std::string nif)
Find User Login.
Parameters
name
password
nif
Returns
true
false
Definition at line 51 of file UsersServer.cpp.
{
   // Debemos de buscar encontrar a un usuario por su nombre, contraseña y nif
   // Si tienen el mismo puntero devolver true, si no false
   if (usersDatabase_.findUserByNif(nif) != nullptr) {
     if (usersDatabase_.findUserByNif(nif)->getName() == name &&
         usersDatabase_.findUserByNif(nif)->getPassword() == password) {
       return true;
     }
   }
   return false;
 }
Referenced by main(), GreenHouse::manageLogin(), and GreenHouse::searchUser().
getPrivileges()
std::string UsersServer::getPrivileges (std::string nif)
Get Privileges.
Parameters
nif
Returns
std::string the privileges
Definition at line 42 of file UsersServer.cpp.
{
   User *user = usersDatabase_.findUserByNif(nif);
   if (user != nullptr) {
     return user->getPrivileges();
   } else {
     return "GUEST";
   }
 }
References User::getPrivileges().
Referenced by main(), and GreenHouse::manageLogin().
loadUsersFromFile()
void UsersServer::loadUsersFromFile ()
Load Users from File Load users from a file.
Definition at line 225 of file UsersServer.cpp.
{
   // Cargo los usuarios del archivo
   // Siguiendo el formato de nombre nif password privilegios email
   try {
     // readUsersFromFileTxt();
     readUsersFromFileBi();
   } catch (FileReadError &e) {
     std::cerr << e.what() << std::endl;
   } catch (FileCloseError &e) {
     std::cerr << e.what() << std::endl;
   } catch (FileOpenError &e) {
     std::cerr << e.what() << std::endl;
   } catch (FileNotFoundError &e) {
     std::cerr << e.what() << std::endl;
   }
   /*
   if (file.is_open()) {
     std::string name, nif, password, privileges, email;
     while (file >> name >> nif >> password >> privileges >> email) {
       createUser(name, nif, password, privileges, email);
     }
     file.close();
   } else {
     std::cerr << "Error: Unable to open file for reading." << std::endl;
   }
   */
 }
Referenced by main(), and GreenHouse::manageLogin().
printUsersServer()
void UsersServer::printUsersServer () const
Print all Users Print all users in the UsersDatabase object.
Definition at line 80 of file UsersServer.cpp.
{
   this->usersDatabase_.printUsers();
 }
Referenced by main(), and GreenHouse::manageAdmin().
readUsersFromFileBi()
void UsersServer::readUsersFromFileBi () private
This method reads the users from a file binary.
Definition at line 84 of file UsersServer.cpp.
{
   std::cout << "Reading users from file " << fileNameBi_ << "..." << std::endl;
   std::ifstream file(fileNameBi_, std::ios::binary);
   if (file.is_open()) {
     while (file) {
       User *user = new User();
       // Read the user name
       size_t nameLength;
       file.read(reinterpret_cast<char *>(&nameLength), sizeof(nameLength));
       if (!file) {
         delete user;
         break;
       }
       char *name = new char[nameLength];
       file.read(name, nameLength);
       if (!file) {
         delete[] name;
         delete user;
         break;
       }
       user->setName(std::string(name, nameLength));
       delete[] name;
       // Read the user nif
       size_t nifLength;
       file.read(reinterpret_cast<char *>(&nifLength), sizeof(nifLength));
       if (!file) {
         delete user;
         break;
       }
       char *nif = new char[nifLength];
       file.read(nif, nifLength);
       if (!file) {
         delete[] nif;
         delete user;
         break;
       }
       user->setNif(std::string(nif, nifLength));
       delete[] nif;
       // Read the user password
       size_t passwordLength;
       file.read(reinterpret_cast<char *>(&passwordLength),
                 sizeof(passwordLength));
       if (!file) {
         delete user;
         break;
       }
       char *password = new char[passwordLength];
       file.read(password, passwordLength);
       if (!file) {
         delete[] password;
         delete user;
         break;
       }
       user->setPassword(std::string(password, passwordLength));
       delete[] password;
       // Read the user privileges
       size_t privilegesLength;
       file.read(reinterpret_cast<char *>(&privilegesLength),
                 sizeof(privilegesLength));
       if (!file) {
         delete user;
         break;
       }
       char *privileges = new char[privilegesLength];
       file.read(privileges, privilegesLength);
       if (!file) {
         delete[] privileges;
         delete user;
         break;
       }
       user->setPrivileges(std::string(privileges, privilegesLength));
       delete[] privileges;
       // Read the user email
       size_t emailLength;
       file.read(reinterpret_cast<char *>(&emailLength), sizeof(emailLength));
       if (!file) {
         delete user;
         break;
       }
       char *email = new char[emailLength];
       file.read(email, emailLength);
       if (!file) {
         delete[] email;
         delete user;
         break;
       }
       user->setEmail(std::string(email, emailLength));
       delete[] email;
       if (file.eof()) {
         delete user; // prevent adding incomplete user due to eof
         break;
       }
       std::cout << "Read user: " << user->getName() << "-" << user->getNif()
                 << "-" << user->getPrivileges() << std::endl;
       usersDatabase_.addUser(user);
     }
     file.close();
   } else {
     std::cerr << "Error: Unable to open file for reading." << std::endl;
   }
 }
References User::getName(), User::getNif(), User::getPrivileges(), User::setEmail(), User::setName(), User::setNif(), User::setPassword(), and User::setPrivileges().
readUsersFromFileTxt()
void UsersServer::readUsersFromFileTxt () private
This method reads the users from a file txt.
Definition at line 194 of file UsersServer.cpp.
{
   std::cout << "Loading users from file " << fileNameTxt_ << "..." << std::endl;
   try {
     std::ifstream file(fileNameTxt_);
     if (!file.good()) {
       file.close();
       throw FileNotFoundError(fileNameTxt_);
     }
     if (!file.is_open()) {
       throw FileOpenError(fileNameTxt_);
     }
     std::string name, nif, password, privileges, email;
     while (file >> name >> nif >> password >> privileges >> email) {
       std::cout << "Read user: " << name << " " << nif << " " << password << " "
                 << privileges << " " << email << std::endl;
       createUser(name, nif, password, privileges, email);
     }
     file.close();
     if (file.is_open()) {
       throw FileCloseError(fileNameTxt_);
     }
   } catch (std::exception &e) {
     // std::cerr << e.what() << std::endl;
     throw;
   }
 }
saveUsersToFile()
void UsersServer::saveUsersToFile ()
Save Users to File Save users to a file.
Definition at line 341 of file UsersServer.cpp.
{
   // Guardo los usuarios en el archivo
   try {
     writeUserToFileTxt();
     writeUserToFileBi();
   } catch (FileOpenError &e) {
     std::cerr << e.what() << std::endl;
   } catch (FileCloseError &e) {
     std::cerr << e.what() << std::endl;
   } catch (FileWriteError &e) {
     std::cerr << e.what() << std::endl;
   } catch (FileNotFoundError &e) {
     std::cerr << e.what() << std::endl;
   }
   /*
   std::cout << "Saving users to file..." << std::endl;
   std::ofstream file(fileNameTxt_);
   if (file.is_open()) {
     for (const User *user : usersDatabase_.getUsers()) {
       file << user->getName() << " " << user->getNif() << " "
            << user->getPassword() << " " << user->getPrivileges() << " "
            << user->getEmail() << std::endl;
       std::cout << "User saved: " << user->getName() << "-" << user->getNif()
                 << std::endl;
     }
     file.close();
   } else {
     std::cerr << "Error: Unable to open file for writing." << std::endl;
   }
   */
 }
Referenced by main(), GreenHouse::manageAdmin(), and GreenHouse::save().
updateUser()
void UsersServer::updateUser (const std::string name, const std::string nif, const std::string password, const std::string privileges, const std::string email)
Update User.
Parameters
name
nif
password
privileges
email
Definition at line 65 of file UsersServer.cpp.
{
   User *userToUpdate = usersDatabase_.findUserByNif(nif);
   // Si el usuario existe, y los privilegios que se quieren cambiar
   // isValidPrivileges entonces se cambian los privilegios y el email
   if (userToUpdate != nullptr && usersDatabase_.isValidPrivileges(privileges)) {
     userToUpdate->setPrivileges(privileges);
     userToUpdate->setEmail(email);
   } else {
     std::cout << "User dosen't change, maybe correct privileges" << std::endl;
   }
 }
References User::setEmail(), and User::setPrivileges().
Referenced by main(), and GreenHouse::manageUpdateUser().
writeUserToFileBi()
void UsersServer::writeUserToFileBi () private
This method writes the users from a file binary.
Definition at line 258 of file UsersServer.cpp.
{
   std::cout << "Saving users to file " << fileNameBi_ << "..." << std::endl;
   std::ofstream file(fileNameBi_, std::ios::binary | std::ios::trunc);
   // Tengo que guardar los usuarios en un archivo binario, recorriendo el set de
   // usuarios Los guardaremos en el binario siguiendo el formato de nombre nif
   // password privilegios email y cuando se lea se leera en el mismo formato
   if (file.is_open()) {
     for (const User *user : usersDatabase_.getUsers()) {
       // Guardar el nombre
       size_t nameLength = user->getName().length();
       file.write(reinterpret_cast<const char *>(&nameLength),
                  sizeof(nameLength));
       file.write(user->getName().c_str(), nameLength);
       // Guardar el nif
       size_t nifLength = user->getNif().length();
       file.write(reinterpret_cast<const char *>(&nifLength), sizeof(nifLength));
       file.write(user->getNif().c_str(), nifLength);
       // Guardar el password
       size_t passwordLength = user->getPassword().length();
       file.write(reinterpret_cast<const char *>(&passwordLength),
                  sizeof(passwordLength));
       file.write(user->getPassword().c_str(), passwordLength);
       // Guardar el privilegios
       size_t privilegesLength = user->getPrivileges().length();
       file.write(reinterpret_cast<const char *>(&privilegesLength),
                  sizeof(privilegesLength));
       file.write(user->getPrivileges().c_str(), privilegesLength);
       // Guardar el email
       size_t emailLength = user->getEmail().length();
       file.write(reinterpret_cast<const char *>(&emailLength),
                  sizeof(emailLength));
       file.write(user->getEmail().c_str(), emailLength);
       // Imprimir el usuario que se ha guardado
       std::cout << "User saved: " << user->getName() << "-" << user->getNif()
                 << std::endl;
     }
     file.close();
   } else {
     std::cerr << "Error: Unable to open file for writing." << std::endl;
   }
 }
writeUserToFileTxt()
void UsersServer::writeUserToFileTxt () private
This method writes the users to a file txt.
Definition at line 307 of file UsersServer.cpp.
{
   std::cout << "Saving users to file " << fileNameTxt_ << "..." << std::endl;
   try {
     std::ofstream file(fileNameTxt_);
     if (!file.good()) {
       file.close();
       throw FileNotFoundError(fileNameTxt_);
     }
     if (!file.is_open()) {
       throw FileOpenError(fileNameTxt_);
     }
     // Write users to file
     for (const User *user : usersDatabase_.getUsers()) {
       file << user->getName() << " " << user->getNif() << " "
            << user->getPassword() << " " << user->getPrivileges() << " "
            << user->getEmail() << std::endl;
       std::cout << "User saved: " << user->getName() << "-" << user->getNif()
                 << std::endl;
     }
     // Close the file
     file.close();
     // Check if file was closed properly
     if (file.is_open()) {
       throw FileCloseError(fileNameTxt_);
     }
   } catch (std::exception &e) {
     std::cerr << e.what() << std::endl;
   }
 }
Member Data Documentation
fileNameBi_
std::string UsersServer::fileNameBi_ = "users.dat" private
This is the name of the binary file.
Definition at line 115 of file UsersServer.h.
fileNameTxt_
std::string UsersServer::fileNameTxt_ = "users.txt" private
This is the name of the file.
Definition at line 110 of file UsersServer.h.
usersDatabase_
UsersDatabase UsersServer::usersDatabase_ private
This is the UsersDatabase object.
Definition at line 104 of file UsersServer.h.
The documentation for this class was generated from the following files:
src/UsersServer.h
src/UsersServer.cpp