Green House software: ScreenHardware Class Reference
ScreenHardware Class Reference
#include <ScreenHardware.h>
Public Member Functions
ScreenHardware (bool active)
Construct a new Screen Hardware object.
~ScreenHardware () override
Destroy the Screen Hardware object.
void displayOutput () const override
This method displays the output of the system.
int askInput () override
Ask for an input to the user (this method in reality is not used, we use the keyboard to ask for an input)
void initialWindow ()
This method displays the initial window of the system.
void loginWindow ()
This method displays the login window of the system.
void mainWindowAdmin ()
This method displays the main window of the system for the admin.
void mainWindowEmployee ()
This method displays the main window of the system for the employee.
void mainWindowGuest ()
This method displays the main window of the system for the guest.
void createUserWindow ()
Create a User object window.
void deleteUserWindow ()
Delete a User object window.
void updateUserWindow ()
Update a User object window.
void displayUsersWindow ()
Display all Users window.
void saveUsersWindow ()
Save the users window.
void createAlarmWindow ()
Create a Alarm Window object.
void deleteAlarmWindow ()
Delete a Alarm Window object.
void displaySensorsWindow ()
Display all Sensors window.
void displayAlarmsWindow ()
Display all Alarms window.
void saveAlarmWindow ()
Save Alarm Window object.
void turnOnOffSystemWindow ()
Turn on or off the system window.
void displayErrorWindow ()
Display the error window.
void cleanScreen ()
Clean the screen.
void exitWindow ()
Exit the window.
void displayCameraWindow ()
Display the camera window.
void createCameraWindow ()
Create a camera window.
void deleteCameraWindow ()
Delete a camera window.
void turnOnOffCameraWindow ()
Turn on or off the camera window.
void saveCameraWindow ()
Save a camera window.
Public Member Functions inherited from Hardware
Hardware ()
Construct a new Hardware object.
Hardware (bool active, Types_Hardware type)
Construct a new Hardware object.
virtual ~Hardware ()
Destroy the Hardware object.
std::string getType () const
Get the Type object.
void setType (std::string newtype)
Set the Type object.
bool isActive () const
If the hardware is active.
void turnOn ()
Turn on the hardware.
void turnOff ()
Turn off the hardware.
std::string stringStatus () const
This method returns if the hardware is active or not in a string.
Additional Inherited Members
Public Types inherited from Hardware
enum Types_Hardware { NONE , SCREEN , KEYBOARD , SWITCH }
Enum of the types of hardware.
Detailed Description
Definition at line 15 of file ScreenHardware.h.
Constructor & Destructor Documentation
ScreenHardware()
ScreenHardware::ScreenHardware (bool active) explicit
Construct a new Screen Hardware object.
Parameters
active
Returns
ScreenHardware object
Definition at line 15 of file ScreenHardware.cpp.
     : Hardware(active, Hardware::Types_Hardware::SCREEN) {}
~ScreenHardware()
ScreenHardware::~ScreenHardware () override
Destroy the Screen Hardware object.
Definition at line 18 of file ScreenHardware.cpp.
 {}
Member Function Documentation
askInput()
int ScreenHardware::askInput () override virtual
Ask for an input to the user (this method in reality is not used, we use the keyboard to ask for an input)
Returns
int
Reimplemented from Hardware.
Definition at line 24 of file ScreenHardware.cpp.
{
   std::cout << "Screen wating a input..." << std::endl;
   return 0;
 }
cleanScreen()
void ScreenHardware::cleanScreen ()
Clean the screen.
Definition at line 206 of file ScreenHardware.cpp.
{
   // Aqui tengo que limpiar la pantalla
   system("clear");
 }
Referenced by MonitoringSystem::cleanScreen(), MonitoringSystem::createAlarmScreen(), MonitoringSystem::createCameraScreen(), MonitoringSystem::createUserScreen(), MonitoringSystem::deleteAlarmScreen(), MonitoringSystem::deleteCameraScreen(), MonitoringSystem::deleteUserScreen(), MonitoringSystem::displayAlarmsScreen(), MonitoringSystem::displayCameraScreen(), MonitoringSystem::displayErrorScreen(), MonitoringSystem::displaySensorsScreen(), MonitoringSystem::displayUsersScreen(), MonitoringSystem::exitScreen(), MonitoringSystem::initialScreen(), MonitoringSystem::loginScreen(), MonitoringSystem::mainWindowAdmin(), MonitoringSystem::mainWindowEmployee(), MonitoringSystem::mainWindowGuest(), MonitoringSystem::saveAlarmScreen(), MonitoringSystem::saveCameraScreen(), MonitoringSystem::saveUsersScreen(), MonitoringSystem::turnOnOffCameraScreen(), MonitoringSystem::turnOnOffSystemScreen(), and MonitoringSystem::updateUserScreen().
createAlarmWindow()
void ScreenHardware::createAlarmWindow ()
Create a Alarm Window object.
Definition at line 173 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para crear una alarma
   std::cout << "---_Create Alarm Window_---" << std::endl;
   std::cout << "First the type(intro), then the id(intro)" << std::endl;
 }
Referenced by MonitoringSystem::createAlarmScreen().
createCameraWindow()
void ScreenHardware::createCameraWindow ()
Create a camera window.
Definition at line 222 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para crear una camara
   std::cout << "---_Create Camera Window_---" << std::endl;
   std::cout << "Creating a new camera..." << std::endl;
 }
Referenced by MonitoringSystem::createCameraScreen().
createUserWindow()
void ScreenHardware::createUserWindow ()
Create a User object window.
Definition at line 143 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para crear un usuario
   std::cout << "---_Create User Window_---" << std::endl;
   std::cout << ASK_DATA << std::endl;
   std::cout << USER_PROMPT << std::endl;
 }
References ASK_DATA, and USER_PROMPT.
Referenced by MonitoringSystem::createUserScreen(), and main().
deleteAlarmWindow()
void ScreenHardware::deleteAlarmWindow ()
Delete a Alarm Window object.
Definition at line 178 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para borrar una alarma
   std::cout << "---_Delete Alarm Window_---" << std::endl;
   std::cout << "Enter the id of the alarm you want to delete" << std::endl;
 }
Referenced by MonitoringSystem::deleteAlarmScreen().
deleteCameraWindow()
void ScreenHardware::deleteCameraWindow ()
Delete a camera window.
Definition at line 228 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para borrar una camara
   std::cout << "---_Delete Camera Window_---" << std::endl;
   std::cout << "Deleting a camera..." << std::endl;
 }
Referenced by MonitoringSystem::deleteCameraScreen().
deleteUserWindow()
void ScreenHardware::deleteUserWindow ()
Delete a User object window.
Definition at line 150 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para borrar un usuario
   std::cout << "---_Delete User Window_---" << std::endl;
   std::cout << "First the name(intro), then the password(intro), then the "
                "nif(intro)"
             << std::endl;
 }
Referenced by MonitoringSystem::deleteUserScreen(), and main().
displayAlarmsWindow()
void ScreenHardware::displayAlarmsWindow ()
Display all Alarms window.
Definition at line 189 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para ver todas las alarmas
   std::cout << "---_Display Alarms Window_---" << std::endl;
 }
Referenced by MonitoringSystem::displayAlarmsScreen(), and main().
displayCameraWindow()
void ScreenHardware::displayCameraWindow ()
Display the camera window.
Definition at line 217 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para ver la camara
   std::cout << "---_Display Camera Window_---" << std::endl;
 }
Referenced by MonitoringSystem::displayCameraScreen().
displayErrorWindow()
void ScreenHardware::displayErrorWindow ()
Display the error window.
Definition at line 200 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu de error
   std::cout << "---_Display Error Window_---" << std::endl;
   std::cout << "And error happend" << std::endl;
 }
Referenced by MonitoringSystem::displayErrorScreen(), and main().
displayOutput()
void ScreenHardware::displayOutput () const override virtual
This method displays the output of the system.
Reimplemented from Hardware.
Definition at line 20 of file ScreenHardware.cpp.
{
   std::cout << "Displaying output..." << std::endl;
 }
displaySensorsWindow()
void ScreenHardware::displaySensorsWindow ()
Display all Sensors window.
Definition at line 184 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para ver todos los sensores
   std::cout << "---_Display Sensors Window_---" << std::endl;
 }
Referenced by MonitoringSystem::displaySensorsScreen(), and main().
displayUsersWindow()
void ScreenHardware::displayUsersWindow ()
Display all Users window.
Definition at line 168 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para ver todos los usuarios
   std::cout << "---_Display Users Window_---" << std::endl;
 }
Referenced by MonitoringSystem::displayUsersScreen(), and main().
exitWindow()
void ScreenHardware::exitWindow ()
Exit the window.
Definition at line 36 of file ScreenHardware.cpp.
{
   // Aqui es el menu de salida
   std::cout << "---_Exit Window_---" << std::endl;
   std::cout << "Thanks for using our system" << std::endl;
 }
Referenced by MonitoringSystem::exitScreen(), and main().
initialWindow()
void ScreenHardware::initialWindow ()
This method displays the initial window of the system.
Definition at line 29 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu principal donde se de la bienvenida
   std::cout << "---_Initial Window_---" << std::endl;
   std::cout << "1. Login" << std::endl;
   std::cout << "2. Exit" << std::endl;
 }
Referenced by MonitoringSystem::initialScreen(), and main().
loginWindow()
void ScreenHardware::loginWindow ()
This method displays the login window of the system.
Definition at line 42 of file ScreenHardware.cpp.
{
   // Este es el menu de login
   std::cout << "---_Login Window_---" << std::endl;
   std::cout << ASK_DATA << std::endl;
   std::cout
       << "First the name(intro), then the password(intro), then the nif(intro)"
       << std::endl;
 }
References ASK_DATA.
Referenced by MonitoringSystem::loginScreen(), and main().
mainWindowAdmin()
void ScreenHardware::mainWindowAdmin ()
This method displays the main window of the system for the admin.
Definition at line 51 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu principal donde se muestran todas las
   // opciones para admins
   std::cout << "---_Main Window Admin_---" << std::endl;
   std::cout << "\n" << std::endl;
   // Seccion de usuarios
   std::cout << "-Users Section-" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "1. Create User" << std::endl;
   std::cout << "2. Delete User" << std::endl;
   std::cout << "3. Update User" << std::endl;
   std::cout << "4. Display Users" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "\n" << std::endl;
   // Seccion de alarmas y sensores
   std::cout << "-Alarms/Sensors Section-" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "5. Create Sensor" << std::endl;
   std::cout << "6. Delete Sensor" << std::endl;
   std::cout << "7. Display Sensors" << std::endl;
   std::cout << "8. Display Alarms" << std::endl;
   std::cout << "9. Turn On/Off Sensors/Alarms" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "\n" << std::endl;
   // Seccion de camaras
   std::cout << "-Cameras Section-" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "10. Display Cameras" << std::endl;
   std::cout << "11. Create Camera" << std::endl;
   std::cout << "12. Delete Camera" << std::endl;
   std::cout << "13. Turn On/Off Cameras" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "\n" << std::endl;
   // Seccion de guardar y salir
   std::cout << "-Save/Exit Section-" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "14. Save Cameras" << std::endl;
   std::cout << "15. Save Users" << std::endl;
   std::cout << "16. Save Sensors" << std::endl;
   std::cout << "17. Exit & Save all" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "\n" << std::endl;
 }
Referenced by main(), and MonitoringSystem::mainWindowAdmin().
mainWindowEmployee()
void ScreenHardware::mainWindowEmployee ()
This method displays the main window of the system for the employee.
Definition at line 95 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu principal donde se muestran todas las
   // opciones para employees
   std::cout << "---_Main Window Employee_---" << std::endl;
   std::cout << "\n" << std::endl;
   // Seccion de sensores y alarmas
   std::cout << "-Sensors/Alarms Section-" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "1. Create Sensor" << std::endl;
   std::cout << "2. Delete Sensor" << std::endl;
   std::cout << "3. Display Sensors" << std::endl;
   std::cout << "4. Display Alarms" << std::endl;
   std::cout << "5. Turn On/Off Sensors/Alarms" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "\n" << std::endl;
   // Seccion de camaras
   std::cout << "-Cameras Section-" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "6. Display Cameras" << std::endl;
   std::cout << "7. Create Camera" << std::endl;
   std::cout << "8. Delete Camera" << std::endl;
   std::cout << "9. Turn On/Off Cameras" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "\n" << std::endl;
   // Seccion de guardar y salir
   std::cout << "-Save/Exit Section-" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "10. Save Cameras" << std::endl;
   std::cout << "11. Save Sensors" << std::endl;
   std::cout << "12. Exit & Save all" << std::endl;
   std::cout << "-------------------------" << std::endl;
 }
Referenced by main(), and MonitoringSystem::mainWindowEmployee().
mainWindowGuest()
void ScreenHardware::mainWindowGuest ()
This method displays the main window of the system for the guest.
Definition at line 128 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu principal donde se muestran todas las
   // opciones para guests
   std::cout << "---_Main Window Guest_---" << std::endl;
   std::cout << "\n" << std::endl;
   // Seccion de sensores y alarmas
   std::cout << "-Sensors/Alarms Section-" << std::endl;
   std::cout << "-------------------------" << std::endl;
   std::cout << "1. Display Sensors" << std::endl;
   std::cout << "2. Display Alarms" << std::endl;
   std::cout << "3. Display Cameras" << std::endl;
   std::cout << "4. Exit" << std::endl;
   std::cout << "-------------------------" << std::endl;
 }
Referenced by main(), and MonitoringSystem::mainWindowGuest().
saveAlarmWindow()
void ScreenHardware::saveAlarmWindow ()
Save Alarm Window object.
Definition at line 211 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para guardar una alarma
   std::cout << "---_Save Alarm Window_---" << std::endl;
   std::cout << "Saving all the sensors(txt/dat)..." << std::endl;
 }
Referenced by MonitoringSystem::saveAlarmScreen().
saveCameraWindow()
void ScreenHardware::saveCameraWindow ()
Save a camera window.
Definition at line 240 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para guardar una camara
   std::cout << "---_Save Camera Window_---" << std::endl;
   std::cout << "Saving all the cameras(txt)..." << std::endl;
 }
Referenced by MonitoringSystem::saveCameraScreen().
saveUsersWindow()
void ScreenHardware::saveUsersWindow ()
Save the users window.
Definition at line 246 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para guardar un usuario
   std::cout << "---_Save User Window_---" << std::endl;
   std::cout << "Saving all the users(txt/dat)..." << std::endl;
 }
Referenced by MonitoringSystem::saveUsersScreen().
turnOnOffCameraWindow()
void ScreenHardware::turnOnOffCameraWindow ()
Turn on or off the camera window.
Definition at line 234 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para encender y apagar la camara
   std::cout << "---_Turn On/Off Camera Window_---" << std::endl;
   std::cout << "1. ON \n2. OFF" << std::endl;
 }
Referenced by MonitoringSystem::turnOnOffCameraScreen().
turnOnOffSystemWindow()
void ScreenHardware::turnOnOffSystemWindow ()
Turn on or off the system window.
Definition at line 194 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para encender y apagar el sistema
   std::cout << "---_Turn On/Off System Window_---" << std::endl;
   std::cout << "1. ON \n2. OFF" << std::endl;
 }
Referenced by main(), and MonitoringSystem::turnOnOffSystemScreen().
updateUserWindow()
void ScreenHardware::updateUserWindow ()
Update a User object window.
Definition at line 158 of file ScreenHardware.cpp.
{
   // Aqui tengo que mostrar un menu para actualizar un usuario
   std::cout << "---_Update User Window_---" << std::endl;
   std::cout << ASK_DATA << std::endl;
   std::cout << "You can change the role / the email / if you want to change "
                "password delete the user and create a new one"
             << std::endl;
   std::cout << USER_PROMPT << std::endl;
 }
References ASK_DATA, and USER_PROMPT.
Referenced by main(), and MonitoringSystem::updateUserScreen().
The documentation for this class was generated from the following files:
src/ScreenHardware.h
src/ScreenHardware.cpp