Green House software: src/mainRGBCamera.cpp File Reference
mainRGBCamera.cpp File Reference
#include "RGBCamera.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 3 of file mainRGBCamera.cpp.
            {
   RGBCamera camera1(1);
   camera1.printCamera();
   camera1.collectData();
   camera1.printCamera();
   camera1.turnOff();
   camera1.printCamera();
   return 0;
 }
References RGBCamera::collectData(), RGBCamera::printCamera(), and Camera::turnOff().