Green House software: src/mainUserGuest.cpp File Reference
mainUserGuest.cpp File Reference
#include "UserGuest.h"
#include <iostream>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 6 of file mainUserGuest.cpp.
            {
   UserGuest user1("Adrian", "234453Y", "ORANGE_JUICE", "correo");
   user1.printUser();
   UserGuest user2;
   user2.setName("Lena");
   user2.setNif("LJ809K5ES43");
   user2.setPassword("Bagumm.87ยก");
   user2.setEmail("correo2");
   user2.printUser();
   return 0;
 }
References User::printUser(), User::setEmail(), User::setName(), User::setNif(), and User::setPassword().