Green House software: src/mainHardware.cpp File Reference
mainHardware.cpp File Reference
#include <iostream>
#include <string>
#include "Hardware.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 7 of file mainHardware.cpp.
            {
   // Aqui tengo que probar los distintos metodos de un objeto Hardware
   Hardware hardware(true, Hardware::Types_Hardware::SWITCH);
   // Pruebas get type set type
   std::cout << hardware.getType() << std::endl;
   hardware.setType("SCREEN");
   std::cout << hardware.getType() << std::endl;
   // Vamos a ver si esta activado y luego desactivamos
   if (hardware.isActive()) {
     std::cout << "Esta activo" << std::endl;
   } else {
     std::cout << "No esta activo" << std::endl;
   }
   hardware.turnOff();
   if (hardware.isActive()) {
     std::cout << "Esta activo" << std::endl;
   } else {
     std::cout << "No esta activo" << std::endl;
   }
   std::cout << hardware.stringStatus() << std::endl;
 }
References Hardware::getType(), Hardware::isActive(), Hardware::setType(), Hardware::stringStatus(), and Hardware::turnOff().