Green House software: src/mainKeyboardHardware.cpp File Reference
mainKeyboardHardware.cpp File Reference
#include <iostream>
#include "KeyboardHardware.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 6 of file mainKeyboardHardware.cpp.
            {
   KeyboardHardware keyboard(true);
   if (keyboard.isActive()) {
     std::cout << "Active" << std::endl;
   } else {
     std::cout << "No Active" << std::endl;
   }
   // apagamos
   keyboard.turnOff();
   std::cout << keyboard.stringStatus() << std::endl;
   // encnedemos
   keyboard.turnOn();
   std::cout << keyboard.stringStatus() << std::endl;
   // Preguntamos un input y luego mostramos el ultimo input
   std::cout << keyboard.askInput() << std::endl;
   std::cout << keyboard.stringInput() << std::endl;
   keyboard.displayOutput();
   return 0;
 }
References KeyboardHardware::askInput(), KeyboardHardware::displayOutput(), Hardware::isActive(), KeyboardHardware::stringInput(), Hardware::stringStatus(), Hardware::turnOff(), and Hardware::turnOn().