Green House software: src/mainScreenHardware.cpp File Reference
mainScreenHardware.cpp File Reference
#include <iostream>
#include "ScreenHardware.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 6 of file mainScreenHardware.cpp.
            {
   ScreenHardware screenHardware(true);
   if (screenHardware.isActive()) {
     std::cout << "Active" << std::endl;
   } else {
     std::cout << "No Active" << std::endl;
   }
   // apagamos
   screenHardware.turnOff();
   std::cout << screenHardware.stringStatus() << std::endl;
   // encnedemos
   screenHardware.turnOn();
   std::cout << screenHardware.stringStatus() << std::endl;
   // Ahora mostramos cada tipo de pantalla para comprobar que funciona
   screenHardware.initialWindow();
   screenHardware.loginWindow();
   screenHardware.mainWindowAdmin();
   screenHardware.mainWindowEmployee();
   screenHardware.mainWindowGuest();
   screenHardware.createUserWindow();
   screenHardware.deleteUserWindow();
   screenHardware.updateUserWindow();
   screenHardware.displayUsersWindow();
   screenHardware.displaySensorsWindow();
   screenHardware.displayAlarmsWindow();
   screenHardware.turnOnOffSystemWindow();
   screenHardware.displayErrorWindow();
   screenHardware.exitWindow();
 }
References ScreenHardware::createUserWindow(), ScreenHardware::deleteUserWindow(), ScreenHardware::displayAlarmsWindow(), ScreenHardware::displayErrorWindow(), ScreenHardware::displaySensorsWindow(), ScreenHardware::displayUsersWindow(), ScreenHardware::exitWindow(), ScreenHardware::initialWindow(), Hardware::isActive(), ScreenHardware::loginWindow(), ScreenHardware::mainWindowAdmin(), ScreenHardware::mainWindowEmployee(), ScreenHardware::mainWindowGuest(), Hardware::stringStatus(), Hardware::turnOff(), Hardware::turnOn(), ScreenHardware::turnOnOffSystemWindow(), and ScreenHardware::updateUserWindow().