Green House software: src/mainPressureSensor.cpp File Reference
mainPressureSensor.cpp File Reference
#include <iostream>
#include "PressureSensor.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 6 of file mainPressureSensor.cpp.
            {
   PressureSensor pressureSensor(1, true);
   // Imprimo la presion por defecto
   pressureSensor.printData();
   // Cambio el valor de la presion
   pressureSensor.collectData();
   // Imprimo la nueva presion
   pressureSensor.printData();
   // Vuelvo a imprimir la presion
   cout << "Pressure: " << pressureSensor.getData() << endl;
   cout << "Status: " << pressureSensor.stringStatus() << endl;
   pressureSensor.collectData();
   // Imprimo el sensor de nuevo
   pressureSensor.printData();
   // Print collect and print
   pressureSensor.collectAndPrint();
 }
References PressureSensor::collectAndPrint(), PressureSensor::collectData(), Sensor::getData(), PressureSensor::printData(), and PressureSensor::stringStatus().