Green House software: src/mainTemperatureSensor.cpp File Reference
mainTemperatureSensor.cpp File Reference
#include <iostream>
#include "TemperatureSensor.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 6 of file mainTemperatureSensor.cpp.
            {
   // Genero un sensor tipo temperatura
   TemperatureSensor tempSensor(1, true);
   // Imprimo la temperatura por defecto
   tempSensor.printData();
   // Cambio el valor de la temperatura
   tempSensor.collectData();
   // Imprimo la nueva temperatura
   tempSensor.printData();
   // Vuelvo a imprimir la temperatura
   cout << "Temperature: " << tempSensor.getData() << endl;
   cout << "Status: " << tempSensor.stringStatus() << endl;
   tempSensor.collectData();
   // Imprimo el sensor de nuevo
   tempSensor.printData();
   // Print collect and print
   tempSensor.collectAndPrint();
 }
References TemperatureSensor::collectAndPrint(), TemperatureSensor::collectData(), Sensor::getData(), TemperatureSensor::printData(), and TemperatureSensor::stringStatus().