Green House software: src/mainHydrometerSensor.cpp File Reference
mainHydrometerSensor.cpp File Reference
#include <iostream>
#include "HydrometerSensor.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 6 of file mainHydrometerSensor.cpp.
            {
   // Genero un sensor tipo hidrometro (mide la humedad del aire)
   HydrometerSensor hydrometer(1, true);
   // Imprimo la hidrometro (mide la humedad del aire) por defecto
   hydrometer.printData();
   // Cambio el valor de la hidrometro (mide la humedad del aire)
   hydrometer.collectData();
   // Imprimo la nueva hidrometro (mide la humedad del aire)
   hydrometer.printData();
   // Vuelvo a imprimir la hidrometro (mide la humedad del aire)
   cout << "Air Quality: " << hydrometer.getData() << endl;
   cout << "Status: " << hydrometer.stringStatus() << endl;
   hydrometer.collectData();
   // Imprimo el sensor de nuevo
   hydrometer.printData();
   // Print collect and print
   hydrometer.collectAndPrint();
 }
References HydrometerSensor::collectAndPrint(), HydrometerSensor::collectData(), Sensor::getData(), HydrometerSensor::printData(), and HydrometerSensor::stringStatus().