Green House software: src/mainLightSensor.cpp File Reference
mainLightSensor.cpp File Reference
#include <iostream>
#include "LightSensor.h"
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 5 of file mainLightSensor.cpp.
            {
   LightSensor lightSensor(1, true);
   // Imprimo la luz por defecto
   lightSensor.printData();
   // Cambio el valor de la luz
   lightSensor.collectData();
   // Imprimo la nueva luz
   lightSensor.printData();
   // Print collect and print
   std::cout << "Light: " << lightSensor.getData() << std::endl;
   // Print collect and print
   std::cout << "Status: " << lightSensor.stringStatus() << std::endl;
   // Imprimo el sensor de nuevo
   lightSensor.collectData();
   // Imprimo el sensor de nuevo
   lightSensor.printData();
   // Print collect and print
   lightSensor.collectAndPrint();
   return 0;
 }
References LightSensor::collectAndPrint(), LightSensor::collectData(), Sensor::getData(), LightSensor::printData(), and LightSensor::stringStatus().